# Curated topic corpus, clusters 14-25. Same tuple shape as topics_1_13.py.

TOPICS_14_25 = {
14: [
 ("Earned value management from first principles","earned value management","applied","Awareness","Informational","What problem does EVM actually solve?"),
 ("PV, EV and AC: the three numbers everything rests on","planned value earned value actual cost","applied","Awareness","Informational","What do the three base measures mean?"),
 ("CPI and SPI, and what they do not tell you","cpi spi meaning","applied","Consideration","Informational","How should performance indices be read?"),
 ("Cost and schedule variance, worked","cost variance schedule variance","applied","Consideration","Informational","How are variances computed and interpreted?"),
 ("EAC and ETC: forecasting from performance","eac etc formula","applied","Consideration","Informational","How do you forecast the finish from today's data?"),
 ("TCPI: the index that tests your promise","to complete performance index","applied","Consideration","Informational","Is the remaining plan achievable?"),
 ("The data EVM needs before it works","evm data requirements","standard","Consideration","Informational","What must be in place before EVM is meaningful?"),
 ("Earned value on agile and hybrid work","agile earned value","comparison","Consideration","Informational","Can EVM survive iterative delivery?"),
 ("EVM system guidelines and where they come from","evms guidelines","standard","Consideration","Informational","Which published guidelines govern EVM systems?"),
 ("Reporting earned value to people who dislike it","evm reporting","asset","Consideration","Informational","How do you make EVM land with executives?"),
 ("Nine ways EVM gets gamed","evm pitfalls","faq","Consideration","Informational","How is earned value manipulated in practice?"),
 ("Percent complete methods, compared","percent complete methods","comparison","Consideration","Comparison","Which measurement method suits which work?"),
 ("A full EVM worked example, end to end","evm worked example","asset","Consideration","Informational","Can I see the whole calculation on one project?"),
 ("Standing up EVM on a live project","implement evm","applied","Decision","Informational","How do you introduce EVM mid-flight?"),
 ("Choosing EVM tooling","evm software","comparison","Decision","Comparison","What should EVM tooling actually do?"),
 ("EVM myths that will not die","evm myths","faq","Awareness","Informational","What do people get wrong about earned value?"),
 ("Earned value for small projects","evm small projects","faq","Consideration","Informational","Is EVM worth it below a certain size?"),
 ("Reading EVM trends over six months","evm trend analysis","applied","Consideration","Informational","What do the curves tell you over time?"),
],
15: [
 ("A risk process that survives delivery pressure","project risk management process","standard","Awareness","Informational","What does a working risk process look like?"),
 ("Risk registers that get used","project risk register","asset","Consideration","Informational","How do you keep a register alive?"),
 ("Qualitative and quantitative risk, compared","qualitative vs quantitative risk","comparison","Consideration","Comparison","When do you need numbers?"),
 ("Monte Carlo simulation for project outcomes","monte carlo project risk","applied","Consideration","Informational","How does simulation produce a confidence range?"),
 ("Risk appetite and tolerance, made concrete","risk appetite project","standard","Consideration","Informational","How do you turn appetite into thresholds?"),
 ("Contingency drawdown discipline","contingency drawdown","applied","Consideration","Informational","How do you release contingency without losing control?"),
 ("Change control that neither blocks nor leaks","project change control","applied","Consideration","Informational","How do you keep change visible and priced?"),
 ("Variations, changes and claims: the distinctions","variation vs change order","comparison","Consideration","Informational","What is the difference, contractually?"),
 ("Trend registers: change before it is change","project trend register","applied","Consideration","Informational","How do you capture emerging cost and time?"),
 ("Issue management when the risk has landed","project issue management","standard","Consideration","Informational","What changes when a risk becomes an issue?"),
 ("Governance frameworks for projects","project governance framework","standard","Consideration","Informational","How is a governance framework structured?"),
 ("Stage gates that decide something","project stage gates","standard","Consideration","Informational","What makes a gate real rather than ceremonial?"),
 ("Independent assurance reviews","project assurance review","standard","Consideration","Informational","Who reviews, and against what?"),
 ("Decision rights: who decides what, at what value","project decision rights","asset","Consideration","Informational","How do you set delegated authority?"),
 ("Escalation that works","project escalation process","standard","Consideration","Informational","When and how should issues escalate?"),
 ("Lessons learned that change the next project","lessons learned process","applied","Retention","Informational","How do lessons actually get used?"),
 ("Risk in AI-assisted forecasting","ai forecasting risk","applied","Consideration","Informational","What new risks does AI introduce to forecasts?"),
 ("Risk management mistakes that recur","risk management mistakes","faq","Consideration","Informational","What goes wrong in most risk processes?"),
 ("Opportunity management, not just threat","project opportunity management","standard","Consideration","Informational","Why is the upside usually ignored?"),
 ("Reporting risk to a board","board risk reporting","asset","Consideration","Informational","What does a board need to see?"),
],
16: [
 ("Project finance and corporate finance, compared","project finance vs corporate finance","comparison","Awareness","Comparison","How is non-recourse finance different?"),
 ("Capital structure basics for project people","project capital structure","applied","Awareness","Informational","How are debt and equity assembled?"),
 ("Sizing debt against a cash flow","debt sizing project finance","applied","Consideration","Informational","How much debt will a project support?"),
 ("Debt service coverage ratio, worked","dscr calculation","applied","Consideration","Informational","How is DSCR computed and read?"),
 ("Loan life coverage ratio, worked","llcr calculation","applied","Consideration","Informational","What does LLCR add over DSCR?"),
 ("How a project financial model is structured","project finance model structure","asset","Consideration","Informational","What are the standard model layers?"),
 ("Sensitivity and scenario analysis","financial model sensitivity","applied","Consideration","Informational","Which variables actually move the answer?"),
 ("What makes a project bankable","bankable project","standard","Consideration","Informational","What do lenders test before committing?"),
 ("Public-private partnership structures","ppp structures explained","standard","Consideration","Informational","How are PPPs assembled and paid?"),
 ("What happens at financial close","financial close process","standard","Consideration","Informational","What must be true before money flows?"),
 ("Forecasting project cash flow","cash flow forecasting project","applied","Consideration","Informational","How do you build the cash curve?"),
 ("Working capital on projects","project working capital","applied","Consideration","Informational","Why do profitable projects run out of cash?"),
 ("NPV and IRR, and where they mislead","npv vs irr","comparison","Consideration","Comparison","When does IRR give the wrong signal?"),
 ("Discounting, payback and hurdle rates","discount rate project","applied","Consideration","Informational","How is the discount rate chosen?"),
 ("Accounting foundations for project managers","accounting basics project managers","applied","Awareness","Informational","What accounting must a delivery lead know?"),
 ("Capex and opex on projects","capex vs opex","comparison","Consideration","Informational","What determines the treatment?"),
 ("Revenue recognition for project work","revenue recognition projects","standard","Consideration","Informational","How is revenue recognised over time?"),
 ("Leases and their project consequences","lease accounting projects","standard","Consideration","Informational","How do leases affect project cost?"),
 ("Budget, forecast and actual: three different jobs","budget vs forecast vs actual","comparison","Consideration","Informational","Why keep all three?"),
 ("Finance for non-financial project managers","finance for project managers","asset","Awareness","Informational","What is the minimum viable finance literacy?"),
],
17: [
 ("Governed AI in project controls","ai project controls","standard","Awareness","Informational","What does governed AI mean in practice?"),
 ("\"AI proposes, the professional disposes\", explained","ai human accountability","standard","Awareness","Informational","Where does accountability sit when AI assists?"),
 ("AI for cost and schedule forecasting","ai forecasting projects","applied","Consideration","Informational","Where does AI genuinely improve forecasts?"),
 ("AI for risk identification","ai risk identification","applied","Consideration","Informational","Can AI surface risks people miss?"),
 ("AI for schedule analysis","ai schedule analysis","applied","Consideration","Informational","What can AI check in a schedule?"),
 ("AI for reporting and narrative","ai project reporting","applied","Consideration","Informational","Where does AI help write the report?"),
 ("The data foundations AI needs","project data foundations","standard","Consideration","Informational","Why does AI fail on poor project data?"),
 ("Prompt discipline for project professionals","prompt engineering project management","asset","Consideration","Informational","How do you ask for analysis you can defend?"),
 ("Validating an AI output before you sign it","validate ai output","applied","Consideration","Informational","How do you check what the model produced?"),
 ("Explainability in project decisions","explainable ai projects","standard","Consideration","Informational","How do you show why the number is the number?"),
 ("Writing an AI-use policy for a project team","ai use policy","asset","Decision","Informational","What belongs in a team AI policy?"),
 ("AI ethics on delivery programmes","ai ethics projects","standard","Consideration","Informational","What ethical lines apply to project AI?"),
 ("AI, confidentiality and client data","ai data privacy projects","trust","Consideration","Informational","What must never go into a prompt?"),
 ("Automation versus augmentation","automation vs augmentation","comparison","Consideration","Comparison","Which tasks should be automated at all?"),
 ("How AI fails on projects","ai failures projects","faq","Consideration","Informational","What are the common failure modes?"),
 ("Choosing AI tools for a controls team","ai tool selection","comparison","Decision","Comparison","How do you evaluate a project AI tool?"),
 ("Building an AI-ready project data model","ai ready data model","applied","Consideration","Informational","What structure does the data need?"),
 ("Raising AI literacy across a controls team","ai literacy training","career","Decision","Informational","How do you upskill a whole team?"),
 ("Audit trails for AI-assisted decisions","ai audit trail","trust","Consideration","Informational","What record proves how a decision was made?"),
 ("A responsible-AI checklist for project work","responsible ai checklist","asset","Decision","Informational","What do you check before relying on AI output?"),
],
18: [
 ("Dashboard design principles for projects","project dashboard design","asset","Consideration","Informational","What makes a dashboard decision-useful?"),
 ("Choosing KPIs that change behaviour","project kpis","standard","Consideration","Informational","Which measures actually drive action?"),
 ("Reporting cadence and audience","project reporting frequency","standard","Consideration","Informational","Who needs what, how often?"),
 ("Executive reporting on complex projects","executive project report","asset","Consideration","Informational","How do you brief a busy executive honestly?"),
 ("Data visualisation for project data","project data visualisation","applied","Consideration","Informational","Which chart for which project question?"),
 ("Power BI for project controls","power bi project controls","applied","Decision","Informational","How do you build a controls model in Power BI?"),
 ("Excel dashboards that do not break","excel project dashboard","applied","Decision","Informational","How do you build a maintainable Excel dashboard?"),
 ("Automating the monthly report","automate project reporting","applied","Decision","Informational","What can be automated safely?"),
 ("One source of truth, in practice","single source of truth project","standard","Consideration","Informational","How do you stop competing numbers?"),
 ("Designing drill-down that answers the next question","dashboard drill down","applied","Consideration","Informational","How deep should a dashboard go?"),
 ("Narrative and numbers together","project report narrative","asset","Consideration","Informational","How much prose does a report need?"),
 ("Why traffic lights hide problems","rag status reporting","faq","Consideration","Informational","What is wrong with red-amber-green?"),
 ("Presenting a forecast people will act on","presenting project forecast","applied","Consideration","Informational","How do you present uncertainty?"),
 ("Portfolio dashboards for many projects","portfolio dashboard","applied","Consideration","Informational","How does reporting change at portfolio level?"),
 ("Accessible reporting","accessible dashboard design","standard","Consideration","Informational","How do you make reports readable for everyone?"),
 ("From dashboard to decision support","decision support system projects","standard","Consideration","Informational","When does reporting become decision support?"),
],
19: [
 ("Recommended practices in cost engineering: an orientation","aace recommended practices","standard","Consideration","Informational","What are recommended practices and how are they used?"),
 ("Estimate classification systems","estimate classification system","standard","Consideration","Informational","How do classification systems define accuracy?"),
 ("Earned value system guidelines","evms 748 guidelines","standard","Consideration","Informational","What do EVM system guidelines require?"),
 ("NEC contracts and project controls","nec contract project controls","standard","Consideration","Informational","What does NEC demand of controls?"),
 ("FIDIC contracts and project controls","fidic project controls","standard","Consideration","Informational","What does FIDIC demand of controls?"),
 ("Contract types and their controls consequences","contract types projects","comparison","Consideration","Comparison","How does contract form change controls?"),
 ("Claims: the controls evidence that decides them","construction claims evidence","applied","Consideration","Informational","What records win or lose a claim?"),
 ("ISO standards relevant to project delivery","iso project management standards","standard","Consideration","Informational","Which ISO standards touch project work?"),
 ("Standards, guidance and recommended practice","standard vs guidance","comparison","Awareness","Informational","What is the difference in authority?"),
 ("Programme and portfolio standards","programme management standards","standard","Consideration","Informational","How do standards scale above the project?"),
 ("Documentation standards for controls","project documentation standards","standard","Consideration","Informational","What must be documented, and how?"),
 ("Records management for disputes","project records management","applied","Consideration","Informational","What do you keep, and for how long?"),
 ("Emerging standards for AI in projects","ai standards projects","standard","Consideration","Informational","Which AI standards are becoming relevant?"),
 ("A map of the standards landscape","project standards landscape","asset","Awareness","Informational","How do the standards bodies relate?"),
],
20: [
 ("Primavera P6 fundamentals","primavera p6 basics","applied","Awareness","Informational","What does P6 do that simpler tools cannot?"),
 ("Cost in Primavera P6","p6 cost loading","applied","Consideration","Informational","How do you resource- and cost-load in P6?"),
 ("Microsoft Project fundamentals","microsoft project basics","applied","Awareness","Informational","What is MS Project good at?"),
 ("Primavera P6 versus Microsoft Project","p6 vs microsoft project","comparison","Decision","Comparison","Which scheduling tool should a team standardise on?"),
 ("Power BI for controls reporting","power bi reporting projects","applied","Decision","Informational","How do you connect project data to Power BI?"),
 ("The Excel skills a controls professional needs","excel for project controls","asset","Consideration","Informational","Which Excel skills matter most?"),
 ("Financial modelling in Excel for projects","excel financial model project","applied","Consideration","Informational","How do you structure a project model?"),
 ("Choosing a scheduling tool","scheduling tool selection","comparison","Decision","Comparison","How do you evaluate scheduling tools?"),
 ("Risk analysis tooling","project risk analysis software","comparison","Decision","Comparison","What should risk tooling provide?"),
 ("Cost management tooling","project cost management software","comparison","Decision","Comparison","What should cost tooling provide?"),
 ("Document control systems","document control system","standard","Decision","Informational","What does document control need to do?"),
 ("AI assistants in day-to-day project work","ai assistant project work","applied","Consideration","Informational","Where do assistants save real time?"),
 ("Integrating project data across tools","project data integration","applied","Decision","Informational","How do you move data without losing meaning?"),
 ("Tool governance: who changes what","project tool governance","standard","Consideration","Informational","How do you stop tool sprawl?"),
 ("Migrating between project tools","project tool migration","applied","Decision","Informational","How do you migrate without losing history?"),
 ("A templates library worth maintaining","project controls templates","asset","Consideration","Informational","Which templates repay the effort?"),
 ("Scripting and automation for controls data","automate project data","applied","Consideration","Informational","What should be scripted?"),
 ("Extracting analysis from a schedule file","schedule data extraction","applied","Consideration","Informational","How do you analyse a schedule outside the tool?"),
 ("Version control for project data","project data version control","standard","Consideration","Informational","How do you know which file is current?"),
 ("The tool skills employers ask for","project controls tool skills","career","Decision","Commercial","Which tools appear most in job adverts?"),
],
21: [
 ("The planning engineer role, described honestly","planning engineer role","career","Awareness","Commercial","What does a planning engineer do all day?"),
 ("The scheduler role, described honestly","project scheduler role","career","Awareness","Commercial","How does scheduling differ from planning?"),
 ("The cost engineer role, described honestly","cost engineer role","career","Awareness","Commercial","What does a cost engineer own?"),
 ("The cost controller role","cost controller role","career","Awareness","Commercial","How does control differ from engineering?"),
 ("The estimator role","estimator role","career","Awareness","Commercial","What does an estimator produce?"),
 ("The earned value analyst role","evm analyst role","career","Awareness","Commercial","What does an EVM analyst do?"),
 ("The risk analyst role","project risk analyst role","career","Awareness","Commercial","What does a risk analyst produce?"),
 ("The project accountant role","project accountant role","career","Awareness","Commercial","Where does project accounting sit?"),
 ("The PMO analyst role","pmo analyst role","career","Awareness","Commercial","What does a PMO analyst actually deliver?"),
 ("The PMO manager role","pmo manager role","career","Consideration","Commercial","What changes at PMO management level?"),
 ("The project controls manager role","project controls manager role","career","Consideration","Commercial","What does the manager own that the analyst does not?"),
 ("The project controls director role","project controls director role","career","Consideration","Commercial","What does leadership look like at director level?"),
 ("The commercial manager role","commercial manager role","career","Consideration","Commercial","Where do commercial and controls overlap?"),
 ("The contracts administrator role","contracts administrator role","career","Awareness","Commercial","What does contract administration involve?"),
 ("The project data analyst role","project data analyst role","career","Awareness","Commercial","What does data analysis add to controls?"),
 ("Preparing for a project controls interview","project controls interview questions","asset","Decision","Informational","What are you actually being tested on?"),
 ("A CV that shows controls capability","project controls cv","asset","Decision","Informational","How do you evidence controls skill on paper?"),
 ("Researching pay for controls roles, properly","project controls salary research","career","Decision","Informational","How do you find reliable pay data yourself?"),
 ("Contract and freelance project controls work","freelance project controls","career","Decision","Commercial","What changes when you contract?"),
],
22: [
 ("Project controls careers in the United Kingdom","project controls jobs uk","career","Decision","Commercial","What does the UK market look like?"),
 ("Project controls careers in Ireland","project controls jobs ireland","career","Decision","Commercial","What does the Irish market look like?"),
 ("Project controls careers in the Netherlands","project controls jobs netherlands","career","Decision","Commercial","What does the Dutch market look like?"),
 ("Project controls careers in Germany","project controls jobs germany","career","Decision","Commercial","What does the German market look like?"),
 ("Project controls careers in the Nordics","project controls jobs nordics","career","Decision","Commercial","What do the Nordic markets look like?"),
 ("Project controls careers in Poland and CEE","project controls jobs poland","career","Decision","Commercial","What does the CEE market look like?"),
 ("Project controls careers in the United Arab Emirates","project controls jobs uae","career","Decision","Commercial","What does the UAE market look like?"),
 ("Project controls careers in Saudi Arabia","project controls jobs saudi arabia","career","Decision","Commercial","What does the Saudi market look like?"),
 ("Project controls careers in Qatar","project controls jobs qatar","career","Decision","Commercial","What does the Qatari market look like?"),
 ("Project controls careers in Oman and the wider Gulf","project controls jobs oman","career","Decision","Commercial","What does the wider Gulf market look like?"),
 ("Project controls careers in India","project controls jobs india","career","Decision","Commercial","What does the Indian market look like?"),
 ("Project controls careers in Singapore","project controls jobs singapore","career","Decision","Commercial","What does the Singapore market look like?"),
 ("Project controls careers in Malaysia","project controls jobs malaysia","career","Decision","Commercial","What does the Malaysian market look like?"),
 ("Project controls careers in Australia","project controls jobs australia","career","Decision","Commercial","What does the Australian market look like?"),
 ("Project controls careers in New Zealand","project controls jobs new zealand","career","Decision","Commercial","What does the New Zealand market look like?"),
 ("Project controls careers in Canada","project controls jobs canada","career","Decision","Commercial","What does the Canadian market look like?"),
 ("Project controls careers in the United States","project controls jobs usa","career","Decision","Commercial","What does the US market look like?"),
 ("Project controls careers in South Africa","project controls jobs south africa","career","Decision","Commercial","What does the South African market look like?"),
 ("Project controls careers in Nigeria and West Africa","project controls jobs nigeria","career","Decision","Commercial","What does the West African market look like?"),
 ("Project controls careers in Brazil and Latin America","project controls jobs brazil","career","Decision","Commercial","What does the Latin American market look like?"),
],
23: [
 ("PCI PCL-AI and PMI-SP compared","pcl-ai vs pmi-sp","comparison","Decision","Comparison","Scheduling specialism or controls breadth?"),
 ("PCI PCL-AI and PMI-RMP compared","pcl-ai vs pmi-rmp","comparison","Decision","Comparison","Risk specialism or controls breadth?"),
 ("PCI credentials and CAPM compared","pci vs capm","comparison","Decision","Comparison","Where should an entry-level candidate start?"),
 ("PCI PML-AI and PMP compared","pml-ai vs pmp","comparison","Decision","Comparison","Which leadership credential fits my career?"),
 ("PCI PML-AI and PRINCE2 Practitioner compared","pml-ai vs prince2 practitioner","comparison","Decision","Comparison","Method certification or leadership credential?"),
 ("PCI PML-AI and PgMP compared","pml-ai vs pgmp","comparison","Decision","Comparison","Programme scope or delivery leadership?"),
 ("PCI credentials and MSP compared","pci vs msp","comparison","Decision","Comparison","Where does programme method fit?"),
 ("PCI credentials and APM PMQ compared","pci vs apm pmq","comparison","Decision","Comparison","How do these qualifications differ in purpose?"),
 ("PCI credentials and APM Chartered status compared","pci vs chartered project professional","comparison","Decision","Comparison","Credential or chartership?"),
 ("PCI PCL-AI and AACE CCP compared","pcl-ai vs ccp","comparison","Decision","Comparison","Cost professional depth or integrated controls?"),
 ("PCI PCL-AI and AACE PSP compared","pcl-ai vs psp","comparison","Decision","Comparison","Scheduling depth or integrated controls?"),
 ("PCI PCL-AI and AACE EVP compared","pcl-ai vs evp","comparison","Decision","Comparison","Earned value specialism or breadth?"),
 ("PCI PCL-AI and AACE CEP compared","pcl-ai vs cep","comparison","Decision","Comparison","Estimating specialism or breadth?"),
 ("PCI PML-AI and Scrum certifications compared","pml-ai vs scrum certification","comparison","Decision","Comparison","Agile role training or delivery leadership?"),
 ("PCI PML-AI and SAFe certifications compared","pml-ai vs safe","comparison","Decision","Comparison","Scaled agile framework or leadership credential?"),
 ("PCI credentials and Lean Six Sigma compared","pci vs six sigma","comparison","Decision","Comparison","Process improvement or project delivery?"),
 ("PCI credentials and ITIL compared","pci vs itil","comparison","Decision","Comparison","Service management or project delivery?"),
 ("PCI credentials and IPMA levels compared","pci vs ipma","comparison","Decision","Comparison","Competence levels or credential architecture?"),
 ("PMP, PRINCE2 and PCI: a three-way orientation","pmp vs prince2 vs pci","comparison","Decision","Comparison","How do the three approaches differ?"),
 ("Which project credential for construction delivery","project certification construction","comparison","Decision","Comparison","What suits construction specifically?"),
 ("Which project credential for IT and digital delivery","project certification it projects","comparison","Decision","Comparison","What suits software and digital work?"),
 ("Which project credential for energy and infrastructure","project certification energy","comparison","Decision","Comparison","What suits capital projects?"),
 ("How employers read project credentials","employers project certifications","comparison","Decision","Informational","How much weight does a credential carry in hiring?"),
 ("The true cost of project credentials, compared","project certification cost comparison","comparison","Decision","Comparison","What is the total cost of each pathway?"),
 ("Renewal and CPD burden, compared","certification renewal comparison","comparison","Decision","Comparison","What does each credential demand after you pass?"),
 ("A decision guide for project credentials","project certification decision guide","asset","Decision","Comparison","Which credential should I choose, given my situation?"),
],
24: [
 ("PCI PFL-AI and CPA compared","pfl-ai vs cpa","comparison","Decision","Comparison","Licensed accountancy or project finance capability?"),
 ("PCI PFL-AI and ACCA compared","pfl-ai vs acca","comparison","Decision","Comparison","Broad accountancy or project finance focus?"),
 ("PCI PFL-AI and CIMA compared","pfl-ai vs cima","comparison","Decision","Comparison","Management accounting or project finance?"),
 ("PCI PFL-AI and CIA compared","pfl-ai vs cia","comparison","Decision","Comparison","Internal audit or project finance?"),
 ("PCI PFL-AI and CISA compared","pfl-ai vs cisa","comparison","Decision","Comparison","Information systems audit or project finance?"),
 ("PCI PFL-AI and treasury credentials compared","pfl-ai vs treasury certification","comparison","Decision","Comparison","Corporate treasury or project finance?"),
 ("PCI PFL-AI and financial-modelling certificates compared","pfl-ai vs financial modelling certificate","comparison","Decision","Comparison","Modelling technique or project finance judgement?"),
 ("PCI PFL-AI and alternative-investment credentials compared","pfl-ai vs caia","comparison","Decision","Comparison","Investment analysis or project delivery finance?"),
 ("PCI PFL-AI and risk-management credentials compared","pfl-ai vs frm","comparison","Decision","Comparison","Financial risk or project finance?"),
 ("PCI credentials and data-analytics certifications compared","pci vs data analytics certification","comparison","Decision","Comparison","Analytics tooling or project domain?"),
 ("PCI credentials and cloud certifications: relevance","pci vs cloud certification","comparison","Decision","Comparison","Do platform certifications help project professionals?"),
 ("The finance credential landscape for project people","finance certifications project professionals","asset","Consideration","Comparison","How does the landscape fit together?"),
 ("Which finance credential for infrastructure","infrastructure finance certification comparison","comparison","Decision","Comparison","What suits infrastructure finance?"),
 ("Which finance credential for renewables","renewables finance certification","comparison","Decision","Comparison","What suits renewable-energy finance?"),
 ("Which finance credential for PPP work","ppp certification","comparison","Decision","Comparison","What suits PPP practitioners?"),
 ("Audit credentials and project finance compared","audit vs project finance certification","comparison","Decision","Comparison","How different are the disciplines?"),
 ("Accounting qualifications and project finance compared","accounting vs project finance","comparison","Decision","Comparison","Does accountancy cover project finance?"),
 ("The cost of finance credentials, compared","finance certification cost comparison","comparison","Decision","Comparison","What does each pathway cost?"),
 ("The time commitment of finance credentials, compared","finance certification time","comparison","Decision","Comparison","How long does each take?"),
 ("Renewal and CPD across finance credentials","finance certification cpd","comparison","Decision","Comparison","What maintenance does each require?"),
 ("Jurisdiction constraints on finance credentials","finance certification jurisdiction","comparison","Decision","Informational","Which credentials are jurisdiction-bound?"),
 ("Do you need a CPA to work in project finance?","cpa for project finance","faq","Decision","Informational","Is an accountancy licence required?"),
 ("Combining PFL-AI with an accountancy qualification","pfl-ai and accounting qualification","comparison","Decision","Comparison","Do the two complement each other?"),
 ("A decision guide for finance credentials","finance certification decision guide","asset","Decision","Comparison","Which finance credential should I choose?"),
],
25: [
 ("Is PCI certification accredited? An honest answer","is pci certification accredited","trust","Consideration","Informational","What is PCI's accreditation position?"),
 ("Will a PCI certification get me a job?","will certification get me a job","faq","Consideration","Informational","What can and cannot a credential do for hiring?"),
 ("How hard is a PCI examination?","how hard is pci exam","faq","Consideration","Informational","What level of difficulty should I expect?"),
 ("What happens if you fail","fail certification exam","faq","Consideration","Informational","Is failing recoverable?"),
 ("Certifying without a degree","certification without degree","faq","Consideration","Informational","Does the lack of a degree block me?"),
 ("Certifying from a non-technical background","non technical project certification","faq","Consideration","Informational","Can a non-engineer succeed?"),
 ("How much mathematics is involved?","project controls maths","faq","Consideration","Informational","Do I need strong maths?"),
 ("How much study time is realistic?","certification study hours","faq","Consideration","Informational","How many hours should I budget?"),
 ("Studying while working full time","study while working full time","asset","Consideration","Informational","How do people fit study around a job?"),
 ("What online proctoring is actually like","online proctoring experience","faq","Decision","Informational","What does remote invigilation involve?"),
 ("If your connection fails mid-examination","internet fails during exam","faq","Decision","Informational","What happens to my attempt?"),
 ("Calculators, notes and permitted materials","calculator allowed exam","faq","Decision","Informational","What may I use during the exam?"),
 ("Where practice examinations fit","practice exams value","faq","Consideration","Informational","How useful are mocks?"),
 ("How PCI examinations are marked and reported","how are exams marked","faq","Decision","Informational","How is my result determined and presented?"),
 ("When results arrive","when do exam results come","faq","Decision","Informational","How long is the wait?"),
 ("Appealing a result","appeal exam result","faq","Retention","Informational","What if I think the result is wrong?"),
 ("Recognition of PCI credentials abroad","certification recognised internationally","trust","Consideration","Informational","How is a credential treated in other countries?"),
 ("Myth: AI is about to replace planners","will ai replace planners","faq","Awareness","Informational","Is the planning role disappearing?"),
 ("Myth: certifications do not matter any more","do certifications matter","faq","Awareness","Informational","Has experience made credentials irrelevant?"),
 ("Myth: you need ten years before certifying","experience needed for certification","faq","Awareness","Informational","How much experience is really required?"),
 ("Case scenario: the graduate with no project history","graduate project controls","asset","Consideration","Informational","What should a graduate do first?"),
 ("Case scenario: the mid-career switcher","career switch to project controls","asset","Consideration","Informational","How does a switcher build credibility fast?"),
 ("Case scenario: the experienced planner going deeper","experienced planner certification","asset","Consideration","Informational","What does a veteran gain?"),
 ("Case scenario: the finance professional entering projects","finance professional project career","asset","Consideration","Informational","How does a finance person cross over?"),
],
}
