# Curated topic corpus, clusters 1-13. Each entry: (working title, primary keyword,
# content type, funnel stage, search intent, real question answered).
# Content types carry the master prompt's quota tags: comparison | faq | career | applied |
# trust | pricing-route | asset | standard.

TOPICS_1_13 = {
1: [
 ("What \"developed with reference to ISO/IEC 17024\" means at PCI","iso 17024 certification meaning","trust","Consideration","Informational","What does referencing ISO/IEC 17024 actually commit PCI to?"),
 ("PCI's accreditation status, stated plainly","is pci accredited","trust","Consideration","Informational","Is PCI accredited, and by whom?"),
 ("Who makes PCI certification decisions","pci certification board","trust","Consideration","Informational","Which people and committees decide outcomes?"),
 ("Impartiality by design: why PCI separates the standard from the training","certification body impartiality","trust","Consideration","Informational","Why does PCI not sell its own exam preparation?"),
 ("How PCI writes and maintains a body of knowledge","body of knowledge development","trust","Awareness","Informational","How is the examined syllabus produced and kept current?"),
 ("Complaints and appeals at PCI","certification appeal process","trust","Retention","Informational","How do I challenge a decision I believe is wrong?"),
 ("Ethics and professional conduct for PCI certificants","project controls code of conduct","trust","Retention","Informational","What conduct is expected of a certificant?"),
 ("How PCI handles candidate data","certification body data protection","trust","Consideration","Informational","What happens to my personal data and ID documents?"),
 ("PCI's AI-use and academic-integrity policy for candidates","exam ai policy","trust","Consideration","Informational","Where is AI allowed in preparation and assessment?"),
 ("When a PCI credential can be revoked","certification revocation","trust","Retention","Informational","What could cause a credential to be withdrawn?"),
 ("Why PCI exists: the case for an integrated project-controls credential","why project controls certification","trust","Awareness","Informational","What gap is PCI trying to close?"),
 ("Reasonable adjustments and accessibility in PCI examinations","exam reasonable adjustments","trust","Consideration","Informational","What adjustments can I request, and how?"),
],
2: [
 ("The three-years-of-experience rule, explained","project controls certification experience requirement","pricing-route","Decision","Informational","What counts toward the three-year requirement?"),
 ("Membership or certification: what each one gives you","pci membership vs certification","pricing-route","Decision","Commercial","Do I need membership, certification, or both?"),
 ("The membership + exam bundle, explained","pci exam bundle","pricing-route","Decision","Commercial","Is the bundle worth it for my situation?"),
 ("Discount codes, waivers and sponsorships at PCI","pci discount code","pricing-route","Decision","Commercial","What reductions exist and who qualifies?"),
 ("Payments, receipts and refunds","pci refund policy","pricing-route","Decision","Informational","What happens if I pay twice or need to cancel?"),
 ("The Founding Route, explained","pci founding route","pricing-route","Decision","Informational","What is the founding cohort and how does someone join?"),
 ("Employer-sponsored candidates: how sponsorship works","employer sponsored certification","career","Decision","Commercial","How does an employer pay for and track candidates?"),
 ("Do I need PCI membership to sit an examination?","pci membership required exam","pricing-route","Decision","Informational","Is membership a prerequisite for the exam?"),
 ("Taking more than one PCI certification","multiple pci certifications","pricing-route","Decision","Commercial","Can I hold two or three credentials, and should I?"),
 ("Currency, payment methods and instalments","pci payment methods","pricing-route","Decision","Informational","How can I pay, and are instalments available?"),
 ("How long a PCI credential lasts","pci credential validity","pricing-route","Consideration","Informational","When does my credential expire?"),
 ("Booking, rescheduling and missed examinations","reschedule pci exam","faq","Decision","Informational","What happens if I need to move my exam date?"),
 ("Identity requirements for a proctored PCI examination","online proctored exam id","faq","Decision","Informational","What ID do I need on exam day?"),
 ("From submission to decision: certification timelines","pci certification timeline","pricing-route","Decision","Informational","How long does each stage take?"),
],
3: [
 ("Is PCL-AI the right credential for you?","pcl-ai candidate profile","standard","Consideration","Informational","Does my role and experience fit PCL-AI?"),
 ("Earned value in PCL-AI: what is examined","pcl-ai earned value","faq","Consideration","Informational","How deeply does PCL-AI test EVM?"),
 ("Forecasting in PCL-AI: what is examined","pcl-ai forecasting","faq","Consideration","Informational","What forecasting competence does PCL-AI assess?"),
 ("Risk in PCL-AI: what is examined","pcl-ai risk management","faq","Consideration","Informational","What risk competence does PCL-AI assess?"),
 ("Planning and scheduling in PCL-AI: what is examined","pcl-ai scheduling","faq","Consideration","Informational","What scheduling competence does PCL-AI assess?"),
 ("Cost control in PCL-AI: what is examined","pcl-ai cost control","faq","Consideration","Informational","What cost competence does PCL-AI assess?"),
 ("Governed AI in PCL-AI: what is examined","pcl-ai artificial intelligence","faq","Consideration","Informational","What does PCL-AI expect you to do with AI?"),
 ("A worked PCL-AI scenario question, step by step","pcl-ai sample question","asset","Consideration","Informational","What does a scenario question actually look like?"),
 ("What PCL-AI adds to ten years of site experience","certification vs experience","standard","Consideration","Informational","I already do this work — what does the credential add?"),
 ("From PCP-AI to PCL-AI: the rename explained","pcp-ai renamed","faq","Awareness","Informational","I saw PCP-AI referenced — is that the same credential?"),
 ("PCL-AI for construction professionals","project controls certification construction","career","Consideration","Commercial","How does PCL-AI map to construction delivery?"),
 ("PCL-AI for energy and infrastructure","project controls certification energy","career","Consideration","Commercial","How does PCL-AI map to energy projects?"),
 ("PCL-AI for defence, aerospace and regulated programmes","project controls certification defence","career","Consideration","Commercial","How does PCL-AI map to regulated programmes?"),
 ("Building a PCL-AI study plan around a full-time job","pcl-ai study plan","applied","Decision","Informational","How do I prepare without taking leave?"),
 ("Five ways PCL-AI candidates lose marks","pcl-ai exam mistakes","faq","Decision","Informational","What are the common preparation mistakes?"),
],
4: [
 ("Is PFL-AI the right credential for you?","pfl-ai candidate profile","standard","Consideration","Informational","Does my role and experience fit PFL-AI?"),
 ("Financial modelling in PFL-AI: what is examined","pfl-ai financial modelling","faq","Consideration","Informational","What modelling competence does PFL-AI assess?"),
 ("Capital structure in PFL-AI: what is examined","pfl-ai capital structure","faq","Consideration","Informational","What does PFL-AI expect on debt and equity?"),
 ("Bankability in PFL-AI: what is examined","project bankability","faq","Consideration","Informational","What makes a project bankable, and how is it tested?"),
 ("Coverage ratios in PFL-AI: DSCR, LLCR and what they mean","dscr project finance","applied","Consideration","Informational","How are coverage ratios calculated and read?"),
 ("PPP structures in PFL-AI: what is examined","ppp project finance","faq","Consideration","Informational","What PPP knowledge does PFL-AI assess?"),
 ("Financial close in PFL-AI: what is examined","project financial close","faq","Consideration","Informational","What happens at financial close?"),
 ("Accounting foundations for PFL-AI candidates","accounting for project managers","faq","Consideration","Informational","How much accounting do I actually need?"),
 ("A worked PFL-AI scenario question, step by step","pfl-ai sample question","asset","Consideration","Informational","What does a PFL-AI scenario look like?"),
 ("PFL-AI for infrastructure finance professionals","infrastructure finance certification","career","Consideration","Commercial","How does PFL-AI map to infrastructure finance?"),
 ("PFL-AI for renewable-energy projects","renewable energy project finance","career","Consideration","Commercial","How does PFL-AI map to renewables?"),
 ("PFL-AI for PMO and commercial leads","commercial manager certification","career","Consideration","Commercial","Why would a commercial lead take a finance credential?"),
 ("Building a PFL-AI study plan","pfl-ai study plan","applied","Decision","Informational","How should I sequence PFL-AI preparation?"),
 ("Where PFL-AI candidates go wrong","pfl-ai exam mistakes","faq","Decision","Informational","What trips PFL-AI candidates up?"),
 ("Project cash flow: the skill PFL-AI keeps testing","project cash flow forecasting","applied","Consideration","Informational","Why is cash flow central to project finance?"),
 ("NPV, IRR and payback for project decisions","npv irr project appraisal","applied","Consideration","Informational","How do appraisal metrics drive real decisions?"),
],
5: [
 ("Is PML-AI the right credential for you?","pml-ai candidate profile","standard","Consideration","Informational","Does my role and experience fit PML-AI?"),
 ("Governance in PML-AI: what is examined","project governance certification","faq","Consideration","Informational","What governance competence does PML-AI assess?"),
 ("Delivery planning in PML-AI: what is examined","pml-ai delivery planning","faq","Consideration","Informational","How does PML-AI test planning at leadership level?"),
 ("Agile and hybrid delivery in PML-AI","agile hybrid project delivery","faq","Consideration","Informational","How does PML-AI treat agile and hybrid methods?"),
 ("Stakeholder leadership in PML-AI","project stakeholder leadership","faq","Consideration","Informational","What leadership behaviour does PML-AI assess?"),
 ("AI-enabled project management in PML-AI","ai project management","faq","Consideration","Informational","What does PML-AI expect a leader to do with AI?"),
 ("A worked PML-AI scenario question, step by step","pml-ai sample question","asset","Consideration","Informational","What does a PML-AI scenario look like?"),
 ("PML-AI for PMO leads","pmo lead certification","career","Consideration","Commercial","How does PML-AI map to PMO leadership?"),
 ("PML-AI for programme managers","programme manager certification","career","Consideration","Commercial","How does PML-AI map to programme management?"),
 ("Building a PML-AI study plan","pml-ai study plan","applied","Decision","Informational","How should I sequence PML-AI preparation?"),
 ("Where PML-AI candidates go wrong","pml-ai exam mistakes","faq","Decision","Informational","What trips PML-AI candidates up?"),
 ("Benefits realisation in PML-AI","benefits realisation management","standard","Consideration","Informational","How is benefits thinking assessed?"),
 ("Leading delivery teams under pressure","project team leadership","applied","Consideration","Informational","What leadership practice does the credential reward?"),
 ("Delivery assurance and independent review","delivery assurance review","standard","Consideration","Informational","How does assurance fit a leader's job?"),
 ("PML-AI for consultants and advisers","consultant project certification","career","Consideration","Commercial","Is PML-AI useful in a consulting career?"),
 ("Why it is \"PCI Project Management Leader – AI\"","pml-ai full title","faq","Awareness","Informational","What is the credential's exact official title?"),
],
6: [
 ("Holding all three: what the full suite signals","pci certification suite","comparison","Consideration","Informational","What does holding all three credentials demonstrate?"),
 ("PCL-AI then PFL-AI: why controls people add finance","project controls to project finance","comparison","Consideration","Informational","Why would a controls professional add finance?"),
 ("PCL-AI then PML-AI: controls to leadership","project controls to leadership","comparison","Consideration","Informational","How does a controls specialist move into leadership?"),
 ("PFL-AI then PML-AI: finance to delivery leadership","finance to project leadership","comparison","Consideration","Informational","How does a finance professional lead delivery?"),
 ("Certification map: planning engineer","planning engineer certification","career","Decision","Commercial","Which credential fits a planning engineer?"),
 ("Certification map: cost engineer","cost engineer certification","career","Decision","Commercial","Which credential fits a cost engineer?"),
 ("Certification map: PMO analyst","pmo analyst certification","career","Decision","Commercial","Which credential fits a PMO analyst?"),
 ("Certification map: project accountant","project accountant certification","career","Decision","Commercial","Which credential fits a project accountant?"),
 ("Certification map: risk manager","project risk manager certification","career","Decision","Commercial","Which credential fits a risk manager?"),
 ("Certification map: project director","project director certification","career","Decision","Commercial","Which credential fits a project director?"),
 ("A three-year certification plan that fits a career","certification roadmap","asset","Decision","Informational","How do I sequence credentials over three years?"),
 ("Changing career into project controls: which credential first","career change project controls","career","Decision","Commercial","Where does a career changer start?"),
 ("Already a project manager: which PCI credential adds most","project manager upskilling","comparison","Decision","Commercial","What should a PM add, and why?"),
 ("Already in finance: which PCI credential adds most","finance professional projects","comparison","Decision","Commercial","What should a finance professional add?"),
 ("The full suite: total time and total cost","cost of pci certifications","pricing-route","Decision","Commercial","What does the whole pathway cost in time and money?"),
 ("Certifying a whole team: an employer's pathway","team certification programme","career","Decision","Commercial","How does an employer roll this out?"),
],
7: [
 ("How Certuvo practice mirrors the examination","exam practice platform","applied","Consideration","Informational","How close is practice to the real thing?"),
 ("Inside Certuvo: question banks, mocks and analytics","certuvo features","applied","Consideration","Informational","What tools does Certuvo actually provide?"),
 ("The Certuvo AI coach, explained","ai study coach","applied","Consideration","Informational","What does the AI coach do — and not do?"),
 ("Setting up and signing in to Certuvo","certuvo login","faq","Decision","Navigational","How do I access my Certuvo account?"),
 ("Certuvo access and your PCI membership","certuvo access membership","pricing-route","Decision","Informational","What triggers my Certuvo access?"),
 ("Using practice analytics to find weak domains","exam readiness analytics","applied","Consideration","Informational","How do I turn practice data into a study plan?"),
 ("A mock-examination strategy that works","mock exam strategy","applied","Decision","Informational","How many mocks, and when?"),
 ("Certuvo compared with generic exam-prep sites","exam prep platform comparison","comparison","Consideration","Comparison","How does official preparation differ from generic sites?"),
 ("Do you need Certuvo to pass a PCI examination?","do i need certuvo","pricing-route","Decision","Informational","Is official preparation mandatory?"),
 ("Why the trainer is not the certifier","training provider vs certification body","trust","Consideration","Informational","Why does the separation matter to me?"),
 ("When Certuvo access does not appear","certuvo access problem","faq","Retention","Informational","My access is missing — what now?"),
 ("Practice questions versus real examination questions","practice vs real exam questions","faq","Consideration","Informational","Will I see these questions in the exam?"),
 ("A four-week study schedule built around practice","four week exam study plan","asset","Decision","Informational","What does a realistic final month look like?"),
],
8: [
 ("Guided lab: building a work breakdown structure","wbs guided lab","applied","Consideration","Informational","How do you build a WBS that survives delivery?"),
 ("Guided lab: calculating earned value","evm practice exercise","applied","Consideration","Informational","How do you compute EV, CPI and SPI from raw data?"),
 ("Guided lab: developing a schedule","schedule development exercise","applied","Consideration","Informational","How do you turn scope into a logic-driven schedule?"),
 ("Guided lab: building a cost breakdown structure","cost breakdown structure exercise","applied","Consideration","Informational","How do you structure cost to match the WBS?"),
 ("Guided lab: measuring progress honestly","progress measurement exercise","applied","Consideration","Informational","How do you measure percent complete defensibly?"),
 ("Guided lab: Pareto analysis on project data","pareto analysis project","applied","Consideration","Informational","How do you find the vital few cost or delay drivers?"),
 ("Guided lab: running change control","change control exercise","applied","Consideration","Informational","How does a change move through control?"),
 ("Guided lab: forecasting cash flow","cash flow forecast exercise","applied","Consideration","Informational","How do you build a defensible cash-flow forecast?"),
 ("Skill drills versus guided labs: what each is for","skill drill vs lab","comparison","Consideration","Informational","When should I drill and when should I do a full lab?"),
 ("How deterministic grading works in the Simulation Lab","automated exercise grading","applied","Consideration","Informational","How is my lab work marked, and is it consistent?"),
 ("What the lab coach will and will not do for you","ai tutor limits","faq","Consideration","Informational","Will the coach give me the answer?"),
 ("The capstone: a full project under constraint","project simulation capstone","applied","Consideration","Informational","What does the capstone demand?"),
 ("Team scenarios: controls under disagreement","team project simulation","applied","Consideration","Informational","How do team scenarios differ from solo labs?"),
 ("Difficulty bands: foundation to expert","lab difficulty levels","faq","Consideration","Informational","Which level should I start at?"),
 ("Talking about lab work in an interview","project controls interview evidence","career","Decision","Informational","How do I describe simulated work credibly?"),
 ("Who can access the Simulation Lab","simulation lab access","pricing-route","Decision","Informational","What do I need to use the labs?"),
 ("From lab scenario to Monday morning","applying simulation to real projects","applied","Retention","Informational","How does lab practice transfer to a live project?"),
],
9: [
 ("Creating your PCI World account","pci world sign up","faq","Decision","Navigational","How do I join PCI World?"),
 ("Publishing your PCI World Passport","publish passport","applied","Decision","Informational","How do I turn my record into a shareable page?"),
 ("Passport privacy: what you choose to show","passport privacy settings","trust","Decision","Informational","What exactly becomes visible when I publish?"),
 ("Rotating, expiring and withdrawing a Passport link","withdraw passport link","trust","Retention","Informational","How do I take a shared link back?"),
 ("The one-page Passport PDF","passport pdf","applied","Decision","Informational","What is in the printable Passport?"),
 ("Verifying a Passport: a guide for employers","verify pci world passport","trust","Decision","Informational","How does a recruiter confirm a Passport is real?"),
 ("What a Passport is not","passport limitations","trust","Consideration","Informational","Is a Passport a certification?"),
 ("Community rooms: what happens inside","project controls community","standard","Awareness","Informational","What are the rooms for?"),
 ("Forum norms and moderation at PCI World","community moderation policy","trust","Consideration","Informational","How is discussion kept useful and safe?"),
 ("The careers surface for candidates","project controls jobs","career","Decision","Commercial","How do I find roles through PCI World?"),
 ("The careers surface for employers","post project controls job","career","Decision","Commercial","How does an employer publish and manage roles?"),
 ("Challenges: how practice becomes evidence","project challenges practice","applied","Consideration","Informational","What is a challenge and what does completing one give me?"),
 ("Anonymous practice that joins your record later","anonymous practice account","faq","Consideration","Informational","Do I lose work I did before signing up?"),
 ("PCI World and the Institute: where the line sits","pci world vs institute","trust","Awareness","Informational","Which one certifies, and which one practises?"),
 ("Your PCI Student Number, explained","pci student number","faq","Consideration","Informational","What is the number used for?"),
 ("PCI World for students and recent graduates","student project controls experience","career","Awareness","Commercial","How do I build evidence with no project history?"),
 ("Contributing to PCI World without self-promotion","community contribution guidelines","trust","Retention","Informational","How do I add value without spamming?"),
],
10: [
 ("Signing in to MyPCI","mypci login","faq","Decision","Navigational","How do I access the candidate portal?"),
 ("Your MyPCI dashboard, explained","mypci dashboard","faq","Decision","Navigational","What does each panel show?"),
 ("Applications inside MyPCI","pci application status","faq","Decision","Navigational","How do I track my application?"),
 ("Payments and receipts in MyPCI","pci payment receipt","pricing-route","Decision","Navigational","Where do I find proof of payment?"),
 ("Booking an examination in MyPCI","book pci exam","faq","Decision","Navigational","How do I secure an exam slot?"),
 ("Results in MyPCI: what you see and when","pci exam results","faq","Retention","Informational","How and when are results shown?"),
 ("Downloading and sharing your credential","download pci certificate","faq","Retention","Navigational","How do I share proof of certification?"),
 ("The Passport module inside MyPCI","passport in mypci","faq","Retention","Navigational","How does the portal show my World record?"),
 ("Event passes and how they work","pci event pass","faq","Retention","Navigational","What is an event pass for?"),
 ("Logging CPD in MyPCI","log cpd hours","faq","Retention","Navigational","How do I record continuing development?"),
 ("Renewing your credential in MyPCI","renew pci certification","pricing-route","Retention","Navigational","What does the renewal flow involve?"),
 ("Keeping your record accurate","update certification details","faq","Retention","Navigational","How do I change my name or email?"),
 ("Getting help: the support route that works","pci support contact","faq","Retention","Navigational","Who do I contact, and about what?"),
 ("Moving between PCI World and MyPCI","portal handoff","faq","Retention","Navigational","How do the two portals connect?"),
 ("When you cannot sign in","cannot log in certification portal","faq","Retention","Informational","What do I do about access problems?"),
],
11: [
 ("Where project controls sits in an organisation","project controls function","standard","Awareness","Informational","Who does project controls report to, and why?"),
 ("Scope: the discipline everything else depends on","project scope management","standard","Awareness","Informational","How does scope discipline protect cost and time?"),
 ("Work breakdown structures that hold up","work breakdown structure","applied","Awareness","Informational","What makes a WBS good rather than tidy?"),
 ("Baselines: what they are and when to change them","project baseline","standard","Awareness","Informational","When is re-baselining legitimate?"),
 ("Measuring progress without fooling yourself","progress measurement","applied","Consideration","Informational","Which progress methods resist optimism?"),
 ("Integrating cost and schedule","cost schedule integration","applied","Consideration","Informational","How do the two baselines stay consistent?"),
 ("Project controls maturity, honestly assessed","project controls maturity","asset","Consideration","Informational","How mature is my organisation, really?"),
 ("Controls on a small project versus a mega project","project controls scaling","comparison","Consideration","Informational","What scales down and what never should?"),
 ("Data quality: the silent controls failure","project data quality","applied","Consideration","Informational","How does bad data destroy good analysis?"),
 ("Reporting cadence that people actually read","project reporting cadence","standard","Consideration","Informational","How often should you report, and to whom?"),
 ("Governance for controls professionals","project controls governance","standard","Consideration","Informational","What decisions belong at which level?"),
 ("The project controls toolkit, role by role","project controls tools","standard","Awareness","Informational","What does a controls professional actually use?"),
 ("Working with procurement and supply chain","procurement project controls","standard","Consideration","Informational","Where do controls and procurement meet?"),
 ("Working with engineering","engineering project controls","standard","Consideration","Informational","How do engineering deliverables drive controls data?"),
 ("Controls in operations, shutdowns and turnarounds","turnaround project controls","standard","Consideration","Informational","What changes when the window is days, not years?"),
 ("Controls versus assurance: different jobs","controls vs assurance","comparison","Consideration","Informational","Who checks the checkers?"),
 ("A working glossary of project controls terms","project controls glossary","asset","Awareness","Informational","What do these terms actually mean?"),
 ("Breaking into project controls with no experience","how to start project controls career","career","Awareness","Commercial","How do I get the first role?"),
],
12: [
 ("Critical path method, from first principles","critical path method","applied","Awareness","Informational","How does CPM actually compute the path?"),
 ("Building a schedule people can execute","how to build project schedule","applied","Consideration","Informational","What makes a schedule usable rather than decorative?"),
 ("Float, and the four ways it misleads you","total float free float","applied","Consideration","Informational","What do the different floats really tell you?"),
 ("Schedule quality checks worth running","schedule quality check","asset","Consideration","Informational","How do I test a schedule before trusting it?"),
 ("Resource loading and levelling","resource loaded schedule","applied","Consideration","Informational","How do resources change the answer?"),
 ("Schedule risk analysis in practice","schedule risk analysis","applied","Consideration","Informational","How do you produce a defensible P80 date?"),
 ("Baselines and re-baselining without losing history","schedule baseline","standard","Consideration","Informational","How do you re-baseline honestly?"),
 ("Progress updating: the weekly discipline","schedule progress update","applied","Consideration","Informational","What does a clean update cycle look like?"),
 ("Compression: crashing, fast-tracking and their costs","schedule compression","applied","Consideration","Informational","What do you actually pay for a shorter schedule?"),
 ("Look-ahead planning that changes behaviour","look ahead schedule","applied","Consideration","Informational","How do short-interval plans drive the field?"),
 ("Milestones that mean something","project milestones","standard","Consideration","Informational","How do you choose milestones worth tracking?"),
 ("Delay analysis methods, compared","delay analysis methods","comparison","Consideration","Comparison","Which method suits which dispute?"),
 ("Concurrent delay, explained for practitioners","concurrent delay","standard","Consideration","Informational","What happens when both parties cause delay?"),
 ("Time impact analysis, step by step","time impact analysis","applied","Consideration","Informational","How is a TIA constructed?"),
 ("As-planned versus as-built","as planned vs as built","comparison","Consideration","Comparison","When is this method appropriate?"),
 ("Extension-of-time claims: the evidence that wins","extension of time claim","applied","Consideration","Informational","What records decide an EOT?"),
 ("Writing a schedule narrative anyone can follow","schedule narrative","asset","Consideration","Informational","How do you explain a schedule in prose?"),
 ("Ten scheduling mistakes that survive audits","scheduling mistakes","faq","Consideration","Informational","What errors keep recurring?"),
 ("Primavera P6 and Microsoft Project for scheduling","p6 vs ms project scheduling","comparison","Decision","Comparison","Which tool suits which project?"),
 ("Where AI helps a scheduler, and where it must not","ai scheduling","applied","Consideration","Informational","What can be automated in scheduling?"),
],
13: [
 ("Cost breakdown structures that reconcile","cost breakdown structure","applied","Awareness","Informational","How do you build a CBS that ties to the WBS?"),
 ("Estimating methods, compared","estimating methods","comparison","Consideration","Comparison","Which estimating method fits which stage?"),
 ("Estimate classes and what they promise","estimate classification","standard","Consideration","Informational","What accuracy can each class claim?"),
 ("Contingency: sizing it and drawing it down","project contingency","applied","Consideration","Informational","How much contingency, and who releases it?"),
 ("Cost baselines and change","cost baseline","standard","Consideration","Informational","What moves the cost baseline legitimately?"),
 ("Commitments, accruals and actuals","commitment vs actual cost","applied","Consideration","Informational","Why do the three numbers disagree?"),
 ("Cost coding that survives contact with accounting","project cost coding","applied","Consideration","Informational","How do you align project and finance codes?"),
 ("Variance analysis that explains, not just reports","cost variance analysis","applied","Consideration","Informational","How do you get from variance to cause?"),
 ("Forecasting at completion: the EAC formulas","estimate at completion","applied","Consideration","Informational","Which EAC formula should you use, and when?"),
 ("Trend analysis before the variance appears","cost trend analysis","applied","Consideration","Informational","How do you see it coming?"),
 ("Cost reports that drive decisions","project cost report","asset","Consideration","Informational","What belongs in a monthly cost report?"),
 ("Benchmarking project costs responsibly","cost benchmarking","standard","Consideration","Informational","How do you compare without misleading?"),
 ("Escalation and inflation in long projects","cost escalation","applied","Consideration","Informational","How do you handle rising prices in a baseline?"),
 ("Currency and exchange exposure on projects","project currency risk","applied","Consideration","Informational","What happens when costs span currencies?"),
 ("Cost control in construction delivery","construction cost control","career","Consideration","Informational","What does cost control look like on site?"),
 ("Cost control in energy and process projects","energy project cost control","career","Consideration","Informational","What is different about process plants?"),
 ("AI-assisted estimating: promise and guardrails","ai estimating","applied","Consideration","Informational","Where can AI improve an estimate?"),
 ("Cost control mistakes that repeat everywhere","cost control mistakes","faq","Consideration","Informational","What goes wrong most often?"),
 ("Cash flow versus the cost curve","project cash flow vs cost","comparison","Consideration","Informational","Why are spend and cash not the same?"),
 ("A cost engineering career, mapped","cost engineering career","career","Decision","Commercial","How does a cost career progress?"),
],
}
