#!/usr/bin/env python3
"""Audit the artwork: inventory, alt text, and every number a chart prints.

`verify_formulas.py` proves the arithmetic in the TEXT. Nothing proved the arithmetic in the
PICTURES. A figure is generated by its own Python module, so its annotations are literals typed a
second time — the classic place for a value to drift away from the prose it illustrates without any
suite noticing, because no suite was looking.

Five things are checked, and the third is the one with teeth:

  1. Inventory. Every figure specified in a manuscript has rendered artwork, every rendered file is
     specified, and every generator writes what its book expects. Orphans in either direction are
     defects: a spec with no artwork prints a caption over nothing, and artwork with no spec is a
     file nobody reviews.

  2. Alt text. Every specification carries an `Alt text:` sentence, and it has to say what the
     reader would otherwise see rather than restate the title.

  3. Traceability of annotated values. Every number a chart PRINTS must be traceable — to the
     figure's own specification in the manuscript, or to a value the formula gate verified. A
     number that appears only inside the drawing is a number nobody has checked.

  4. Axis sanity. Not "are the ticks evenly spaced" — log scales are not, and that is fine — but
     whether screen position is a consistent function of value. A chart distorts when it is not.

  5. Labels that fit. A light label wider than the shape holding it spills onto the page and
     becomes invisible. The text is present, correct and verified; the reader simply cannot see it.

Run:  python3 audit_figures.py             (writes nothing; exits 1 on any defect)
      python3 audit_figures.py --verbose   (also lists what each figure traced to)
      python3 audit_figures.py --refresh   (re-runs the formula gate to rebuild the verified set)
      python3 audit_figures.py --selftest  (plants each defect class and proves it is caught)
"""
from __future__ import annotations

import html
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent
BOOKS = ROOT.parent
CACHE = ROOT / "__pycache__" / "verified_values.txt"

BOOK_DIRS = {"pml-ai": BOOKS / "pml-ai", "pfl-ai": BOOKS / "pfl-ai"}

# A figure specification opens a blockquote: "> **Fig 4.1.1 — Kestrel's NPV profile.** ..."
SPEC_RE = re.compile(r"\*\*Fig\s+([0-9]+(?:\.[0-9]+)+)\s*[—-]\s*(.+?)\.?\*\*", re.S)
TEXT_RE = re.compile(r"<text[^>]*>(.*?)</text>", re.S)
TEXT_POS_RE = re.compile(r"<text\b([^>]*)>(.*?)</text>", re.S)
ATTR_RE = re.compile(r'\b(x|y)\s*=\s*"([-\d.]+)"')
# A number as a reader sees it: optional sign, digit groups, optional decimals.
NUM_RE = re.compile(r"[-+−]?\d[\d,]*(?:\.\d+)?")


def numbers(s: str) -> list[str]:
    """Every number in a string, normalised to a bare digit form for comparison."""
    out = []
    for m in NUM_RE.finditer(s):
        t = m.group(0).lstrip("+-−").replace(",", "")
        if t and t.strip("0.") != "":  # a bare 0 traces to nothing useful
            out.append(t.rstrip("0").rstrip(".") if "." in t else t)
    return out


def verified_values() -> set[str]:
    """Every value the formula gate printed, in the same normalised form.

    Cached, because the gate takes a while and this audit is meant to be cheap to re-run. The
    cache is keyed on nothing — delete __pycache__ or pass --refresh when the corpus changes.
    """
    if CACHE.exists() and "--refresh" not in sys.argv:
        return set(CACHE.read_text().split())
    proc = subprocess.run([sys.executable, str(ROOT / "verify_formulas.py")],
                          capture_output=True, text=True)
    if proc.returncode != 0:
        sys.exit("the formula gate does not pass; fix that before auditing the artwork")
    vals: set[str] = set()
    for line in proc.stdout.splitlines():
        if not line.startswith("PASS"):
            continue
        for part in line.split(": ", 1)[-1].split("  "):
            for n in numbers(part):
                vals |= rounded_forms(n)
    CACHE.parent.mkdir(exist_ok=True)
    CACHE.write_text("\n".join(sorted(vals)))
    return vals


def axis_series(svg: str):
    """Numbers belonging to a tick series, and any tick series that is unevenly spaced.

    Ticks are found by GEOMETRY, not by unit. A first version grouped every number sharing a
    trailing unit ("%", "m") and called the group an axis, which swept annotation values into the
    same bucket as the ruler and then reported the mixture as an uneven axis — 30-odd findings that
    were all artefacts of the grouping. Real ticks line up: y-axis labels share an x coordinate and
    x-axis labels share a y coordinate. Grouping on the shared coordinate and reading the spacing
    along the other one is what actually distinguishes a ruler from a measurement.
    """
    # Labels drawn inside a shape are data, never a ruler. A funnel chart's stage counts sit
    # centred in their bars and formed the leftmost numeric column, so the audit read 40/12/5/2 as
    # a distorted y-axis when the figure has no axis at all.
    boxes = []
    for attrs in RECT_RE.findall(svg):
        a = {k: float(v) for k, v in RECT_ATTR_RE.findall(attrs)}
        if {"x", "y", "width", "height"} <= a.keys():
            boxes.append(a)

    def inside_shape(cx: float, cy: float) -> bool:
        return any(b["x"] <= cx <= b["x"] + b["width"] and b["y"] <= cy <= b["y"] + b["height"]
                   for b in boxes)

    placed: list[tuple[float, float, str, float]] = []   # x, y, raw, value
    for attrs, body in TEXT_POS_RE.findall(svg):
        pos = dict(ATTR_RE.findall(attrs))
        if "x" not in pos or "y" not in pos:
            continue
        if "white" in attrs or "#fff" in attrs.lower():
            continue
        if inside_shape(float(pos["x"]), float(pos["y"])):
            continue
        plain = html.unescape(re.sub(r"<[^>]+>", "", body)).replace("−", "-").strip()
        m = re.fullmatch(r"([-+]?\d[\d,]*(?:\.\d+)?)\s*([%a-zA-Z]{0,3})", plain)
        if not m:
            continue
        try:
            placed.append((float(pos["x"]), float(pos["y"]), plain,
                           float(m.group(1).replace(",", ""))))
        except ValueError:
            pass

    exempt: set[str] = set()
    uneven: list[str] = []
    if not placed:
        return exempt, uneven

    # A ruler sits on the frame: the y-axis tick column is the leftmost stack of numbers, the
    # x-axis tick row the lowest. Any other monotonic column is a stack of data labels, and judging
    # THOSE for even spacing is meaningless — it was reporting annotation values as broken axes.
    for axis, key, along in (("y-axis", 0, 1), ("x-axis", 1, 0)):
        edge = min(p[key] for p in placed) if axis == "y-axis" else max(p[key] for p in placed)
        items = sorted((p[along], p[3], p[2]) for p in placed if abs(p[key] - edge) <= 2)
        if len(items) < 3:
            continue
        vals = [v for _, v, _ in items]
        if not (all(a < b for a, b in zip(vals, vals[1:]))
                or all(a > b for a, b in zip(vals, vals[1:]))):
            continue
        # The honest question is not "are the labels evenly spaced" — log scales are not, and
        # neither are labels parked at data positions, and both are legitimate. It is whether
        # SCREEN POSITION is a consistent function of VALUE. A chart distorts when it is not:
        # equal steps drawn unequally, or unequal steps drawn equally. So fit position against
        # value and against log(value), and accept the axis if either is a straight line.
        # A chart may print a SECOND row of labels at the same tick positions — Fig 6.4.2 puts
        # duration on the axis and cumulative crash cost beneath each point, and says so in the
        # axis title. The lower row is data, not a ruler, so judge every row sharing these
        # positions and accept the axis if any one of them is a straight function of position.
        pos = [p for p, _, _ in items]
        rows = [vals]
        for other in {round(p[key], 0) for p in placed}:
            cand = sorted((p[along], p[3]) for p in placed if abs(p[key] - other) <= 2)
            if len(cand) == len(pos) and all(abs(a - b) < 2 for (a, _), b in zip(cand, pos)):
                rows.append([v for _, v in cand])
        fits = []
        for row in rows:
            fits.append(_r2(pos, row))
            if all(v > 0 for v in row):
                import math as _m
                fits.append(_r2(pos, [_m.log(v) for v in row]))
        if max(fits) >= 0.999 or len(vals) < 4:
            for _, _, raw in items:
                exempt.update(numbers(raw))
        else:
            uneven.append(f"{axis}: {vals} (best fit R2={max(fits):.4f})")
    return exempt, uneven


RECT_RE = re.compile(r"<rect\b([^>]*)>")
RECT_ATTR_RE = re.compile(r'\b(x|y|width|height)\s*=\s*"([-\d.]+)"')
# Average glyph advance as a fraction of font-size, for the sans stack these figures use. Rough on
# purpose: the question is "does this text obviously not fit", not "where does it end".
GLYPH_W = 0.52


def label_overflows(svg: str) -> list[str]:
    """Light-coloured labels wider than the shape they sit in.

    Found by looking at a funnel chart, not by any check: "at 2,400,000 each" was drawn in white,
    centred in the narrowest bar, and the half that overflowed the bar landed white-on-white and
    disappeared. Nothing in the corpus could catch that, because the text is present, correct and
    verified — it is simply invisible. A label whose estimated width exceeds its container's is the
    machine-checkable form of the defect.
    """
    rects = []
    for attrs in RECT_RE.findall(svg):
        a = {k: float(v) for k, v in RECT_ATTR_RE.findall(attrs)}
        if {"x", "y", "width", "height"} <= a.keys():
            rects.append(a)
    out = []
    for attrs, body in TEXT_POS_RE.findall(svg):
        if "white" not in attrs and "#fff" not in attrs.lower():
            continue
        pos = dict(ATTR_RE.findall(attrs))
        size = re.search(r'font-size="([\d.]+)"', attrs)
        if "x" not in pos or "y" not in pos or not size:
            continue
        cx, cy, fs = float(pos["x"]), float(pos["y"]), float(size.group(1))
        label = html.unescape(re.sub(r"<[^>]+>", "", body)).strip()
        est = len(label) * fs * GLYPH_W
        anchored_middle = 'text-anchor="middle"' in attrs
        for r in rects:
            if not (r["x"] - 1 <= cx <= r["x"] + r["width"] + 1
                    and r["y"] - 2 <= cy <= r["y"] + r["height"] + 6):
                continue
            room = r["width"] - 6
            if anchored_middle and est > room:
                out.append(f"{label!r} (~{est:.0f}px) in a {r['width']:.0f}px shape")
            break
    return out


def _r2(xs: list[float], ys: list[float]) -> float:
    """How well a straight line explains y from x. 1.0 is exact."""
    n = len(xs)
    mx, my = sum(xs) / n, sum(ys) / n
    sxy = sum((a - mx) * (b - my) for a, b in zip(xs, ys))
    sxx = sum((a - mx) ** 2 for a in xs)
    syy = sum((b - my) ** 2 for b in ys)
    if sxx == 0 or syy == 0:
        return 0.0
    return (sxy * sxy) / (sxx * syy)


def rounded_forms(v: str) -> set[str]:
    """Every way a verified value could honestly be printed: itself, and rounded to 0-6 places.

    A chart labels "12.1921 %" for a rate the gate verified as 12.192120. Comparing the strings
    finds no match and the label looks unverified, which is the opposite of the truth. Rounding the
    verified value the way a typesetter would is what makes the comparison mean anything.
    """
    out = {v}
    try:
        f = float(v)
    except ValueError:
        return out
    for dp in range(0, 7):
        r = f"{f:.{dp}f}"
        out.add(r.rstrip("0").rstrip(".") if "." in r else r)
    # Charts also print millions as "16.18" for 16,179,360 and thousands as "742" for 742,000.
    for scale in (1e3, 1e6, 1e9):
        if abs(f) >= scale:
            # Four decimals, not three: charts abbreviate 2,916,700 as "2.9167m", and stopping at
            # three made a correctly-abbreviated verified value look like an unchecked one.
            for dp in range(0, 5):
                r = f"{f / scale:.{dp}f}"
                out.add(r.rstrip("0").rstrip(".") if "." in r else r)
    return out


def main() -> int:
    verbose = "--verbose" in sys.argv
    verified = verified_values()
    defects: list[str] = []
    audited = specs_total = 0

    for book, bdir in BOOK_DIRS.items():
        figdir = bdir / "build" / "figures"
        rendered = {p.stem for p in figdir.glob("fig_*.svg")}
        specs: dict[str, tuple[str, str, str]] = {}   # id -> (title, spec text, source file)

        for md in sorted((bdir / "manuscript").glob("*.md")):
            body = md.read_text()
            block: list[str] = []
            blocks: list[str] = []
            for ln in body.splitlines() + [""]:
                if ln.startswith(">"):
                    block.append(ln.lstrip("> ").rstrip())
                elif block:
                    blocks.append(" ".join(block))
                    block = []
            for text in blocks:
                m = SPEC_RE.match(text)
                if not m:
                    continue
                fid, title = m.group(1), m.group(2)
                if fid in specs:
                    defects.append(f"{book}: Fig {fid} specified twice "
                                   f"({specs[fid][2]} and {md.name})")
                specs[fid] = (title, text, md.name, body)
        specs_total += len(specs)

        # ---- 1. inventory ------------------------------------------------------------
        for fid, (_, _, src, _body) in sorted(specs.items()):
            if f"fig_{fid.replace('.', '_')}" not in rendered:
                defects.append(f"{book}: Fig {fid} is specified in {src} but no artwork exists")
        for stem in sorted(rendered):
            fid = stem[4:].replace("_", ".")
            if fid not in specs:
                defects.append(f"{book}: {stem}.svg is rendered but no manuscript specifies it")

        for fid, (title, spec, src, domain_md) in sorted(
                specs.items(), key=lambda kv: [int(x) for x in kv[0].split(".")]):
            svgf = figdir / f"fig_{fid.replace('.', '_')}.svg"
            if not svgf.exists():
                continue
            audited += 1
            svg = svgf.read_text()
            # Inner <tspan> markup must go before the label is read, attributes and all: a fill of
            # "#64748B" otherwise parses as the number 64748 and gets reported as an untraceable
            # value in every figure that colours part of a label.
            texts = [re.sub(r"<[^>]+>", "", t) for t in TEXT_RE.findall(svg)]

            # ---- 2. alt text ---------------------------------------------------------
            alt = re.search(r"Alt text:\s*(.+?)(?:\s*$)", spec, re.S)
            if not alt:
                defects.append(f"{book}: Fig {fid} has no 'Alt text:' sentence")
            else:
                sentence = alt.group(1).strip()
                if len(sentence) < 40:
                    defects.append(f"{book}: Fig {fid} alt text is too short to replace the "
                                   f"picture: {sentence!r}")
                elif sentence.rstrip(".").lower() == title.rstrip(".").lower():
                    defects.append(f"{book}: Fig {fid} alt text merely repeats the title")

            # ---- 5. labels that do not fit their shape --------------------------------
            for o in label_overflows(svg):
                defects.append(f"{book}: Fig {fid} has a light label wider than its shape, so the "
                               f"overflow is invisible against the page — {o}")

            # ---- 4. axis sanity ------------------------------------------------------
            exempt, uneven = axis_series(svg)
            for u in uneven:
                defects.append(f"{book}: Fig {fid} has an unevenly spaced tick series — {u}")

            # ---- 3. traceability -----------------------------------------------------
            spec_nums: set[str] = set()
            for n in numbers(spec) + numbers(domain_md):
                spec_nums |= rounded_forms(n)
            untraced: list[str] = []
            for t in texts:
                plain = html.unescape(t)
                for n in numbers(plain):
                    if n in exempt or n in spec_nums or n in verified:
                        continue
                    # A year, a count of a handful, or a percentage point written inline is not a
                    # computed result; requiring a golden answer for "3" would drown the signal.
                    if len(n.replace(".", "")) <= 2:
                        continue
                    untraced.append(f"{n} (in {plain.strip()!r})")
            if untraced:
                defects.append(f"{book}: Fig {fid} prints {len(untraced)} value(s) that trace to "
                               f"neither its specification nor a verified result: "
                               + "; ".join(untraced[:4]))
            elif verbose:
                print(f"  ok  {book} Fig {fid} — {len(texts)} labels, {len(exempt)} tick values")

    print(f"\nfigures specified: {specs_total}   audited: {audited}")
    if defects:
        print(f"\nopen artwork defects: {len(defects)}")
        for d in defects:
            print(f"  - {d}")
        return 1
    print("open artwork defects: 0")
    return 0


def selftest() -> int:
    """Plant one defect of each kind and confirm the audit reports it.

    A clean run means nothing on its own — an audit that examines the wrong thing also reports
    zero. Three of the four checks in this file were, at some point during their construction,
    reporting artefacts of their own parsing rather than facts about the artwork, and the only
    thing that distinguished the working versions from the broken ones was planting a defect and
    watching them catch it. So that is wired in rather than performed once and described.
    """
    # Each case mutates the RAW manuscript or the RAW svg. An earlier version tried to replace the
    # joined blockquote text inside a file that stores it as wrapped "> " lines, so the alt-text
    # plant never landed — the self-test had the very defect it exists to detect.
    def drop_alt(md_text: str) -> str:
        return md_text.replace("Alt text:", "Alt txt:", 1)

    def add_untraced(svg: str) -> str:
        return svg.replace("</svg>", '<text x="30" y="30" font-size="10">total 8675309</text></svg>')

    def add_overflow(svg: str) -> str:
        return svg.replace("</svg>",
                           '<rect x="10" y="200" width="40" height="20"/>'
                           '<text x="30" y="214" font-size="10" fill="white" '
                           'text-anchor="middle">a label far too long for this shape</text></svg>')

    def distort_axis(svg: str) -> str:
        # Five labels along one row whose values do not track their positions: 1,2,3 crammed into
        # the same span that then jumps to 400,401. No linear or log fit survives that.
        return svg.replace("</svg>", "".join(
            f'<text x="{x}" y="900" font-size="10">{v}</text>'
            for x, v in zip((40, 90, 140, 190, 240), (1, 2, 3, 400, 401))) + "</svg>")

    def hide_artwork(svg: str) -> str:
        return svg   # handled by moving the file instead

    cases = [
        ("alt text removed", None, drop_alt, "no 'Alt text:' sentence"),
        ("an annotation nobody verified", add_untraced, None, "trace to neither"),
        ("a white label wider than its bar", add_overflow, None, "wider than its shape"),
        ("an axis whose labels do not track their positions", distort_axis, None, "unevenly spaced"),
    ]

    bdir = BOOK_DIRS["pfl-ai"]
    svgf = bdir / "build" / "figures" / "fig_4_1_1.svg"
    md = bdir / "manuscript" / "domain-04-investment-appraisal.md"
    svg0, md0 = svgf.read_text(), md.read_text()

    failures = 0
    try:
        for name, mut_svg, mut_md, expect in cases:
            svgf.write_text(mut_svg(svg0) if mut_svg else svg0)
            md.write_text(mut_md(md0) if mut_md else md0)
            out = subprocess.run([sys.executable, __file__], capture_output=True, text=True).stdout
            caught = expect in out
            print(f"{'PASS' if caught else 'FAIL'}  planting {name} is caught")
            failures += 0 if caught else 1

        # Missing artwork, planted by moving the file out of the way.
        svgf.write_text(svg0)
        md.write_text(md0)
        moved = svgf.with_suffix(".svg.selftest")
        svgf.rename(moved)
        out = subprocess.run([sys.executable, __file__], capture_output=True, text=True).stdout
        caught = "no artwork exists" in out
        print(f"{'PASS' if caught else 'FAIL'}  planting missing artwork is caught")
        failures += 0 if caught else 1
        moved.rename(svgf)
    finally:
        svgf.write_text(svg0)
        md.write_text(md0)

    out = subprocess.run([sys.executable, __file__], capture_output=True, text=True).stdout
    restored = "open artwork defects: 0" in out
    print(f"{'PASS' if restored else 'FAIL'}  removing every planted defect restores a clean run")
    failures += 0 if restored else 1
    print("\nself-test failures:", failures)
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(selftest() if "--selftest" in sys.argv else main())
