#!/usr/bin/env python3
"""Build each volume's standards-and-frameworks register, derived from the manuscripts.

Like the glossary, the appendices and the question bank, this is **derived** rather than maintained.
That matters more here than anywhere else: a register of standards is a disclosure document, and a
disclosure document that is edited by hand will eventually disagree with the text it discloses. This
one is generated by scanning every manuscript for references and cross-checking them against a
curated table of what each document addresses, so:

  * a standard referenced in a chapter but missing from the curated table **fails the check** — a new
    reference cannot enter the corpus without being disclosed here;
  * a standard in the table that no chapter references is reported as **unreferenced**, so the register
    cannot claim engagement the volumes do not have;
  * the "where" column is the live set of locations, so it cannot go stale.

**On editions, deliberately.** No entry states an edition year or revision date. That is not an
oversight and it is not laziness — it is the one claim this programme is not in a position to make.
Standards are revised, withdrawn and superseded on their own schedules, and a citation to a
superseded edition is worse than no citation at all, because it looks authoritative while being
wrong. Establishing the current edition of each document requires the publisher's catalogue at the
date of publication, which is a reviewer's task with access this build does not have. What the
register does assert is checkable from the text itself: which documents the volumes engage with,
what each is described as addressing, where each is discussed, and that none is reproduced.

Usage:  python3 make_standards.py            # write both registers
        python3 make_standards.py --check    # audit only; exit 1 on an undisclosed reference
"""
import pathlib
import re
import sys
from collections import defaultdict

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent

BOOKS = {"pml-ai": "PML-AI Body of Knowledge", "pfl-ai": "PFL-AI Body of Knowledge"}

# What each referenced document addresses, in this programme's own words, grouped by family.
# These are characterisations at the level of a document's stated scope — the kind of statement a
# catalogue entry makes — and not summaries of any document's content, which the charter forbids.
FAMILIES = [
    ("Project, programme and portfolio management", [
        ("ISO 21500", "context and concepts for project, programme and portfolio management"),
        ("ISO 21502", "guidance on project management"),
        ("ISO 21503", "guidance on programme management"),
        ("ISO 21504", "guidance on portfolio management"),
        ("ISO 21505", "guidance on governance of projects, programmes and portfolios"),
        ("ISO 10006", "quality management in projects"),
    ]),
    ("Risk", [
        ("ISO 31000", "risk management — principles and guidelines"),
    ]),
    # Sustainability reporting is the one area where a voluntary framework and a mandatory
    # disclosure regime are most often conflated, so the entry says which this is.
    ("Environmental and sustainability quantification", [
        ("ISO 14064", "the quantification and reporting of greenhouse-gas emissions and removals — "
                      "voluntary guidance, and not itself a disclosure obligation"),
    ]),
    # An assurance architecture owned by a named professional body, revised by its owner. It is
    # neither a standard nor a requirement, and the volumes use it as a lens rather than a rule.
    ("Assurance and internal audit", [
        ("Institute of Internal Auditors", "an assurance architecture, commonly called the three "
                                           "lines, published by a professional body and revised by "
                                           "it into a model of roles rather than sequential lines of "
                                           "defence — voluntary guidance, neither a standard nor a "
                                           "requirement, and described in this volume in its own "
                                           "words"),
    ]),
    ("Quality and data quality", [
        ("ISO 9000", "quality management systems — fundamentals and vocabulary"),
        ("ISO 9001", "quality management systems — the certifiable requirements standard"),
        ("ISO 8000", "data quality"),
        ("ISO/IEC 25012", "a data-quality model for software and systems"),
    ]),
    ("Information management in the built environment", [
        ("ISO 19650", "organisation and digitisation of information about buildings and civil "
                      "engineering works, including building information modelling"),
    ]),
    ("Artificial intelligence, information security and privacy", [
        ("ISO/IEC 42001", "artificial-intelligence management systems"),
        ("ISO/IEC 23894", "guidance on risk management for artificial intelligence"),
        ("ISO/IEC 38507", "governance implications of an organisation's use of artificial "
                          "intelligence"),
        ("ISO/IEC 27001", "information-security management systems"),
        ("ISO/IEC 27701", "privacy information management. Its relationship to an ISO/IEC 27001 "
                          "information-security management system, and whether it can be certified in "
                          "its own right, differ between editions; establish which edition any claim "
                          "of conformity refers to before relying on it"),
        ("NIST", "the United States National Institute of Standards and Technology, referenced for "
                 "its AI Risk Management Framework — a voluntary, function-based framework, not a "
                 "standard and not a regulation"),
    ]),
    ("Financial reporting", [
        ("IFRS 15", "revenue from contracts with customers"),
        ("IFRS 16", "leases"),
        ("IAS 37", "provisions, contingent liabilities and contingent assets"),
    ]),
    ("Project finance, environmental and social frameworks", [
        ("Equator Principles", "a voluntary risk-management framework adopted by participating "
                               "financial institutions for environmental and social risk in project "
                               "finance"),
        ("IFC Performance Standards", "the International Finance Corporation's environmental and "
                                      "social performance standards, widely adopted as a reference "
                                      "benchmark in project finance"),
        ("OECD", "the Organisation for Economic Co-operation and Development, referenced for its "
                 "arrangement on officially supported export credits, for its convention on "
                 "combating bribery of foreign public officials, and for its Guidelines for "
                 "Multinational Enterprises and the associated due-diligence guidance — "
                 "recommendations addressed to adhering governments and, through them, to "
                 "enterprises, and not obligations of themselves"),
    ]),
    # Financial crime is the one duty in the ethics chapter whose breach is criminal, and the three
    # instruments below are the three most often misdescribed: a treaty that is not law anywhere, an
    # intergovernmental standard that is not legislation, and a voluntary standard whose certification
    # is not a defence. Each is characterised by WHAT IT IS, because that is the whole disclosure.
    ("Financial crime, anti-bribery and sanctions", [
        ("OECD Anti-Bribery Convention", "the Convention on Combating Bribery of Foreign Public "
                                         "Officials in International Business Transactions — a "
                                         "treaty, addressed to the states party to it rather than "
                                         "to a project company, and not to be read as applying "
                                         "directly to a transaction"),
        ("FATF", "the Financial Action Task Force, referenced for its Recommendations on combating "
                 "money laundering and the financing of terrorism and proliferation — an "
                 "intergovernmental standard addressed to countries, reaching a project in practice "
                 "through the supervised institutions that finance and advise it"),
        ("ISO 37001", "anti-bribery management systems — a voluntary management-system standard; "
                      "certification against it is a third party's opinion about a management "
                      "system at a point in time and should never be offered or accepted as a "
                      "defence"),
    ]),
    # Standard-form contracts are PRIVATELY PUBLISHED MODEL FORMS. They have no standing of their
    # own: they matter to a project because the parties wrote one into their agreement, and what it
    # then means between them is a question of that contract and the applicable law. The register
    # must not let a familiar acronym read as an authority.
    ("Standard-form contract families", [
        ("NEC", "a family of privately published standard-form construction and engineering "
                "contracts, named for identification only; it has no standing of its own and takes "
                "effect only where parties adopt it in their agreement"),
        ("FIDIC", "a family of privately published standard-form engineering and construction "
                  "contracts, named for identification only; it has no standing of its own and takes "
                  "effect only where parties adopt it in their agreement"),
        ("JCT", "a family of privately published standard-form building contracts, named for "
                "identification only; it has no standing of its own and takes effect only where "
                "parties adopt it in their agreement"),
        ("ISO 44001", "the management of collaborative business relationships — voluntary guidance"),
    ]),
    # Non-binding international instruments supply the METHOD of human-rights due diligence. They
    # are addressed to states and, through them, to enterprises as expectations of conduct; they are
    # a different kind of thing from national due-diligence legislation and the register says so.
    ("Responsible and sustainable procurement", [
        ("UN Guiding Principles on Business and Human Rights", "business responsibility for human "
                                                               "rights — a non-binding international "
                                                               "instrument that supplies a method "
                                                               "and imposes no obligation of itself"),
        ("ISO 20400", "sustainable procurement — voluntary guidance, and not a certifiable "
                      "requirements standard"),
    ]),
    ("Records and service management", [
        ("ISO 15489", "records management — what a record is, and the controls that keep it "
                      "authentic, reliable and usable over time; voluntary guidance, and it states "
                      "no retention period applicable to any organisation"),
        ("ISO/IEC 20000", "service management, the discipline a receiving organisation runs when it "
                          "accepts a service into support; voluntary guidance"),
    ]),
    ("Cost engineering", [
        ("AACE", "AACE International, referenced for the existence and purpose of the cost-estimate "
                 "classification progression — in its Total Cost Management framework and in its "
                 "Recommended Practices on cost-estimate classification; voluntary professional "
                 "guidance, named for identification only and never reproduced"),
    ]),
    ("Industrial control system security", [
        ("IEC 62443", "security for industrial automation and control systems"),
    ]),
    # Laws are NOT standards and the register must not blur the two. A standard is voluntary unless a
    # contract or regulator adopts it; a regulation binds within its jurisdiction and nowhere else,
    # which is exactly the distinction the charter requires the volumes to keep.
    ("Regulation — named as reference points, not as applicable law", [
        ("AI Act", "the European Union's risk-tiered regulatory approach to artificial intelligence, "
                   "named as an example of that regulatory shape and binding only within its own "
                   "jurisdiction"),
        ("General Data Protection Regulation", "the European Union's data-protection regime, named as "
                                               "an example of a rights-based data-protection approach "
                                               "and binding only within its own jurisdiction"),
    ]),
]

# Reference patterns. Longest-first matching matters: ISO/IEC 27701 must not be found as ISO/IEC 277.
# Patterns are deliberately wider than the obvious ones. A first version matched only ISO- and
# ISO/IEC-prefixed numbers and so missed IEC 62443 (no ISO prefix), the EU AI Act and the General
# Data Protection Regulation — the same failure as asserting a vocabulary instead of reading one, and
# a register that silently omits a regulation is worse than no register.
PATTERNS = [
    (r"\bISO(?:/IEC)?\s?\d{4,5}(?:[-‑]\d+)?\b", lambda m: re.sub(r"\s+", " ", m.group(0))),
    (r"(?<![/\w])IEC\s?\d{4,5}(?:[-‑]\d+)?\b", lambda m: re.sub(r"\s+", " ", m.group(0))),
    (r"\b(?:European Union's |EU )?AI Act\b", lambda m: "AI Act"),
    (r"\bGeneral Data Protection Regulation\b", lambda m: m.group(0)),
    (r"\bIFRS\s?\d{1,2}\b", lambda m: re.sub(r"\s+", " ", m.group(0))),
    (r"\bIAS\s?\d{1,2}\b", lambda m: re.sub(r"\s+", " ", m.group(0))),
    # Wrapped across lines in the manuscripts, so whitespace runs — never a literal space.
    (r"\bCombating\s+Bribery\s+of\s+Foreign\s+Public\s+Officials\b|\bOECD\s+Anti-Bribery\s+Convention\b",
     lambda m: "OECD Anti-Bribery Convention"),
    (r"\bFATF\b", lambda m: "FATF"),
    (r"\bEquator Principles\b", lambda m: m.group(0)),
    (r"\bIFC Performance Standards\b", lambda m: m.group(0)),
    (r"\bNIST\b", lambda m: m.group(0)),
    (r"\bOECD\b", lambda m: m.group(0)),
    (r"\bAACE\b", lambda m: m.group(0)),
    # Named bodies and instruments with no catalogue number. Wrapped across lines in the
    # manuscripts, so whitespace runs — never a literal space.
    (r"\bInstitute\s+of\s+Internal\s+Auditors\b", lambda m: "Institute of Internal Auditors"),
    (r"\bUN\s+Guiding\s+Principles\s+on\s+Business\s+and\s+Human\s+Rights\b",
     lambda m: "UN Guiding Principles on Business and Human Rights"),
    (r"(?<![\w-])NEC(?![\w-])", lambda m: "NEC"),
    (r"(?<![\w-])FIDIC(?![\w-])", lambda m: "FIDIC"),
    (r"(?<![\w-])JCT(?![\w-])", lambda m: "JCT"),
]


def scan(book: str) -> dict:
    """reference -> sorted list of 'D<n>' locations where it is discussed."""
    found = defaultdict(set)
    for f in sorted((ROOT / book / "manuscript").glob("domain-*.md")):
        dn = int(re.match(r"domain-(\d+)-", f.name).group(1))
        text = f.read_text(encoding="utf-8")
        for pat, norm in PATTERNS:
            for m in re.finditer(pat, text):
                found[norm(m)].add(dn)
    return {k: sorted(v) for k, v in found.items()}


def known() -> dict:
    return {ref: desc for _, entries in FAMILIES for ref, desc in entries}


def build(book: str, refs: dict) -> str:
    KNOWN = known()
    total = len(refs)
    L = [f"# Appendix F — Standards and frameworks referenced — {BOOKS[book]}", "",
         "> **Derived, not maintained.** Generated by `_build/make_standards.py` from the manuscripts",
         "> themselves. A standard referenced in a chapter and missing from this register fails the",
         "> build, so a reference cannot enter the corpus without being disclosed here.", "",
         f"This volume references **{total} documents, standards or frameworks**. Every one is *named*",
         "and *characterised* — never reproduced. No protected text, table, figure, clause, checklist or",
         "question from any of them appears in this volume; each is described at the level of its stated",
         "scope, in this programme's own words, and the treatment of the underlying subject is this",
         "programme's own. Where a chapter needs a number, it derives one rather than citing one.", "",
         "**Nothing here implies endorsement.** No standards body, institute, professional association",
         "or financial institution has reviewed, approved or endorsed this volume, the designation it",
         "supports, or this programme. A reference means only that the document exists and is relevant",
         "to the topic under discussion.", "",
         "**Editions are deliberately not stated.** No entry below carries an edition year or revision",
         "date. Standards are revised, withdrawn and superseded on their own schedules, and a citation",
         "to a superseded edition is worse than no citation, because it reads as authoritative while",
         "being wrong. Confirming the current edition of each document against the publisher's",
         "catalogue at the date of publication is a review task, and it is recorded as outstanding in",
         "`CORPUS_GATE_REPORT.md`. **A reader consulting any document below should obtain the current",
         "edition from its publisher.** Standards are copyright works and are not reproduced or",
         "redistributed by this programme.", ""]

    for family, entries in FAMILIES:
        rows = [(ref, desc) for ref, desc in entries if ref in refs]
        if not rows:
            continue
        L += [f"## {family}", "",
              "| Reference | Described in this volume as addressing | Discussed in |",
              "|---|---|---|"]
        for ref, desc in rows:
            where = ", ".join(f"D{d}" for d in refs[ref])
            L.append(f"| **{ref}** | {desc} | {where} |")
        L += [""]

    undisclosed = sorted(set(refs) - set(KNOWN))
    if undisclosed:
        L += ["## Undisclosed references — a defect", "",
              "The following appear in the manuscripts and are **not** characterised above. This is a",
              "build defect, not a finding about the standards:", ""]
        L += [f"- `{u}` ({', '.join('D' + str(d) for d in refs[u])})" for u in undisclosed] + [""]

    L += ["## What this register does not contain", "",
          "**No bibliography of textbooks or certification-body publications.** This volume is written",
          "from first principles and its worked examples are original, so there is no borrowed material",
          "to cite. Where a body of practice is discussed — cost-estimate classification, iterative",
          "delivery, portfolio governance — the discussion is of the *practice*, described in this",
          "programme's own words, and the reader is pointed to the owning body rather than given a",
          "paraphrase of its text.", "",
          "**No legal, tax or accounting authority.** The financial-reporting standards above are named",
          "where a chapter explains why a treatment matters, never to state what the treatment is in any",
          "jurisdiction. Every such passage carries the volume's standing caution: treatments are",
          "jurisdiction-specific, and the applicable position requires written advice for the specific",
          "entity and structure. The same applies to every legal question raised in the text.", ""]
    return "\n".join(L).rstrip() + "\n"


def main() -> int:
    check_only = "--check" in sys.argv
    KNOWN, defects = known(), 0
    all_refs = {}
    for book in BOOKS:
        refs = scan(book)
        all_refs[book] = refs
        undisclosed = sorted(set(refs) - set(KNOWN))
        if not check_only:
            (ROOT / book / "STANDARDS.md").write_text(build(book, refs), encoding="utf-8")
        print(f"{book}: {len(refs)} references"
              + (f" -> {book}/STANDARDS.md" if not check_only else " (audit only)"))
        for ref in sorted(refs):
            mark = "" if ref in KNOWN else "  <-- UNDISCLOSED"
            print(f"    {ref:<26} {', '.join('D' + str(d) for d in refs[ref])}{mark}")
        defects += len(undisclosed)

    unreferenced = sorted(set(KNOWN) - set().union(*(set(r) for r in all_refs.values())))
    if unreferenced:
        print(f"\ncharacterised but referenced by neither volume ({len(unreferenced)}): "
              + ", ".join(unreferenced))
        print("  (not a build failure, but the register should not claim engagement that is absent)")
        defects += len(unreferenced)
    print(f"\nopen standards-register defects: {defects}")
    return 1 if (check_only and defects) else 0


if __name__ == "__main__":
    raise SystemExit(main())
