"""Article Bank data spine — curated seeds and dimension banks.

The generator (article_bank.py) combines these into 5,000+ distinct article
briefs. Kinds drive which angles apply to a term:
  concept  — definitional/explanatory
  metric   — has a formula: calculate/example angles
  process  — a workflow: how-to/checklist/KPI angles
  doc      — an artifact: template/build angles
"""

# ------------------------------------------------------------------ flagships
# The user's own seed topics come first — every one ships as a P1 flagship.
FLAGSHIPS = [
 ("Why PCI AI? Inside the Project Controls Institute and its AI-era credentials", "Brand & Authority", "pillar"),
 ("PMI vs PCI AI: what is the difference, and which fits your career?", "Comparisons", "comparison"),
 ("PCI AI vs the field: an honest comparison with AACE, PMI, APMG and ECITB programmes", "Comparisons", "comparison"),
 ("How many project controls jobs are there? The 2026 market, by region and role", "Careers & Jobs", "data-study"),
 ("Why a certification that blends finance + project management + AI had to exist", "Brand & Authority", "pillar"),
 ("Project management + finance + AI in one credential: the gap PCL-AI was built to fill", "Brand & Authority", "pillar"),
 ("PFL-AI vs CFA vs CA vs ACCA vs CPA vs CMA (IMA): which finance credential fits project people?", "Finance Certifications", "comparison"),
 ("Earned value management: the complete guide (EVM pillar)", "EVM & Performance", "pillar"),
 ("IFRS for project controls: the standards every cost engineer must know", "Project Accounting & IFRS", "pillar"),
 ("The phases of project management, explained with real project-controls checkpoints", "PM Fundamentals", "guide"),
 ("EAC accounting: how estimate at completion flows into the financial statements", "Project Accounting & IFRS", "guide"),
 ("Project budgeting and forecasting: a practical end-to-end guide", "Budgeting & Cash Flow", "pillar"),
 ("Project cash flow: modelling, S-curves and the forecast the CFO actually reads", "Budgeting & Cash Flow", "guide"),
 ("Project dashboards that get read: design, metrics and cadence", "Reporting & Dashboards", "guide"),
 ("AI in finance: what changes for project-facing finance teams", "AI & The Future", "guide"),
 ("AI in project management: the 2026 state of play", "AI & The Future", "pillar"),
 ("AI skills in demand: what employers now ask of project controls professionals", "AI & The Future", "data-study"),
 ("Project performance management: from metrics to decisions", "EVM & Performance", "guide"),
 ("Project financing explained for project controls professionals", "Budgeting & Cash Flow", "guide"),
 ("People and delivery: the human side of project controls", "PM Fundamentals", "guide"),
 ("Project scope: definition, creep, and the controls that hold the line", "PM Fundamentals", "guide"),
 ("WBS-level reporting in agile environments: making hybrid delivery measurable", "Scheduling & WBS", "guide"),
]

CURATED = [
 # Brand & Authority
 ("What is the Project Controls Institute (PCI AI)? Mission, credentials, governance", "Brand & Authority", "guide"),
 ("PCL-AI, PFL-AI, PML-AI: which PCI credential is right for you?", "Brand & Authority", "comparison"),
 ("Inside the PCL-AI syllabus: what the AI-era project controls leader must know", "Brand & Authority", "guide"),
 ("Inside the PFL-AI syllabus: finance foundations for project professionals", "Brand & Authority", "guide"),
 ("Inside the PML-AI syllabus: mastery for senior practitioners", "Brand & Authority", "guide"),
 ("The PCI AI honorary certification: who qualifies and how assessment works", "Brand & Authority", "guide"),
 ("How PCI AI writes its exams: item design, standard setting and integrity", "Brand & Authority", "guide"),
 ("Why project controls needed its own institute", "Brand & Authority", "guide"),
 ("How to verify a PCI AI credential (and why verification matters)", "Brand & Authority", "faq"),
 ("The PCI AI code of ethics and impartiality policy, explained", "Brand & Authority", "guide"),
 ("Certuvo: how the official PCI AI preparation platform works", "Brand & Authority", "guide"),
 ("What 'developed with reference to ISO/IEC 17024' means — and why it matters", "Brand & Authority", "guide"),
 # Careers & jobs data studies
 ("Project controls salary report: what the market pays in 2026", "Careers & Jobs", "data-study"),
 ("The Gulf giga-projects hiring wave: what it means for planners and cost engineers", "Careers & Jobs", "data-study"),
 ("Is project controls a good career? An honest assessment", "Careers & Jobs", "faq"),
 ("Project controls vs project management careers: pay, path and pressure", "Careers & Jobs", "comparison"),
 ("From site engineer to project controls: the switching guide", "Careers & Jobs", "guide"),
 ("From accountant to project controls: the finance route in", "Careers & Jobs", "guide"),
 ("From quantity surveyor to project controls: what transfers", "Careers & Jobs", "guide"),
 ("Remote and hybrid project controls jobs: who hires and how to land one", "Careers & Jobs", "guide"),
 ("Contracting vs staff roles in project controls: rates, risk and lifestyle", "Careers & Jobs", "comparison"),
 ("Women in project controls: the state of the profession", "Careers & Jobs", "data-study"),
 ("The project controls skills matrix: rate yourself honestly", "Careers & Jobs", "template"),
 ("Graduate routes into project controls: degrees, apprenticeships, first roles", "Careers & Jobs", "guide"),
 # IFRS / accounting deep set
 ("IFRS 15 for construction: percentage of completion and performance obligations", "Project Accounting & IFRS", "guide"),
 ("Revenue recognition on long-term contracts: a project controls view of IFRS 15", "Project Accounting & IFRS", "guide"),
 ("IAS 23 borrowing costs: when project interest is capitalised", "Project Accounting & IFRS", "guide"),
 ("IAS 37 provisions and onerous contracts on projects", "Project Accounting & IFRS", "guide"),
 ("IAS 16 and self-constructed assets: capitalisation rules planners should know", "Project Accounting & IFRS", "guide"),
 ("IFRS 16 leases on projects: plant, equipment and the balance sheet", "Project Accounting & IFRS", "guide"),
 ("WIP accounting on projects: work in progress without the mystery", "Project Accounting & IFRS", "guide"),
 ("Retention accounting: how retentions hit revenue, cash and risk", "Project Accounting & IFRS", "guide"),
 ("Variations and claims in the accounts: recognition rules that surprise engineers", "Project Accounting & IFRS", "guide"),
 ("Accruals vs cash on projects: why the cost report and the ledger disagree", "Project Accounting & IFRS", "guide"),
 ("Project cost audit: what auditors test and how controls teams prepare", "Project Accounting & IFRS", "guide"),
 ("Month-end close for projects: the controls-to-finance handshake", "Project Accounting & IFRS", "process-guide"),
 ("Capex vs opex on projects: classification calls that change the P&L", "Project Accounting & IFRS", "guide"),
 ("Foreign currency on international projects: IAS 21 for cost engineers", "Project Accounting & IFRS", "guide"),
 # AI curated set
 ("AI in construction scheduling: tools, wins and honest limits", "AI & The Future", "guide"),
 ("AI in cost estimating: where machine learning beats the database", "AI & The Future", "guide"),
 ("AI in risk analysis: from Monte Carlo to machine-learned distributions", "AI & The Future", "guide"),
 ("Will AI replace planning engineers? The evidence, not the hype", "AI & The Future", "faq"),
 ("Will AI replace quantity surveyors? What the data says", "AI & The Future", "faq"),
 ("Will AI replace cost engineers? Role change vs role loss", "AI & The Future", "faq"),
 ("Prompt engineering for project professionals: a working introduction", "AI & The Future", "how-to"),
 ("Using large language models to review schedules: a practical protocol", "AI & The Future", "how-to"),
 ("AI-assisted forecasting: pairing EVM with machine learning", "AI & The Future", "guide"),
 ("The ethics of AI in project decisions: accountability, bias and audit trails", "AI & The Future", "guide"),
 ("Building an AI policy for a project controls team", "AI & The Future", "template"),
 ("AI copilots for Primavera P6 and MS Project: what exists in 2026", "AI & The Future", "guide"),
 ("Digital twins and project controls: where the data meets the baseline", "AI & The Future", "guide"),
 ("Generative AI for project reports: speed without losing the audit trail", "AI & The Future", "how-to"),
 ("The AI maturity ladder for project organisations", "AI & The Future", "guide"),
 ("AI in claims and disputes: document analysis at scale", "AI & The Future", "guide"),
 ("Machine learning on productivity data: norms that update themselves", "AI & The Future", "guide"),
 ("AI risk registers: letting models propose what humans decide", "AI & The Future", "guide"),
 # Exam prep (Certuvo)
 ("PFL-AI exam guide: format, domains, pass strategy", "Exam Prep", "guide"),
 ("PCL-AI exam guide: format, domains, pass strategy", "Exam Prep", "guide"),
 ("PML-AI exam guide: format, domains, pass strategy", "Exam Prep", "guide"),
 ("The EVM formulas cheat sheet: every formula with a worked example", "Exam Prep", "template"),
 ("30-day study plan for a project controls certification", "Exam Prep", "template"),
 ("60-day study plan for working professionals", "Exam Prep", "template"),
 ("How to study for a certification while working full-time on site", "Exam Prep", "guide"),
 ("The 20 hardest earned value questions (with full solutions)", "Exam Prep", "practice"),
 ("Scheduling practice questions: 25 exam-style problems solved", "Exam Prep", "practice"),
 ("Cost management practice questions: 25 exam-style problems solved", "Exam Prep", "practice"),
 ("Risk management practice questions: 20 exam-style problems solved", "Exam Prep", "practice"),
 ("Project finance practice questions: 20 exam-style problems solved", "Exam Prep", "practice"),
 ("AI-in-projects practice questions: 20 exam-style problems solved", "Exam Prep", "practice"),
 ("Exam-day strategy: time budgeting, flagging and the last ten minutes", "Exam Prep", "guide"),
 ("Why people fail project controls exams: the five patterns", "Exam Prep", "guide"),
]

# --------------------------------------------------------------- comparisons
PCI_CERTS = ["PCL-AI", "PFL-AI", "PML-AI"]
PM_CERTS = ["PMP", "CAPM", "PMI-SP", "PMI-RMP", "PgMP", "PRINCE2", "PRINCE2 Agile",
            "APM PMQ", "AACE CCP", "AACE PSP", "AACE EVP", "AACE CEP", "AACE DRMP",
            "ECITB Project Controls", "MSP", "CIOB CMP", "RICS QS (MRICS)",
            "PMI-PMOCP", "PSM (Scrum)", "CSM (Scrum)", "SAFe Agilist", "IPMA Level C/D"]
FIN_CERTS = ["CFA", "CPA", "CA", "ACCA", "CMA (IMA)", "CIMA", "FRM", "CIA", "CAIA", "CTP"]
CROSS_PAIRS = [
 ("PMP", "PRINCE2"), ("PMP", "CAPM"), ("PMP", "AACE CCP"), ("PMP", "PMI-SP"),
 ("PMP", "CFA"), ("PMP", "CMA (IMA)"), ("PMP", "MBA"), ("PMI-SP", "AACE PSP"),
 ("AACE CCP", "AACE CEP"), ("AACE CCP", "RICS QS (MRICS)"), ("AACE PSP", "PRINCE2"),
 ("PRINCE2", "APM PMQ"), ("CFA", "FRM"), ("CFA", "CPA"), ("CFA", "ACCA"),
 ("CFA", "CAIA"), ("ACCA", "CPA"), ("ACCA", "CIMA"), ("ACCA", "CA"),
 ("CMA (IMA)", "CIMA"), ("CMA (IMA)", "CPA"), ("CIA", "CPA"), ("FRM", "PRM"),
 ("CIMA", "CGMA"), ("PgMP", "PfMP"), ("PSM (Scrum)", "CSM (Scrum)"),
 ("PRINCE2", "SAFe Agilist"), ("ECITB Project Controls", "AACE CCP"),
 ("APM PMQ", "PMP"), ("CAPM", "PRINCE2 Foundation"),
]
COMPARISON_ROUNDUPS = [
 "The best project controls certifications, honestly ranked",
 "The best certifications for planning engineers",
 "The best certifications for cost engineers and estimators",
 "The best certifications for quantity surveyors moving into controls",
 "The best finance certifications for project professionals",
 "The best entry-level project management certifications",
 "The best risk management certifications for project people",
 "The best scheduling certifications compared",
 "Certification stacking: which combinations employers actually reward",
 "Certification costs compared: every major PM and controls credential",
 "Certification renewal rules compared: CPD, PDUs and recertification",
 "Which certification first? A decision tree for project controls careers",
 "Do certifications raise salaries? The evidence by credential",
 "Online vs exam-centre certification: formats compared",
 "University degree vs professional certification for project controls",
]

# ------------------------------------------------------------------ term bank
# (term, category, kind)
TERMS = [
 # EVM & performance metrics
 ("earned value management", "EVM & Performance", "process"),
 ("planned value (PV)", "EVM & Performance", "metric"),
 ("earned value (EV)", "EVM & Performance", "metric"),
 ("actual cost (AC)", "EVM & Performance", "metric"),
 ("budget at completion (BAC)", "EVM & Performance", "metric"),
 ("estimate at completion (EAC)", "EVM & Performance", "metric"),
 ("estimate to complete (ETC)", "EVM & Performance", "metric"),
 ("variance at completion (VAC)", "EVM & Performance", "metric"),
 ("cost variance (CV)", "EVM & Performance", "metric"),
 ("schedule variance (SV)", "EVM & Performance", "metric"),
 ("cost performance index (CPI)", "EVM & Performance", "metric"),
 ("schedule performance index (SPI)", "EVM & Performance", "metric"),
 ("to-complete performance index (TCPI)", "EVM & Performance", "metric"),
 ("earned schedule", "EVM & Performance", "metric"),
 ("percent complete", "EVM & Performance", "metric"),
 ("physical percent complete", "EVM & Performance", "metric"),
 ("50/50 rule", "EVM & Performance", "concept"),
 ("0/100 rule", "EVM & Performance", "concept"),
 ("level of effort (LOE)", "EVM & Performance", "concept"),
 ("apportioned effort", "EVM & Performance", "concept"),
 ("control account", "EVM & Performance", "concept"),
 ("work package", "EVM & Performance", "concept"),
 ("planning package", "EVM & Performance", "concept"),
 ("performance measurement baseline (PMB)", "EVM & Performance", "concept"),
 ("management reserve", "EVM & Performance", "concept"),
 ("undistributed budget", "EVM & Performance", "concept"),
 ("earned value management system (EVMS)", "EVM & Performance", "process"),
 ("integrated baseline review (IBR)", "EVM & Performance", "process"),
 ("variance analysis report", "EVM & Performance", "doc"),
 ("estimate at completion methods", "EVM & Performance", "concept"),
 ("productivity factor", "EVM & Performance", "metric"),
 ("rules of credit", "EVM & Performance", "concept"),
 ("progress measurement", "EVM & Performance", "process"),
 ("performance reporting", "EVM & Performance", "process"),
 # Scheduling & WBS
 ("critical path method (CPM)", "Scheduling & WBS", "process"),
 ("critical path", "Scheduling & WBS", "concept"),
 ("near-critical path", "Scheduling & WBS", "concept"),
 ("total float", "Scheduling & WBS", "metric"),
 ("free float", "Scheduling & WBS", "metric"),
 ("negative float", "Scheduling & WBS", "concept"),
 ("float ownership", "Scheduling & WBS", "concept"),
 ("schedule baseline", "Scheduling & WBS", "concept"),
 ("re-baselining", "Scheduling & WBS", "process"),
 ("schedule levels (L1-L5)", "Scheduling & WBS", "concept"),
 ("work breakdown structure (WBS)", "Scheduling & WBS", "process"),
 ("WBS dictionary", "Scheduling & WBS", "doc"),
 ("organisational breakdown structure (OBS)", "Scheduling & WBS", "concept"),
 ("cost breakdown structure (CBS)", "Scheduling & WBS", "concept"),
 ("responsibility assignment matrix (RAM)", "Scheduling & WBS", "doc"),
 ("activity duration estimating", "Scheduling & WBS", "process"),
 ("lag and lead", "Scheduling & WBS", "concept"),
 ("finish-to-start relationship", "Scheduling & WBS", "concept"),
 ("start-to-start relationship", "Scheduling & WBS", "concept"),
 ("constraints in scheduling", "Scheduling & WBS", "concept"),
 ("schedule crashing", "Scheduling & WBS", "process"),
 ("fast tracking", "Scheduling & WBS", "process"),
 ("resource levelling", "Scheduling & WBS", "process"),
 ("resource loading", "Scheduling & WBS", "process"),
 ("schedule compression", "Scheduling & WBS", "process"),
 ("look-ahead schedule", "Scheduling & WBS", "doc"),
 ("baseline schedule review", "Scheduling & WBS", "process"),
 ("schedule health check", "Scheduling & WBS", "process"),
 ("DCMA 14-point assessment", "Scheduling & WBS", "process"),
 ("schedule quality metrics", "Scheduling & WBS", "concept"),
 ("out-of-sequence progress", "Scheduling & WBS", "concept"),
 ("progress override vs retained logic", "Scheduling & WBS", "concept"),
 ("data date", "Scheduling & WBS", "concept"),
 ("schedule narrative", "Scheduling & WBS", "doc"),
 ("fragnet", "Scheduling & WBS", "concept"),
 ("milestone management", "Scheduling & WBS", "process"),
 ("interface milestones", "Scheduling & WBS", "concept"),
 ("schedule basis document", "Scheduling & WBS", "doc"),
 ("rolling wave planning", "Scheduling & WBS", "process"),
 ("line of balance", "Scheduling & WBS", "process"),
 ("time-location charts", "Scheduling & WBS", "concept"),
 ("pull planning", "Scheduling & WBS", "process"),
 ("last planner system", "Scheduling & WBS", "process"),
 ("takt planning", "Scheduling & WBS", "process"),
 ("4D scheduling", "Scheduling & WBS", "process"),
 ("schedule risk analysis (QSRA)", "Scheduling & WBS", "process"),
 ("Monte Carlo schedule simulation", "Scheduling & WBS", "process"),
 ("P50 vs P80 dates", "Scheduling & WBS", "concept"),
 ("schedule contingency", "Scheduling & WBS", "concept"),
 ("weather calendars", "Scheduling & WBS", "concept"),
 ("calendars in P6", "Scheduling & WBS", "concept"),
 ("activity coding structures", "Scheduling & WBS", "concept"),
 ("baseline vs current schedule comparison", "Scheduling & WBS", "process"),
 ("as-built schedule", "Scheduling & WBS", "doc"),
 ("short interval control", "Scheduling & WBS", "process"),
 # Cost estimating & control
 ("cost estimating", "Cost & Estimating", "process"),
 ("estimate classification (AACE 17R-97)", "Cost & Estimating", "concept"),
 ("class 5 estimate", "Cost & Estimating", "concept"),
 ("class 3 estimate", "Cost & Estimating", "concept"),
 ("class 1 estimate", "Cost & Estimating", "concept"),
 ("parametric estimating", "Cost & Estimating", "process"),
 ("analogous estimating", "Cost & Estimating", "process"),
 ("bottom-up estimating", "Cost & Estimating", "process"),
 ("first principles estimating", "Cost & Estimating", "process"),
 ("unit rate estimating", "Cost & Estimating", "process"),
 ("estimate basis document", "Cost & Estimating", "doc"),
 ("estimate accuracy range", "Cost & Estimating", "concept"),
 ("contingency estimating", "Cost & Estimating", "process"),
 ("escalation in estimates", "Cost & Estimating", "concept"),
 ("location factors", "Cost & Estimating", "concept"),
 ("cost benchmarking", "Cost & Estimating", "process"),
 ("should-cost modelling", "Cost & Estimating", "process"),
 ("cost control", "Cost & Estimating", "process"),
 ("commitment tracking", "Cost & Estimating", "process"),
 ("incurred cost vs committed cost", "Cost & Estimating", "concept"),
 ("cost report", "Cost & Estimating", "doc"),
 ("cost coding", "Cost & Estimating", "concept"),
 ("change management (cost)", "Cost & Estimating", "process"),
 ("trend management", "Cost & Estimating", "process"),
 ("budget transfer", "Cost & Estimating", "concept"),
 ("original budget vs current budget", "Cost & Estimating", "concept"),
 ("anticipated final cost (AFC)", "Cost & Estimating", "metric"),
 ("cost value reconciliation (CVR)", "Cost & Estimating", "process"),
 ("value of work done (VOWD)", "Cost & Estimating", "metric"),
 ("quantity tracking", "Cost & Estimating", "process"),
 ("man-hour norms", "Cost & Estimating", "concept"),
 ("productivity analysis", "Cost & Estimating", "process"),
 ("learning curves", "Cost & Estimating", "concept"),
 ("indirect costs on projects", "Cost & Estimating", "concept"),
 ("preliminaries and general conditions", "Cost & Estimating", "concept"),
 ("life cycle costing", "Cost & Estimating", "process"),
 ("whole life cost vs capital cost", "Cost & Estimating", "concept"),
 ("value engineering", "Cost & Estimating", "process"),
 ("cost of quality", "Cost & Estimating", "concept"),
 # Budgeting & cash flow
 ("project budgeting", "Budgeting & Cash Flow", "process"),
 ("budget baseline", "Budgeting & Cash Flow", "concept"),
 ("cost forecasting", "Budgeting & Cash Flow", "process"),
 ("cash flow forecasting", "Budgeting & Cash Flow", "process"),
 ("S-curve", "Budgeting & Cash Flow", "concept"),
 ("front-end loading of budgets", "Budgeting & Cash Flow", "concept"),
 ("phased budgeting", "Budgeting & Cash Flow", "process"),
 ("funding profiles", "Budgeting & Cash Flow", "concept"),
 ("drawdown schedules", "Budgeting & Cash Flow", "doc"),
 ("invoice and payment cycles on projects", "Budgeting & Cash Flow", "concept"),
 ("payment applications", "Budgeting & Cash Flow", "process"),
 ("milestone payments", "Budgeting & Cash Flow", "concept"),
 ("advance payments and guarantees", "Budgeting & Cash Flow", "concept"),
 ("working capital on projects", "Budgeting & Cash Flow", "concept"),
 ("project P&L", "Budgeting & Cash Flow", "concept"),
 ("margin erosion", "Budgeting & Cash Flow", "concept"),
 ("cost to complete review", "Budgeting & Cash Flow", "process"),
 ("annual budgeting for portfolios", "Budgeting & Cash Flow", "process"),
 ("capital allocation for projects", "Budgeting & Cash Flow", "process"),
 ("business case development", "Budgeting & Cash Flow", "process"),
 ("net present value (NPV)", "Budgeting & Cash Flow", "metric"),
 ("internal rate of return (IRR)", "Budgeting & Cash Flow", "metric"),
 ("payback period", "Budgeting & Cash Flow", "metric"),
 ("discount rates on projects", "Budgeting & Cash Flow", "concept"),
 ("sensitivity analysis (financial)", "Budgeting & Cash Flow", "process"),
 ("project financing structures", "Budgeting & Cash Flow", "concept"),
 ("public-private partnerships (PPP)", "Budgeting & Cash Flow", "concept"),
 ("export credit financing", "Budgeting & Cash Flow", "concept"),
 # Risk
 ("project risk management", "Risk", "process"),
 ("risk register", "Risk", "doc"),
 ("risk breakdown structure", "Risk", "concept"),
 ("qualitative risk analysis", "Risk", "process"),
 ("quantitative risk analysis (QRA)", "Risk", "process"),
 ("Monte Carlo cost simulation", "Risk", "process"),
 ("probability-impact matrix", "Risk", "doc"),
 ("risk appetite and tolerance", "Risk", "concept"),
 ("contingency drawdown", "Risk", "process"),
 ("risk-adjusted forecast", "Risk", "concept"),
 ("schedule risk vs cost risk", "Risk", "concept"),
 ("correlation in risk models", "Risk", "concept"),
 ("systemic vs project-specific risk", "Risk", "concept"),
 ("risk workshops", "Risk", "process"),
 ("pre-mortem analysis", "Risk", "process"),
 ("risk owner", "Risk", "concept"),
 ("secondary and residual risk", "Risk", "concept"),
 ("opportunity management", "Risk", "process"),
 ("black swan events on projects", "Risk", "concept"),
 ("reference class forecasting", "Risk", "process"),
 ("optimism bias", "Risk", "concept"),
 ("risk normalisation", "Risk", "concept"),
 # Contracts & claims
 ("contract administration", "Contracts & Claims", "process"),
 ("NEC4 compensation events", "Contracts & Claims", "concept"),
 ("NEC4 early warnings", "Contracts & Claims", "concept"),
 ("NEC4 main options (A to F)", "Contracts & Claims", "concept"),
 ("FIDIC claims procedure", "Contracts & Claims", "process"),
 ("extension of time (EOT)", "Contracts & Claims", "process"),
 ("concurrent delay", "Contracts & Claims", "concept"),
 ("delay analysis methods", "Contracts & Claims", "concept"),
 ("time impact analysis", "Contracts & Claims", "process"),
 ("as-planned vs as-built analysis", "Contracts & Claims", "process"),
 ("window analysis", "Contracts & Claims", "process"),
 ("collapsed as-built analysis", "Contracts & Claims", "process"),
 ("forensic schedule analysis", "Contracts & Claims", "process"),
 ("disruption claims", "Contracts & Claims", "concept"),
 ("measured mile analysis", "Contracts & Claims", "process"),
 ("global claims", "Contracts & Claims", "concept"),
 ("liquidated damages", "Contracts & Claims", "concept"),
 ("variations and change orders", "Contracts & Claims", "process"),
 ("notices and time bars", "Contracts & Claims", "concept"),
 ("records for claims", "Contracts & Claims", "process"),
 ("acceleration claims", "Contracts & Claims", "concept"),
 ("prolongation costs", "Contracts & Claims", "concept"),
 ("head office overheads in claims", "Contracts & Claims", "concept"),
 ("dispute boards", "Contracts & Claims", "concept"),
 ("adjudication", "Contracts & Claims", "concept"),
 ("target cost contracts", "Contracts & Claims", "concept"),
 ("pain/gain share mechanisms", "Contracts & Claims", "concept"),
 ("lump sum vs reimbursable contracts", "Contracts & Claims", "concept"),
 ("back-to-back subcontracts", "Contracts & Claims", "concept"),
 # Reporting & dashboards
 ("project reporting", "Reporting & Dashboards", "process"),
 ("monthly project report", "Reporting & Dashboards", "doc"),
 ("executive dashboard", "Reporting & Dashboards", "doc"),
 ("KPI selection for projects", "Reporting & Dashboards", "process"),
 ("leading vs lagging indicators", "Reporting & Dashboards", "concept"),
 ("RAG status reporting", "Reporting & Dashboards", "concept"),
 ("trend charts", "Reporting & Dashboards", "concept"),
 ("waterfall charts for cost movement", "Reporting & Dashboards", "concept"),
 ("histogram and resource curves", "Reporting & Dashboards", "concept"),
 ("narrative reporting", "Reporting & Dashboards", "process"),
 ("one-page project status", "Reporting & Dashboards", "doc"),
 ("data quality for reporting", "Reporting & Dashboards", "process"),
 ("single source of truth", "Reporting & Dashboards", "concept"),
 ("reporting calendars and cadence", "Reporting & Dashboards", "concept"),
 ("stakeholder-specific reporting", "Reporting & Dashboards", "process"),
 ("automated reporting pipelines", "Reporting & Dashboards", "process"),
 # PMO & governance
 ("project management office (PMO)", "PMO & Governance", "concept"),
 ("PMO types (supportive to directive)", "PMO & Governance", "concept"),
 ("stage gates", "PMO & Governance", "process"),
 ("gate review criteria", "PMO & Governance", "doc"),
 ("project assurance", "PMO & Governance", "process"),
 ("portfolio prioritisation", "PMO & Governance", "process"),
 ("benefits realisation", "PMO & Governance", "process"),
 ("lessons learned", "PMO & Governance", "process"),
 ("project audits", "PMO & Governance", "process"),
 ("delegation of authority", "PMO & Governance", "concept"),
 ("governance boards", "PMO & Governance", "concept"),
 ("project charter", "PMO & Governance", "doc"),
 ("terms of reference", "PMO & Governance", "doc"),
 ("RACI matrix", "PMO & Governance", "doc"),
 ("project controls maturity assessment", "PMO & Governance", "process"),
 ("centre of excellence for controls", "PMO & Governance", "concept"),
 # Agile & hybrid
 ("agile project controls", "Agile & Hybrid", "concept"),
 ("scrum for non-software projects", "Agile & Hybrid", "concept"),
 ("sprint planning", "Agile & Hybrid", "process"),
 ("burndown and burnup charts", "Agile & Hybrid", "concept"),
 ("velocity", "Agile & Hybrid", "metric"),
 ("story points vs hours", "Agile & Hybrid", "concept"),
 ("kanban for engineering teams", "Agile & Hybrid", "process"),
 ("hybrid delivery models", "Agile & Hybrid", "concept"),
 ("earned value in agile", "Agile & Hybrid", "concept"),
 ("agile release planning", "Agile & Hybrid", "process"),
 ("definition of done", "Agile & Hybrid", "concept"),
 ("backlog management", "Agile & Hybrid", "process"),
 ("scaled agile on capital projects", "Agile & Hybrid", "concept"),
 ("iteration reviews and retrospectives", "Agile & Hybrid", "process"),
 # Data & BI
 ("project data model", "Data & BI", "concept"),
 ("Power BI for project controls", "Data & BI", "process"),
 ("dashboards in Power BI vs Excel", "Data & BI", "concept"),
 ("ETL for project data", "Data & BI", "process"),
 ("P6 database queries", "Data & BI", "process"),
 ("XER file structure", "Data & BI", "concept"),
 ("data warehouses for portfolios", "Data & BI", "concept"),
 ("master data management on projects", "Data & BI", "process"),
 ("Python for planners", "Data & BI", "process"),
 ("pandas for schedule analysis", "Data & BI", "process"),
 ("APIs between project tools", "Data & BI", "concept"),
 ("spreadsheet risk and controls", "Data & BI", "concept"),
 ("version control for project data", "Data & BI", "concept"),
 ("data governance for controls teams", "Data & BI", "process"),
 # Procurement & supply chain
 ("procurement strategy", "Procurement", "process"),
 ("long lead items", "Procurement", "concept"),
 ("expediting", "Procurement", "process"),
 ("bid evaluation", "Procurement", "process"),
 ("tender clarifications", "Procurement", "concept"),
 ("supplier performance management", "Procurement", "process"),
 ("material tracking", "Procurement", "process"),
 ("logistics windows on projects", "Procurement", "concept"),
 ("incoterms for project cargo", "Procurement", "concept"),
 ("vendor document control", "Procurement", "process"),
 # PM fundamentals
 ("project life cycle", "PM Fundamentals", "concept"),
 ("front end loading (FEL)", "PM Fundamentals", "concept"),
 ("FEED stage", "PM Fundamentals", "concept"),
 ("final investment decision (FID)", "PM Fundamentals", "concept"),
 ("scope management", "PM Fundamentals", "process"),
 ("scope creep", "PM Fundamentals", "concept"),
 ("requirements management", "PM Fundamentals", "process"),
 ("baseline change control", "PM Fundamentals", "process"),
 ("stakeholder management", "PM Fundamentals", "process"),
 ("communication planning", "PM Fundamentals", "process"),
 ("project handover and closeout", "PM Fundamentals", "process"),
 ("commissioning and startup planning", "PM Fundamentals", "process"),
 ("mechanical completion", "PM Fundamentals", "concept"),
 ("punch lists", "PM Fundamentals", "doc"),
 ("readiness reviews", "PM Fundamentals", "process"),
 ("constructability reviews", "PM Fundamentals", "process"),
 ("interface management", "PM Fundamentals", "process"),
 ("document control", "PM Fundamentals", "process"),
 ("progress meetings that work", "PM Fundamentals", "process"),
 ("site-office data flow", "PM Fundamentals", "concept"),
]

# ------------------------------------------------------------------ dimensions
ROLES = ["planning engineer", "senior planning engineer", "project controls engineer",
         "project controls manager", "project controls lead", "project controls director",
         "cost controller", "cost engineer", "quantity surveyor", "project scheduler",
         "risk manager", "PMO analyst", "PMO manager", "estimator", "EVM analyst",
         "project accountant", "contracts administrator", "claims consultant",
         "forensic delay analyst"]
ROLE_ANGLES = [
 ("How to become a {r}: qualifications, path and first role", "how-to"),
 ("{R} salary guide: what the market pays by region", "data-study"),
 ("{R} interview questions (and answers that impress)", "guide"),
 ("{R} CV guide: what recruiters scan for", "guide"),
 ("A day in the life of a {r}", "guide"),
 ("{R} career path: junior to director", "guide"),
 ("Skills every {r} needs in the AI era", "guide"),
 ("Best certifications for a {r}", "comparison"),
 ("How AI is changing the {r} role", "guide"),
 ("Freelance and contract market for {r}s", "guide"),
]
GEOS = ["UAE", "Dubai", "Abu Dhabi", "Saudi Arabia", "Riyadh", "Qatar", "Kuwait",
        "Oman", "Bahrain", "UK", "London", "USA", "Canada", "Australia", "India",
        "Singapore", "Malaysia", "Nigeria", "South Africa", "Ireland"]
GEO_TOPICS = [
 ("Project controls jobs in {g}: market, employers and how to get in", "guide"),
 ("Planning engineer salary in {g}: the honest numbers", "data-study"),
 ("Project controls courses and certification in {g}", "guide"),
 ("Cost engineer and cost controller salaries in {g}", "data-study"),
 ("Quantity surveyor to project controls in {g}: the local route", "guide"),
 ("The biggest projects hiring in {g} right now", "data-study"),
 ("Work visas and moving to {g} as a project controls professional", "guide"),
 ("PCL-AI certification in {g}: exam access, recognition and salary uplift", "guide"),
 ("PFL-AI certification in {g}: who it fits and why", "guide"),
 ("PML-AI certification in {g}: the senior credential, locally", "guide"),
 ("Contract day rates for planners and cost engineers in {g}", "data-study"),
 ("Interview culture in {g}: what project controls candidates should expect", "guide"),
 ("Cost of living vs project salaries in {g}", "data-study"),
 ("Top employers for project controls in {g}", "guide"),
 ("How to land a project controls job in {g} from abroad", "guide"),
 ("{g} construction market outlook for project professionals", "data-study"),
]
INDUSTRIES = ["oil and gas", "LNG", "rail", "highways", "nuclear", "offshore wind",
              "solar and renewables", "data centres", "airports", "ports", "mining",
              "pharmaceutical plants", "semiconductor fabs", "defence", "hospitals",
              "stadiums and mega-events", "high-rise construction", "metro and tunnelling",
              "power transmission", "green hydrogen"]
INDUSTRY_ANGLES = [
 ("Project controls in {i}: what makes it different", "guide"),
 ("Scheduling challenges unique to {i} projects", "guide"),
 ("Why {i} projects overrun: causes and the data", "data-study"),
 ("Earned value management on {i} projects", "guide"),
 ("Cost benchmarks and metrics for {i} projects", "data-study"),
 ("Careers in {i} project controls: entry routes and pay", "guide"),
 ("Risk hotspots on {i} projects: where the money leaks", "guide"),
 ("Typical schedule phases and durations for {i} projects", "guide"),
]
TOOLS = ["Primavera P6", "Microsoft Project", "Deltek Cobra", "Deltek Acumen Fuse",
         "EcoSys", "Safran Project", "Tilos", "Asta Powerproject", "Primavera Risk Analysis",
         "Power BI", "Excel", "Python", "Synchro 4D", "nPlan", "ALICE Technologies",
         "SAP Project Systems", "Oracle Unifier"]
TOOL_ANGLES = [
 ("{t} for beginners: a working introduction", "how-to"),
 ("Top {t} tips professionals wish they knew earlier", "guide"),
 ("Common {t} errors and how to fix them", "guide"),
 ("Using {t} for earned value management", "how-to"),
 ("{t} reporting: getting clean outputs stakeholders read", "how-to"),
 ("Is {t} certification worth it? Training options compared", "comparison"),
 ("Setting up {t} for a new project: the configuration checklist", "template"),
 ("{t} for cost engineers vs planners: the features that matter to each", "guide"),
]
STANDARDS_TOPICS = [
 "PMBOK's 12 principles, translated for project controls people",
 "PMBOK performance domains: a controls-eye view",
 "ISO 21500 and 21502: what the project management standards actually say",
 "ISO 31000 risk management on capital projects",
 "EIA-748 EVMS guidelines explained in plain language",
 "The 32 EVMS guidelines grouped: organisation, planning, accounting, analysis, revisions",
 "AACE's Total Cost Management framework: the map of the discipline",
 "AACE 17R-97 estimate classification explained with examples",
 "AACE 18R-97 cost estimate classification for process industries",
 "AACE 29R-03 forensic schedule analysis: the method families",
 "Choosing a delay analysis method under AACE 29R-03",
 "AACE recommended practices every planner should read",
 "GAO Schedule Assessment Guide: the ten best practices",
 "GAO Cost Estimating Guide: the twelve steps",
 "NEC4 for project controls: programme obligations that bite",
 "The NEC4 Accepted Programme: clause 31 and 32 in practice",
 "FIDIC 2017 programme requirements (clause 8) explained",
 "SCL Delay and Disruption Protocol: core principles",
 "UK IPA project routemap: lessons for controls teams",
 "P3M3 maturity model: assessing your organisation",
 "APM Body of Knowledge: the controls-relevant chapters",
 "Earned Schedule standard practice: beyond SPI",
 "ISO 19650 information management and the planner",
 "Uniclass and classification systems for cost data",
]
LISTS_TRENDS = [
 "Project management statistics that matter in 2026 (sourced)",
 "Construction cost overrun statistics: the honest numbers",
 "Megaproject failure rates: what the research actually shows",
 "AI in construction statistics: adoption, spend, results",
 "The best books on project controls, reviewed",
 "The best books on earned value management",
 "The best project management podcasts worth your commute",
 "The best free tools for planners and cost engineers",
 "The best Excel functions for project controls work",
 "The best LinkedIn newsletters for project professionals",
 "Project controls conferences and events calendar 2026-27",
 "The best YouTube channels for learning Primavera P6",
 "Common myths about project controls, debunked",
 "Common myths about earned value management, debunked",
 "Ten habits of exceptional planning engineers",
 "Ten red flags in a project schedule",
 "Ten red flags in a cost report",
 "Ten questions every project director should ask their controls team",
 "The KPI library: 50 project metrics with formulas",
 "Reports every capital project should produce monthly",
 "Glossary: 100 project controls terms in one page",
 "The project controls reading list for your first 90 days",
 "Trends shaping project controls in 2026",
 "What CFOs wish project managers understood about cost",
 "What project managers wish finance understood about projects",
]
FAQS = [
 "Is project controls a stressful job?",
 "Is project controls in demand?",
 "Can you do project controls remotely?",
 "Do you need an engineering degree for project controls?",
 "Is planning engineering a dying career?",
 "What does a project controls team actually do?",
 "How long does it take to learn Primavera P6?",
 "Is Primavera P6 hard to learn?",
 "Excel or Primavera: which should you learn first?",
 "What is the difference between a planner and a scheduler?",
 "What is the difference between cost control and cost management?",
 "What is the difference between a cost engineer and a quantity surveyor?",
 "What is the difference between estimating and budgeting?",
 "What is the difference between contingency and management reserve?",
 "What is the difference between accruals and commitments?",
 "What is the difference between EAC and ETC?",
 "What is the difference between CPI and SPI?",
 "What is the difference between total float and free float?",
 "What is the difference between baseline and target schedule?",
 "What is the difference between a WBS and an OBS?",
 "What is the difference between agile and waterfall on real projects?",
 "Does earned value work on agile projects?",
 "Does earned value work on small projects?",
 "Why do projects always seem to finish late?",
 "Why do estimates keep growing?",
 "Who owns float on a construction project?",
 "Who should the project controls team report to?",
 "When should you re-baseline a project?",
 "When is a schedule too detailed?",
 "How many activities should a schedule have?",
 "How often should you update a project forecast?",
 "How accurate should a class 3 estimate be?",
 "Can a project recover from a CPI below 0.8?",
 "What CPI is considered good?",
 "What does negative float actually mean?",
 "Is a 100% on-time project portfolio believable?",
 "Should contingency be visible to the delivery team?",
 "Are Gantt charts outdated?",
 "Is the critical path always right?",
 "Do certifications matter more than experience?",
 "Which pays more: planning or cost control?",
 "Is quantity surveying still a good career in the AI era?",
 "What is a healthy schedule float percentage?",
 "What percentage of project cost should controls cost?",
 "Can ChatGPT build a project schedule?",
 "Can AI predict project overruns?",
 "Is AI going to replace the PMO?",
 "What AI tools do planners actually use in 2026?",
 "Are AI certifications worth it for project managers?",
 "What maths do you need for project controls?",
]

# ----------------------------------------------------- extension vocabularies
TERMS += [
 # QS & measurement
 ("bill of quantities (BOQ)", "QS & Measurement", "doc"),
 ("quantity takeoff", "QS & Measurement", "process"),
 ("material takeoff (MTO)", "QS & Measurement", "doc"),
 ("NRM 1 and NRM 2 measurement rules", "QS & Measurement", "concept"),
 ("CESMM4 measurement", "QS & Measurement", "concept"),
 ("POMI measurement rules", "QS & Measurement", "concept"),
 ("interim valuations", "QS & Measurement", "process"),
 ("final accounts", "QS & Measurement", "process"),
 ("dayworks", "QS & Measurement", "concept"),
 ("provisional sums", "QS & Measurement", "concept"),
 ("prime cost sums", "QS & Measurement", "concept"),
 ("remeasurement contracts", "QS & Measurement", "concept"),
 ("schedule of rates", "QS & Measurement", "doc"),
 ("cost plans (RIBA stages)", "QS & Measurement", "doc"),
 ("elemental cost analysis", "QS & Measurement", "process"),
 ("benchmarking rates per m2", "QS & Measurement", "concept"),
 ("subcontractor procurement packages", "QS & Measurement", "process"),
 ("payment notices and pay-less notices", "QS & Measurement", "concept"),
 ("retention release", "QS & Measurement", "concept"),
 ("loss and expense claims", "QS & Measurement", "concept"),
 # Project finance instruments
 ("performance bonds", "Project Finance", "concept"),
 ("advance payment bonds", "Project Finance", "concept"),
 ("retention bonds", "Project Finance", "concept"),
 ("parent company guarantees", "Project Finance", "concept"),
 ("letters of credit on projects", "Project Finance", "concept"),
 ("surety and bonding capacity", "Project Finance", "concept"),
 ("construction all risks (CAR) insurance", "Project Finance", "concept"),
 ("delay in start-up (DSU) insurance", "Project Finance", "concept"),
 ("escrow accounts on projects", "Project Finance", "concept"),
 ("project bank accounts", "Project Finance", "concept"),
 ("WACC and hurdle rates for projects", "Project Finance", "concept"),
 ("debt service cover ratio (DSCR)", "Project Finance", "metric"),
 ("equity vs debt funding on projects", "Project Finance", "concept"),
 ("lender's technical advisor role", "Project Finance", "concept"),
 ("drawdown certificates", "Project Finance", "doc"),
 ("cost to complete certification for lenders", "Project Finance", "process"),
 ("bank guarantees vs insurance bonds", "Project Finance", "concept"),
 ("currency hedging on international projects", "Project Finance", "concept"),
 ("inflation indices and indexation clauses", "Project Finance", "concept"),
 ("tax considerations on cross-border projects", "Project Finance", "concept"),
 # Turnarounds & operations
 ("turnaround (STO) planning", "Turnarounds & Ops", "process"),
 ("shutdown scope freeze", "Turnarounds & Ops", "concept"),
 ("wrench time analysis", "Turnarounds & Ops", "process"),
 ("turnaround readiness index", "Turnarounds & Ops", "metric"),
 ("blind lists and isolation planning", "Turnarounds & Ops", "concept"),
 ("discovery work management", "Turnarounds & Ops", "process"),
 ("turnaround cost norms", "Turnarounds & Ops", "concept"),
 ("outage scheduling for power plants", "Turnarounds & Ops", "process"),
 ("maintenance backlogs and prioritisation", "Turnarounds & Ops", "process"),
 ("operational readiness (OR) planning", "Turnarounds & Ops", "process"),
 # P6 / tool-specific concepts
 ("P6 activity types", "Scheduling & WBS", "concept"),
 ("P6 percent complete types", "Scheduling & WBS", "concept"),
 ("P6 resource curves", "Scheduling & WBS", "concept"),
 ("P6 global change", "Scheduling & WBS", "process"),
 ("P6 baselines management", "Scheduling & WBS", "process"),
 ("P6 layouts and filters", "Scheduling & WBS", "concept"),
 ("P6 scheduling options (F9 settings)", "Scheduling & WBS", "concept"),
 ("XER import/export pitfalls", "Data & BI", "concept"),
 ("P6 vs Microsoft Project data models", "Data & BI", "concept"),
 ("claim digger / schedule comparison", "Data & BI", "process"),
 # Estimating detail
 ("crew composition and crew rates", "Cost & Estimating", "concept"),
 ("plant and equipment rates", "Cost & Estimating", "concept"),
 ("labour norms by trade", "Cost & Estimating", "concept"),
 ("growth allowance vs contingency", "Cost & Estimating", "concept"),
 ("design allowance", "Cost & Estimating", "concept"),
 ("estimate maturity assessment", "Cost & Estimating", "process"),
 ("bid/no-bid analysis", "Cost & Estimating", "process"),
 ("tender settlement meetings", "Cost & Estimating", "process"),
 ("subcontractor quotations analysis", "Cost & Estimating", "process"),
 ("estimate reviews and cold eyes", "Cost & Estimating", "process"),
 ("currency and escalation in bids", "Cost & Estimating", "concept"),
 ("margin and markup strategy", "Cost & Estimating", "concept"),
 # Risk detail
 ("tornado diagrams", "Risk", "concept"),
 ("expected monetary value (EMV)", "Risk", "metric"),
 ("decision tree analysis", "Risk", "process"),
 ("risk velocity", "Risk", "concept"),
 ("quantified risk exposure", "Risk", "metric"),
 ("integrated cost-schedule risk analysis", "Risk", "process"),
 ("risk maturity models", "Risk", "concept"),
 ("weather risk quantification", "Risk", "process"),
 ("supply chain risk on projects", "Risk", "concept"),
 ("interface risk", "Risk", "concept"),
 # Reporting/comms detail
 ("board papers for projects", "Reporting & Dashboards", "doc"),
 ("cost narrative writing", "Reporting & Dashboards", "process"),
 ("schedule commentary writing", "Reporting & Dashboards", "process"),
 ("visualising float erosion", "Reporting & Dashboards", "concept"),
 ("portfolio heatmaps", "Reporting & Dashboards", "doc"),
 ("earned value dashboards", "Reporting & Dashboards", "doc"),
 ("cash flow dashboards", "Reporting & Dashboards", "doc"),
 ("risk dashboards", "Reporting & Dashboards", "doc"),
 # Commissioning / completion
 ("systems completion and turnover packages", "PM Fundamentals", "process"),
 ("commissioning sequence logic", "PM Fundamentals", "concept"),
 ("care custody and control transfer", "PM Fundamentals", "concept"),
 ("performance test criteria", "PM Fundamentals", "concept"),
 ("defects liability period management", "PM Fundamentals", "process"),
 ("warranty claims tracking", "PM Fundamentals", "process"),
]

GEOS += ["Germany", "Netherlands", "Norway", "New Zealand", "Hong Kong", "Egypt"]

FAQS += [
 "What is a good SPI value?",
 "What does an S-curve tell you?",
 "How do you baseline a programme in P6?",
 "What is the difference between a budget and a forecast?",
 "What is the difference between cash flow and cost flow?",
 "What is the difference between VOWD and actual cost?",
 "What is the difference between accrual and provision?",
 "What is the difference between a trend and a change?",
 "What is the difference between a claim and a variation?",
 "What is the difference between EOT and acceleration?",
 "What is the difference between prolongation and disruption?",
 "How much contingency should a project carry?",
 "How do you forecast final cost mid-project?",
 "How do you measure engineering progress?",
 "How do you measure procurement progress?",
 "How do you measure construction progress?",
 "What does a planning engineer do all day?",
 "What software should a cost engineer learn first?",
 "Do planners need to know how to code?",
 "Is Power BI worth learning for project controls?",
 "What Excel skills do project controls jobs require?",
 "How do you present bad news on a project?",
 "What makes a good weekly project report?",
 "How do you handle a project manager who ignores the forecast?",
 "Why do cost reports and finance reports never match?",
 "What is a healthy change order rate?",
 "What percentage of projects finish on budget?",
 "What is the most in-demand project controls skill in 2026?",
 "How do Gulf project salaries compare with the UK and US?",
 "Are project controls certifications recognised internationally?",
 "How long does it take to become a project controls manager?",
 "Can you move from PMO analyst to project controls?",
 "What is the career ceiling for a planning engineer?",
 "Do project controls professionals become project directors?",
 "What questions should you ask in a project controls interview?",
 "What is a reasonable notice period for contract planners?",
 "Should planners be embedded in delivery teams or central?",
 "What does world-class project controls look like?",
 "Who invented earned value management?",
 "Why is it called earned value?",
 "What projects made project controls famous?",
 "What is the oldest project management technique still used?",
 "Is PERT still used today?",
 "What replaced the Gantt chart, if anything?",
 "How is AI used in project scheduling today?",
 "What data does an AI schedule model need?",
 "Can AI write a basis of schedule?",
 "Should AI outputs go in a contractual programme?",
 "How do you audit an AI-assisted forecast?",
 "What jobs will AI create in project controls?",
 "What is a basis of schedule document?",
 "What is a basis of estimate document?",
 "What is progress s-curve reporting?",
 "What is a project controls plan?",
 "What is schedule float mapping?",
 "What is a resource histogram?",
 "What is cost loading a schedule?",
 "What is schedule levelling vs smoothing?",
 "What is a variance threshold?",
 "What is a work authorisation document?",
 "What is freeze period in scheduling?",
 "What is a schedule basis memorandum?",
]

# Case studies: famous projects with public post-mortems worth analysing
PROJECTS = [
 "Crossrail (the Elizabeth Line)", "HS2", "the Sydney Opera House",
 "the Channel Tunnel", "Burj Khalifa", "the Panama Canal expansion",
 "Berlin Brandenburg Airport", "Boston's Big Dig", "NEOM and The Line",
 "Hinkley Point C", "London 2012 Olympics", "Paris 2024 Olympics",
 "Denver International Airport", "the Suez Canal expansion", "ITER fusion project",
 "the James Webb Space Telescope", "the Boeing 787 programme", "the F-35 programme",
 "California High-Speed Rail", "New York's Second Avenue Subway",
 "the Hoover Dam", "the Empire State Building", "Heathrow Terminal 5",
 "Dubai Metro", "the Riyadh Metro",
]

TOOL_PAIRS = [
 ("Primavera P6", "Microsoft Project"), ("Primavera P6", "Asta Powerproject"),
 ("Deltek Acumen Fuse", "DCMA checks in P6"), ("Power BI", "Excel dashboards"),
 ("Primavera Risk Analysis", "Safran Risk"), ("EcoSys", "Deltek Cobra"),
 ("nPlan", "ALICE Technologies"), ("Synchro 4D", "Navisworks TimeLiner"),
 ("Tilos", "time-location in P6"), ("SAP Project Systems", "Oracle Unifier"),
]

TERM_VS = [
 ("EAC", "ETC"), ("CPI", "SPI"), ("CV", "SV"), ("BAC", "EAC"),
 ("planned value", "earned value"), ("earned value", "actual cost"),
 ("total float", "free float"), ("critical path", "critical chain"),
 ("crashing", "fast tracking"), ("contingency", "management reserve"),
 ("baseline", "re-baseline"), ("forecast", "budget"),
 ("QSRA", "QCRA"), ("deterministic", "probabilistic scheduling"),
 ("top-down estimating", "bottom-up estimating"),
 ("parametric estimating", "analogous estimating"),
 ("accruals", "commitments"), ("VOWD", "earned value"),
 ("cost control", "cost accounting"), ("WBS", "CBS"),
 ("OBS", "RAM"), ("risk register", "issue log"),
 ("EOT claim", "acceleration claim"), ("prolongation", "disruption"),
 ("NEC4", "FIDIC"), ("lump sum", "reimbursable"),
 ("earned schedule", "SPI"), ("percent complete", "physical percent complete"),
 ("level 3 schedule", "level 4 schedule"), ("S-curve", "banana curve"),
 ("leading indicators", "lagging indicators"), ("KPI", "PI"),
 ("dashboard", "report"), ("PMO", "project controls team"),
 ("planner", "scheduler"), ("cost engineer", "quantity surveyor"),
 ("estimator", "cost engineer"), ("project accountant", "cost controller"),
 ("agile", "waterfall"), ("scrum", "kanban"),
 ("story points", "man-hours"), ("velocity", "SPI"),
 ("MSP baseline", "P6 baseline"), ("XER", "XML exchange"),
 ("Monte Carlo", "three-point estimating"), ("P50", "P80"),
 ("EMV", "contingency"), ("risk appetite", "risk tolerance"),
]


# ---------------------------------------------------------------- expansion
# The independent audit's remedy for scale is more genuine topics, not more
# angles per topic. These are real, distinct concepts practitioners search for.
TERMS += [
 # Scheduling depth
 ("schedule density", "Scheduling & WBS", "metric"),
 ("activity duration distribution", "Scheduling & WBS", "concept"),
 ("open ends in a schedule", "Scheduling & WBS", "concept"),
 ("dangling logic", "Scheduling & WBS", "concept"),
 ("redundant logic", "Scheduling & WBS", "concept"),
 ("schedule margin", "Scheduling & WBS", "concept"),
 ("driving path analysis", "Scheduling & WBS", "process"),
 ("longest path vs critical path", "Scheduling & WBS", "concept"),
 ("multi-calendar float distortion", "Scheduling & WBS", "concept"),
 ("resource-constrained critical path", "Scheduling & WBS", "concept"),
 ("schedule acceleration modelling", "Scheduling & WBS", "process"),
 ("bid schedule vs execution schedule", "Scheduling & WBS", "concept"),
 ("engineering deliverable register", "Scheduling & WBS", "doc"),
 ("procurement milestone linkage", "Scheduling & WBS", "concept"),
 ("construction work areas and zones", "Scheduling & WBS", "concept"),
 ("schedule integration across contractors", "Scheduling & WBS", "process"),
 ("interface float", "Scheduling & WBS", "concept"),
 ("early warning indicators in schedules", "Scheduling & WBS", "concept"),
 ("planning package conversion", "Scheduling & WBS", "process"),
 ("schedule reserve release", "Scheduling & WBS", "process"),
 # Cost depth
 ("cost account structure", "Cost & Estimating", "concept"),
 ("estimate reconciliation", "Cost & Estimating", "process"),
 ("bottoms-up validation", "Cost & Estimating", "process"),
 ("cost trending analysis", "Cost & Estimating", "process"),
 ("unit cost tracking", "Cost & Estimating", "process"),
 ("labour productivity index", "Cost & Estimating", "metric"),
 ("burn rate", "Cost & Estimating", "metric"),
 ("run rate forecasting", "Cost & Estimating", "process"),
 ("committed vs uncommitted budget", "Cost & Estimating", "concept"),
 ("cost risk register linkage", "Cost & Estimating", "process"),
 ("scope change pricing", "Cost & Estimating", "process"),
 ("rate build-up", "Cost & Estimating", "process"),
 ("all-in labour rate", "Cost & Estimating", "metric"),
 ("equipment utilisation costing", "Cost & Estimating", "process"),
 ("temporary works costing", "Cost & Estimating", "concept"),
 ("site establishment costs", "Cost & Estimating", "concept"),
 ("cost normalisation for benchmarking", "Cost & Estimating", "process"),
 ("capital efficiency ratio", "Cost & Estimating", "metric"),
 ("estimate contingency drawdown curve", "Cost & Estimating", "concept"),
 ("cost baseline change log", "Cost & Estimating", "doc"),
 # EVM depth
 ("earned value technique selection", "EVM & Performance", "process"),
 ("milestone weighting", "EVM & Performance", "concept"),
 ("weighted milestone method", "EVM & Performance", "process"),
 ("units complete method", "EVM & Performance", "process"),
 ("incremental milestone method", "EVM & Performance", "process"),
 ("earned hours", "EVM & Performance", "metric"),
 ("performance factor", "EVM & Performance", "metric"),
 ("composite CPI", "EVM & Performance", "metric"),
 ("cumulative vs periodic performance", "EVM & Performance", "concept"),
 ("baseline execution index", "EVM & Performance", "metric"),
 ("hit-miss ratio", "EVM & Performance", "metric"),
 ("EVM surveillance review", "EVM & Performance", "process"),
 ("over-target baseline (OTB)", "EVM & Performance", "concept"),
 ("single point adjustment", "EVM & Performance", "concept"),
 ("retroactive changes to EVM data", "EVM & Performance", "concept"),
 ("EVM data quality checks", "EVM & Performance", "process"),
 # Risk depth
 ("risk-adjusted contingency", "Risk", "metric"),
 ("cost risk driver analysis", "Risk", "process"),
 ("schedule risk driver analysis", "Risk", "process"),
 ("risk quantification workshops", "Risk", "process"),
 ("three-point estimates for risk", "Risk", "process"),
 ("triangular vs PERT distributions", "Risk", "concept"),
 ("confidence levels in forecasting", "Risk", "concept"),
 ("risk burn-down", "Risk", "metric"),
 ("emerging risk identification", "Risk", "process"),
 ("assumption and dependency log", "Risk", "doc"),
 ("threat vs opportunity registers", "Risk", "concept"),
 ("risk-based contingency release", "Risk", "process"),
 # Contracts depth
 ("contract baseline", "Contracts & Claims", "concept"),
 ("scope gap analysis", "Contracts & Claims", "process"),
 ("employer's requirements review", "Contracts & Claims", "process"),
 ("contractor's proposals", "Contracts & Claims", "doc"),
 ("programme submission and acceptance", "Contracts & Claims", "process"),
 ("rejected programme consequences", "Contracts & Claims", "concept"),
 ("quotation for compensation events", "Contracts & Claims", "process"),
 ("assessment of delay at the time", "Contracts & Claims", "concept"),
 ("contemporaneous records", "Contracts & Claims", "doc"),
 ("cause and effect analysis", "Contracts & Claims", "process"),
 ("float ownership clauses", "Contracts & Claims", "concept"),
 ("time at large", "Contracts & Claims", "concept"),
 ("prevention principle", "Contracts & Claims", "concept"),
 ("mitigation duty", "Contracts & Claims", "concept"),
 ("expert determination", "Contracts & Claims", "process"),
 # QS depth
 ("measurement conventions", "QS & Measurement", "concept"),
 ("rates analysis", "QS & Measurement", "process"),
 ("subcontract valuation", "QS & Measurement", "process"),
 ("materials on site valuation", "QS & Measurement", "concept"),
 ("variation quotations", "QS & Measurement", "doc"),
 ("contra charges", "QS & Measurement", "concept"),
 ("liquidated damages calculation", "QS & Measurement", "process"),
 ("cost reporting to the client", "QS & Measurement", "process"),
 ("cash flow forecast for a contractor", "QS & Measurement", "process"),
 ("tender adjudication", "QS & Measurement", "process"),
 # Procurement depth
 ("procurement schedule alignment", "Procurement", "process"),
 ("vendor data requirements", "Procurement", "doc"),
 ("purchase order tracking", "Procurement", "process"),
 ("free issue materials", "Procurement", "concept"),
 ("supplier expediting levels", "Procurement", "concept"),
 ("inspection and test plans", "Procurement", "doc"),
 ("shipping and customs milestones", "Procurement", "concept"),
 ("material requisition process", "Procurement", "process"),
 ("spares and commissioning materials", "Procurement", "concept"),
 ("framework agreements", "Procurement", "concept"),
 # Data & BI depth
 ("data dictionary for project reporting", "Data & BI", "doc"),
 ("automated variance commentary", "Data & BI", "process"),
 ("report refresh scheduling", "Data & BI", "process"),
 ("row-level security in dashboards", "Data & BI", "concept"),
 ("star schema for project data", "Data & BI", "concept"),
 ("data lineage", "Data & BI", "concept"),
 ("cost and schedule data integration", "Data & BI", "process"),
 ("exception reporting rules", "Data & BI", "concept"),
 ("naming conventions for project data", "Data & BI", "concept"),
 ("audit trails in reporting tools", "Data & BI", "concept"),
 # PMO depth
 ("portfolio capacity planning", "PMO & Governance", "process"),
 ("resource demand forecasting", "PMO & Governance", "process"),
 ("project prioritisation scoring", "PMO & Governance", "process"),
 ("investment committee reporting", "PMO & Governance", "process"),
 ("project health check", "PMO & Governance", "process"),
 ("assurance review gates", "PMO & Governance", "concept"),
 ("escalation thresholds", "PMO & Governance", "concept"),
 ("project closure report", "PMO & Governance", "doc"),
 ("knowledge transfer at handover", "PMO & Governance", "process"),
 ("controls governance framework", "PMO & Governance", "doc"),
 # Agile depth
 ("sprint burndown interpretation", "Agile & Hybrid", "metric"),
 ("release burnup", "Agile & Hybrid", "metric"),
 ("capacity planning in sprints", "Agile & Hybrid", "process"),
 ("epic and feature breakdown", "Agile & Hybrid", "concept"),
 ("agile estimation techniques", "Agile & Hybrid", "process"),
 ("cumulative flow diagram", "Agile & Hybrid", "concept"),
 ("work in progress limits", "Agile & Hybrid", "concept"),
 ("cycle time and lead time", "Agile & Hybrid", "metric"),
 ("agile governance reporting", "Agile & Hybrid", "process"),
 # Project finance depth
 ("funding drawdown forecast", "Project Finance", "process"),
 ("interest during construction", "Project Finance", "concept"),
 ("capital structure for projects", "Project Finance", "concept"),
 ("financial close", "Project Finance", "concept"),
 ("lender reporting requirements", "Project Finance", "process"),
 ("cost overrun facility", "Project Finance", "concept"),
 ("completion guarantees", "Project Finance", "concept"),
 ("independent engineer reports", "Project Finance", "doc"),
 ("project credit rating factors", "Project Finance", "concept"),
 # Turnarounds depth
 ("turnaround scope challenge", "Turnarounds & Ops", "process"),
 ("critical path in a shutdown", "Turnarounds & Ops", "concept"),
 ("shift planning for turnarounds", "Turnarounds & Ops", "process"),
 ("turnaround daily control room", "Turnarounds & Ops", "process"),
 ("post-turnaround review", "Turnarounds & Ops", "process"),
 ("turnaround contingency management", "Turnarounds & Ops", "process"),
 # PM fundamentals depth
 ("project execution plan", "PM Fundamentals", "doc"),
 ("responsibility matrix for controls", "PM Fundamentals", "doc"),
 ("controls staffing plan", "PM Fundamentals", "doc"),
 ("mobilisation planning", "PM Fundamentals", "process"),
 ("demobilisation planning", "PM Fundamentals", "process"),
 ("permit to work interfaces", "PM Fundamentals", "concept"),
 ("site instruction management", "PM Fundamentals", "process"),
 ("engineering change control", "PM Fundamentals", "process"),
 ("design freeze", "PM Fundamentals", "concept"),
 ("stage gate deliverables", "PM Fundamentals", "doc"),
 ("project controls plan", "PM Fundamentals", "doc"),
 ("owner vs contractor controls", "PM Fundamentals", "concept"),
 # Reporting depth
 ("variance threshold reporting", "Reporting & Dashboards", "process"),
 ("forecast accuracy tracking", "Reporting & Dashboards", "metric"),
 ("dashboard refresh discipline", "Reporting & Dashboards", "process"),
 ("commentary quality standards", "Reporting & Dashboards", "concept"),
 ("management by exception", "Reporting & Dashboards", "concept"),
 ("progress photo evidence", "Reporting & Dashboards", "doc"),
 # Budgeting depth
 ("annual operating plan for projects", "Budgeting & Cash Flow", "doc"),
 ("cash flow curve fitting", "Budgeting & Cash Flow", "process"),
 ("payment milestones negotiation", "Budgeting & Cash Flow", "process"),
 ("budget holder accountability", "Budgeting & Cash Flow", "concept"),
 ("cost centre allocation", "Budgeting & Cash Flow", "concept"),
 ("phasing capital across years", "Budgeting & Cash Flow", "process"),
 # Accounting depth
 ("contract asset recognition", "Project Accounting & IFRS", "concept"),
 ("cut-off procedures at period end", "Project Accounting & IFRS", "process"),
 ("intercompany project charges", "Project Accounting & IFRS", "concept"),
 ("cost capitalisation policy", "Project Accounting & IFRS", "doc"),
 ("impairment of project assets", "Project Accounting & IFRS", "concept"),
 ("percentage complete audit evidence", "Project Accounting & IFRS", "doc"),
]

FAQS += [
 "What is the difference between a programme and a project?",
 "What is the difference between a milestone and a deliverable?",
 "What is the difference between float and slack?",
 "What is the difference between a constraint and a dependency?",
 "What is the difference between a risk and an issue?",
 "What is the difference between a variation and a claim?",
 "What is the difference between direct and indirect costs?",
 "What is the difference between a budget and a baseline?",
 "What is the difference between planning and scheduling?",
 "What is the difference between progress and productivity?",
 "How do you know if a schedule is realistic?",
 "How do you check someone else's schedule quickly?",
 "How do you forecast when the data is bad?",
 "How do you report a project that is failing?",
 "How do you set a contingency you can defend?",
 "How do you build a cost report from scratch?",
 "How do you handle a scope change mid-project?",
 "How do you value work in progress fairly?",
 "How do you evidence a delay claim?",
 "How do you choose between EVM and simple progress tracking?",
 "When should project controls be mobilised on a project?",
 "How many planners does a project need?",
 "What does a good project controls plan contain?",
 "What should a project controls team report weekly?",
 "Who signs off a baseline change?",
 "What is the right level of schedule detail for a client report?",
 "How do you keep a schedule and a cost report aligned?",
 "What causes forecasts to be optimistic?",
 "How do you make a forecast credible to a CFO?",
 "What separates a good planner from a great one?",
]

STANDARDS_TOPICS += [
 "AACE 57R-09: integrated cost and schedule risk analysis using Monte Carlo",
 "AACE 52R-06: time impact analysis, as applied in construction",
 "AACE 25R-03: estimating lost labour productivity in construction claims",
 "AACE 45R-08: scheduling claims protection methods",
 "AACE 49R-06: identifying the critical path",
 "AACE 53R-06: schedule update review, as applied in engineering and construction",
 "AACE 14R-90: responsibility and required skills for a cost engineering practitioner",
 "PMI Practice Standard for Scheduling: what it asks of a planner",
 "PMI Practice Standard for Earned Value Management, in practice",
 "ISO 21508: earned value management in project and programme management",
 "ISO 21511: work breakdown structures for project and programme management",
 "BS 6079: the UK project management standard, explained",
 "The NEC4 Schedule of Cost Components, decoded",
 "JCT contracts and the programme: what is actually required",
 "The SCL Protocol vs AACE 29R-03: two views of delay analysis",
]

PROJECTS += [
 "the Thames Tideway Tunnel", "the Grand Paris Express", "Neom's Trojena",
 "the Jubail Industrial City programme", "the Doha Metro",
 "the Melbourne Metro Tunnel", "the Toronto Eglinton Crosstown",
 "the Copenhagen Cityringen", "the Follo Line project",
 "the Site C dam", "the Vogtle nuclear expansion", "the Dogger Bank wind farm",
]
