"""Research-agent seeds (Aug 2026, 31 searches) — curated into article briefs.
(title, cluster, format). Deduped against the generated bank automatically.
"""

EXTRA_SEEDS = [
 # Strategic / gap-claim (framed per the verified evidence)
 ("The three-way gap: why no certification combines project management, finance and AI", "Brand & Authority", "pillar"),
 ("AI project management certifications compared: PMI-CPMAI, APMG, Certiprof, GSDC — and PCL-AI", "Comparisons", "comparison"),
 ("AI finance credentials compared: CFA data science, AFP no-code AI — and where PFL-AI fits", "Comparisons", "comparison"),
 ("The 2026 CFA curriculum adds AI: what it means for finance careers", "AI & The Future", "guide"),
 ("ISO 21500 vs ISO 21502: which applies to you (and the misinformation to ignore)", "PMO & Governance", "guide"),
 # Competitor-observed themes (P6 / planning deep cuts)
 ("Negative float in Primavera P6: causes and fixes", "Scheduling & WBS", "how-to"),
 ("Hard vs soft constraints in Primavera P6", "Scheduling & WBS", "glossary"),
 ("What a Must Finish By date really does to your schedule", "Scheduling & WBS", "guide"),
 ("How total float is calculated in Primavera P6", "Scheduling & WBS", "how-to"),
 ("Schedule percent complete in P6: how each setting calculates", "Scheduling & WBS", "guide"),
 ("Planned value vs earned value under different P6 settings", "Scheduling & WBS", "guide"),
 ("Primavera P6 export file types explained: XER, XML, XLSX", "Data & BI", "glossary"),
 ("Cleaning POBS data: why your XER imports slowly and how to fix it", "Data & BI", "how-to"),
 ("Importing an XER from a newer P6 version", "Data & BI", "how-to"),
 ("Fixing budgeted cost changes on XER export/import", "Data & BI", "how-to"),
 ("Connecting Primavera P6 to Power BI: the complete pipeline", "Data & BI", "how-to"),
 ("Monitoring and controlling projects with Power BI and P6", "Data & BI", "guide"),
 ("Ten must-have P6 layouts and how to build them", "Tools & Software", "template"),
 ("Graphing a P6 resource S-curve in Excel", "Tools & Software", "how-to"),
 ("P6 layouts for baseline vs updated schedule comparison", "Tools & Software", "how-to"),
 ("Integrating Primavera P6 with ERP and document systems", "Data & BI", "guide"),
 ("The third-party Primavera tools ecosystem: viewers, checkers, analysers", "Tools & Software", "guide"),
 ("Recovery schedules: when the engineer demands one and how to build it", "Scheduling & WBS", "how-to"),
 ("Choosing a delay analysis technique: impacted-as-planned, windows, TIA, as-built-but-for", "Contracts & Claims", "comparison"),
 ("Why you cannot run cost control inside Primavera P6 alone", "Cost & Estimating", "guide"),
 ("Mini-schedules and agile integration at P6 activity level", "Agile & Hybrid", "guide"),
 ("Excessive float and vague activity names: schedule quality pitfalls", "Scheduling & WBS", "guide"),
 ("Activity codes vs WBS: the backbone of a reportable schedule", "Scheduling & WBS", "guide"),
 ("Linear scheduling and time-location views: when they beat Gantt", "Scheduling & WBS", "guide"),
 ("Schedule version comparison: diffing projects like a pro", "Data & BI", "how-to"),
 # Capital projects series (Mastt-style beginner spine)
 ("What are capital projects? The complete beginner's guide", "PM Fundamentals", "pillar"),
 ("The capital project management process, step by step", "PM Fundamentals", "process-guide"),
 ("Capital project portfolio management explained", "PMO & Governance", "guide"),
 ("Becoming a capital project manager: the route in", "Careers & Jobs", "guide"),
 ("The ultimate construction dashboard for capital projects", "Reporting & Dashboards", "guide"),
 ("The S-curve formula with a free calculator walkthrough", "Budgeting & Cash Flow", "how-to"),
 ("Construction cash flow spreadsheet: build it once, use it always", "Budgeting & Cash Flow", "template"),
 # EVM depth (Deltek/AACE-observed)
 ("Earned value reporting thresholds: when variances must trigger action", "EVM & Performance", "guide"),
 ("Using EVM to predict final project costs: the four EAC formulas", "EVM & Performance", "how-to"),
 ("EVM as management practice, not compliance theatre", "EVM & Performance", "guide"),
 ("Common misconceptions about earned value management", "EVM & Performance", "guide"),
 ("Level of effort on earned value (AACE 79R-13): the trap and the fix", "EVM & Performance", "guide"),
 ("Skills of an Earned Value Professional (AACE 81R-13) mapped to a career plan", "EVM & Performance", "guide"),
 ("Control accounts, work packages, planning packages (AACE 125R-22) in practice", "EVM & Performance", "guide"),
 ("Blockchain for project controls: signal or noise?", "AI & The Future", "guide"),
 ("Digital collaboration hubs for project controls teams", "AI & The Future", "guide"),
 ("Bridging project controls and project management: one team, two lenses", "PM Fundamentals", "guide"),
 ("Project controls in contract management: where the disciplines meet", "Contracts & Claims", "guide"),
 ("Risk analysis as a cost probability distribution: reading the curve", "Risk", "guide"),
 ("QRA capability: building quantitative risk analysis into the organisation", "Risk", "guide"),
 ("Scheduling and risk maturity: assessing where your organisation stands", "PMO & Governance", "guide"),
 ("Planning and scheduling with a safety focus", "Scheduling & WBS", "guide"),
 ("Construction scheduling methods compared: CPM, LOB, takt, agile", "Scheduling & WBS", "comparison"),
 # Standards spines (verified references)
 ("AACE 27R-03 schedule classification: matching schedules to project definition", "PMO & Governance", "guide"),
 ("AACE 37R-06 schedule levels: Level 1 to Level 5 and who uses each", "Scheduling & WBS", "guide"),
 ("The nine forensic delay methods of AACE 29R-03, mapped", "Contracts & Claims", "guide"),
 ("Observational vs modelled delay analysis: the 29R-03 taxonomy", "Contracts & Claims", "guide"),
 ("AACE 42R-08: contingency by parametric estimating", "Risk", "guide"),
 ("AACE 44R-08: contingency by expected value", "Risk", "guide"),
 ("AACE 113R-20: integrated cost and schedule risk analysis by parametric and expected value", "Risk", "guide"),
 ("AACE 119R-21: estimate accuracy ranges and contingency, decoded", "Cost & Estimating", "guide"),
 ("Cost engineering terminology (AACE 10S-90): the glossary that settles arguments", "Cost & Estimating", "guide"),
 ("EIA-748 Revision E: the EVMS guidelines streamlined from 32 to 27", "EVM & Performance", "guide"),
 ("The five EIA-748 guideline categories, explained with examples", "EVM & Performance", "guide"),
 ("When EIA-748 compliance is contractually required", "EVM & Performance", "guide"),
 ("NEC4 clause 60.1: the 21 compensation event grounds, grouped", "Contracts & Claims", "guide"),
 ("NEC4 disallowed cost under options C to F", "Contracts & Claims", "guide"),
 ("NEC4 clause 63 assessments and the early-warning penalty (63.7)", "Contracts & Claims", "guide"),
 ("FIDIC 2017 clause 20.2: the unified claims procedure", "Contracts & Claims", "guide"),
 ("FIDIC's 28-day time bar: the notice that decides claims", "Contracts & Claims", "guide"),
 ("FIDIC's 84-day fully detailed claim (20.2.4): building the submission", "Contracts & Claims", "how-to"),
 ("FIDIC 2017 clause 8.5: what qualifies for extension of time", "Contracts & Claims", "guide"),
 ("FIDIC Red vs Yellow Book 2017: design responsibility and claims", "Contracts & Claims", "comparison"),
 ("FIDIC 1999 vs 2017 claims regimes compared", "Contracts & Claims", "comparison"),
 ("IFRS 15 input vs output methods for measuring progress", "Project Accounting & IFRS", "guide"),
 ("Uninstalled materials under IFRS 15's input method", "Project Accounting & IFRS", "guide"),
 ("IFRS 15 vs IAS 11: what actually changed for construction", "Project Accounting & IFRS", "comparison"),
 ("Percentage of completion vs completed contract method", "Project Accounting & IFRS", "comparison"),
 ("IAS 23: specific vs general borrowings on capital projects", "Project Accounting & IFRS", "guide"),
 ("Contract assets and contract liabilities under IFRS 15", "Project Accounting & IFRS", "guide"),
 ("WIP journal entries on construction contracts: a walkthrough", "Project Accounting & IFRS", "how-to"),
 # PAA questions not already banked
 ("What industries pay project controls professionals the most?", "Careers & Jobs", "faq"),
 ("How do you get into project controls with no experience?", "Careers & Jobs", "faq"),
 ("Can project controls lead to programme management?", "Careers & Jobs", "faq"),
 ("Planning engineer vs project engineer: the difference", "Careers & Jobs", "faq"),
 ("Can a planning engineer become a project manager?", "Careers & Jobs", "faq"),
 ("What degree do you need to be a planning engineer?", "Careers & Jobs", "faq"),
 ("What is BCWS vs BCWP? (the old names for PV and EV)", "EVM & Performance", "faq"),
 ("What does a CPI below 1 mean (and what to do about it)?", "EVM & Performance", "faq"),
 ("When should you use bottom-up ETC?", "EVM & Performance", "faq"),
 ("What are the four EAC formulas and when does each apply?", "EVM & Performance", "faq"),
 ("What are the five levels of a work breakdown structure?", "Scheduling & WBS", "faq"),
 ("What is the 100% rule in WBS?", "Scheduling & WBS", "faq"),
 ("WBS vs project schedule: what is the difference?", "Scheduling & WBS", "faq"),
 ("How many levels should a WBS have?", "Scheduling & WBS", "faq"),
 ("Control account vs work package: the difference", "EVM & Performance", "faq"),
 ("What is three-point estimating?", "Cost & Estimating", "faq"),
 ("Cost overrun vs cost escalation: the difference", "Cost & Estimating", "faq"),
 ("What is a schedule of values?", "Budgeting & Cash Flow", "faq"),
 ("What is a construction draw schedule?", "Budgeting & Cash Flow", "faq"),
 ("Front-loaded vs back-loaded cash flow: what it signals", "Budgeting & Cash Flow", "faq"),
 ("Budget vs cash flow forecast: the difference", "Budgeting & Cash Flow", "faq"),
 ("Quantity surveyor vs civil engineer: which career?", "Careers & Jobs", "faq"),
 ("What does MRICS add to a quantity surveyor's salary?", "Careers & Jobs", "faq"),
 ("Is it worth hiring a quantity surveyor for a small project?", "QS & Measurement", "faq"),
 ("What KPIs belong on a project dashboard?", "Reporting & Dashboards", "faq"),
 ("What is generative scheduling?", "AI & The Future", "faq"),
 ("How accurate is AI construction cost estimating?", "AI & The Future", "faq"),
 ("Do project managers need to learn AI?", "AI & The Future", "faq"),
 ("What is PMI-CPMAI?", "AI & The Future", "faq"),
 ("XER vs XML in Primavera: which export to use?", "Data & BI", "faq"),
 ("What is EPC? What planners need to know about contract delivery models", "PM Fundamentals", "faq"),
 ("What is a recovery schedule?", "Scheduling & WBS", "faq"),
 ("How do you apply for an extension of time?", "Contracts & Claims", "faq"),
 ("Project controller vs project accountant: the difference", "Careers & Jobs", "faq"),
 # Jobs/market data-study seeds (source named in brief)
 ("Project management jobs growing 6% to 2034: inside the BLS outlook", "Careers & Jobs", "data-study"),
 ("Cost estimator jobs: declining headcount, 17,000 openings a year (BLS)", "Careers & Jobs", "data-study"),
 ("What project management specialists earn by US state and industry (BLS OES)", "Careers & Jobs", "data-study"),
 ("30 million new project professionals needed by 2035: the PMI talent gap", "Careers & Jobs", "data-study"),
 ("13 million project manager retirements by 2030: the succession problem", "Careers & Jobs", "data-study"),
 ("The PMP salary premium: what PMI's Earning Power survey shows", "Careers & Jobs", "data-study"),
 ("UK project salaries: what the APM market trends survey shows", "Careers & Jobs", "data-study"),
 ("Gulf salaries 2026: reading the Hays GCC salary guide as a controls professional", "Careers & Jobs", "data-study"),
 ("Saudi Arabia: the world's largest construction market by 2028", "Careers & Jobs", "data-study"),
 ("Saudisation and project careers: what the localisation push means for expats", "Careers & Jobs", "data-study"),
 ("Two-thirds of Gulf professionals already use AI at work: the skills signal", "AI & The Future", "data-study"),
 ("Quantity surveyor pay bands in the UAE: the Michael Page numbers", "Careers & Jobs", "data-study"),
 ("Global construction cost inflation: what Turner & Townsend's index shows", "Cost & Estimating", "data-study"),
 ("Labour availability: now the number-one construction cost driver", "Cost & Estimating", "data-study"),
 ("The most expensive cities to build in: the cost-per-m2 league table", "Cost & Estimating", "data-study"),
 ("The data centre boom as a project controls job engine", "Careers & Jobs", "data-study"),
 ("Giga-project workforces: NEOM, Diriyah and the hiring wave (with caveats)", "Careers & Jobs", "data-study"),
 ("US project controls salaries: energy, mining and utilities pay most", "Careers & Jobs", "data-study"),
]
