"""Keyword plan data — researched Aug 2026 (24 live SERP samples marked sampled=True).

Row: (keyword, cluster, intent, funnel, volume, difficulty, who_ranks, asset, priority, sampled)
Difficulty from SERP sampling + competition logic, NOT tool metrics — re-verify
quarterly in Search Console; the P1 set monthly.
"""

KEYWORDS = [
 ("project controls institute", "Brand", "Navigational", "BOFU", "Medium", "Hard",
  "projectcontrolsinstitute.com (the .com competitor) owns this SERP today",
  "Homepage + About + Organization schema — brand defense", "P1", True),
 ("PCL-AI certification", "Brand", "Navigational", "BOFU", "Low", "Easy",
  "Nobody — undefined SERP", "Landing page (define the product SERP before others do)", "P2", False),
 ("Certuvo", "Brand", "Navigational", "BOFU", "Low", "Easy",
  "Nobody — undefined SERP", "Certuvo homepage + cross-links", "P2", False),
 ("project controls certification", "Core", "Commercial", "MOFU", "High", "Hard",
  "APMG, Project Control Academy, EVMi (CPCP), projectcontrolsinstitute.com, SmartPM",
  "Pillar page (certification hub)", "P2", True),
 ("project controls training", "Core", "Commercial", "MOFU", "High", "Hard",
  "Project Control Academy, Plan Academy, GLOMACS, projectcontrolsinstitute.com",
  "Pillar page (training hub)", "P2", True),
 ("project controls course", "Core", "Commercial", "MOFU", "Medium", "Hard",
  "Same set as 'training' (PCA, Plan Academy, Class Central)", "Fold into training pillar", "P3", False),
 ("project controls certification online", "Core", "Transactional", "BOFU", "Medium", "Medium",
  "Class Central, APMG, PCA, EVMi, projectcontrolsinstitute.com", "Landing page (online delivery USP)", "P2", True),
 ("project controls course online", "Core", "Transactional", "BOFU", "Medium", "Medium",
  "Class Central, PCA, Plan Academy", "Same landing page", "P2", False),
 ("certified project controls professional", "Core", "Commercial", "BOFU", "Medium", "Medium",
  "EVMi (CPCP trademark), PCA, AACE", "Landing page (PCL-AI positioned against CPCP)", "P2", False),
 ("project controls certification cost", "Core", "Commercial", "BOFU", "Low", "Easy",
  "ccpstudy.com, AACE, scattered blogs", "FAQ block + pricing table on cert pages", "P2", False),
 ("project controls qualifications", "Core", "Commercial", "MOFU", "Low", "Medium",
  "ECITB, APM, Zippia, University of Cumbria", "Spoke article (UK-flavoured)", "P2", False),
 ("planning engineer certification", "Role", "Commercial", "BOFU", "Medium", "Medium",
  "O*NET, GAFM, apeng.org, gipmc.org, planningengineer.net — weak low-authority SERP",
  "Landing page (PCL-AI for planning engineers)", "P1", True),
 ("certified planning engineer", "Role", "Commercial", "BOFU", "Medium", "Medium",
  "GAFM, APEng, GIPMC, International Certification Centre", "Same landing page + FAQ block", "P2", False),
 ("how to become a planning engineer", "Role", "Informational", "TOFU", "Medium", "Medium",
  "Indeed, Zippia, ZipRecruiter, planningengineer.net", "Spoke article (career guide, cert CTA)", "P2", True),
 ("senior planning engineer career path", "Role", "Informational", "TOFU", "Medium", "Medium",
  "Job boards, Zippia", "Spoke article (progression ladder to PML-AI)", "P3", False),
 ("planning engineer salary", "Role", "Informational", "TOFU", "High", "Hard",
  "Glassdoor, Indeed, PayScale, GulfTalent", "Spoke / salary-by-region tool", "P3", False),
 ("cost controller certification", "Role", "Commercial", "BOFU", "Medium", "Easy",
  "ResumeCat, LinkedIn Pulse, Intl Certification Centre, AAIFM, PCA — thin SERP",
  "Landing page (cost-controller track)", "P1", True),
 ("cost engineer certification", "Role", "Commercial", "BOFU", "Medium", "Medium",
  "AACE (CCP/CCT), universeestimating.com, IMF Academy", "Landing page + AACE comparison link", "P2", False),
 ("project scheduler certification", "Role", "Commercial", "BOFU", "Medium", "Medium",
  "PMI (PMI-SP), AACE (PSP), Project Management Academy", "Landing page (scheduler track)", "P2", False),
 ("AACE PSP certification guide", "Conquest", "Commercial", "MOFU", "Medium", "Medium",
  "AACE, planningengineer.net, projectcontrolsinstitute.com", "Spoke guide (conquest, PCL-AI alternative)", "P2", False),
 ("quantity surveyor certification", "Role", "Commercial", "MOFU", "Medium", "Hard",
  "RICS, Novatr, Class Central, Alison", "Spoke ('QS to project controls' angle)", "P3", False),
 ("quantity surveyor certification online", "Role", "Commercial", "MOFU", "Medium", "Medium",
  "Novatr, Coursesity, Alison, quantitysurveyingcoach.com", "Spoke + cert CTA", "P3", True),
 ("PMO certification", "Role", "Commercial", "MOFU", "High", "Hard",
  "PMI (PMI-PMOCP), GSDC, The Digital PM, PMO Global Institute", "Spoke article (PMO leads angle)", "P3", True),
 ("what does a project controls engineer do", "Role", "Informational", "TOFU", "Medium", "Medium",
  "Zippia, Indeed, research.com", "Spoke article", "P3", False),
 ("how to become a project controls manager", "Role", "Informational", "TOFU", "Low", "Easy",
  "Thin — no dedicated authority page found", "Spoke article (to PML-AI)", "P2", False),
 ("project controls salary", "Role", "Informational", "TOFU", "Medium", "Medium",
  "Zippia, Glassdoor, Ladders", "Spoke / salary tool", "P3", False),
 ("what is project controls", "Skills", "Informational", "TOFU", "High", "Hard",
  "APM, Deltek, Mastt, KnowledgeHut, Asana, Wikipedia, Indeed", "Pillar page (definitive guide)", "P2", True),
 ("project controls vs project management", "Skills", "Informational", "TOFU", "Medium", "Easy",
  "Medium.com post, Mastt, LinkedIn Pulse, PCA, small blogs — weak SERP", "Comparison page", "P2", True),
 ("earned value management certification", "Skills", "Commercial", "MOFU", "Medium", "Medium",
  "EVMi (EVMP), Deltek, Caltech CTME, ScheduleReader, PCA", "Landing page (EVM module)", "P2", True),
 ("earned value management training", "Skills", "Commercial", "MOFU", "Medium", "Medium",
  "Same set + PMI CCRS", "Same landing + spoke", "P2", False),
 ("what is earned value management", "Skills", "Informational", "TOFU", "High", "Hard",
  "PMI, APM, Wrike, big PM blogs", "Spoke article", "P3", False),
 ("earned value formulas cheat sheet", "Skills", "Informational", "MOFU", "Medium", "Easy",
  "PMP-prep blogs, scattered PDFs", "Spoke + downloadable cheat sheet (lead magnet)", "P2", False),
 ("primavera p6 certification", "Skills", "Commercial", "MOFU", "High", "Hard",
  "The Knowledge Academy, Simpliaxis, Global PM, Taradigm", "Spoke guide ('do you need one?')", "P3", True),
 ("primavera p6 online course", "Skills", "Commercial", "MOFU", "High", "Hard",
  "Udemy, Plan Academy, Knowledge Academy", "Spoke (only if P6 content exists)", "P3", False),
 ("schedule risk analysis", "Skills", "Informational", "TOFU", "Medium", "Medium",
  "PNNL, Safran, PMI, SmartPM, Lumivero, Humphreys, iqrm.net", "Mini-pillar (curriculum tie-in)", "P2", True),
 ("quantitative schedule risk analysis QSRA", "Skills", "Informational", "TOFU", "Low", "Easy",
  "iqrm.net, Safran docs, small blogs", "Spoke article", "P2", False),
 ("cost control in construction", "Skills", "Informational", "TOFU", "Medium", "Hard",
  "Procore, CMU, Knowify, Matterport, DG Jones", "Spoke article (long game)", "P3", True),
 ("AI in project controls", "AI", "Informational", "TOFU", "Medium", "Easy",
  "paceglobal.org, TBH, PCA blog, PC Expo, LoadSpring, Proove — all blogs/vendors, no authority owner",
  "Pillar page (category-defining)", "P1", True),
 ("AI project controls certification", "AI", "Commercial", "BOFU", "Low", "Easy",
  "SERP GAP — nobody offers this by name", "Landing page (PCL-AI: the AI-era credential)", "P1", False),
 ("AI for construction scheduling", "AI", "Informational", "TOFU", "Medium", "Medium",
  "ALICE Technologies, CMiC, Archdesk, StruxHub", "Spoke article", "P2", True),
 ("AI in construction project management", "AI", "Informational", "TOFU", "Medium", "Hard",
  "Procore/Autodesk/CMiC-tier vendors", "Spoke article", "P3", False),
 ("will AI replace planning engineers", "AI", "Informational", "TOFU", "Low", "Easy",
  "coursiv.io, jobzonerisk.com, willrobotstakemyjob — very weak SERP",
  "Spoke + FAQ (anxiety magnet, email capture)", "P1", True),
 ("will AI replace project managers", "AI", "Informational", "TOFU", "High", "Hard",
  "Forbes-tier, PMI, big PM blogs", "Spoke article", "P3", False),
 ("AI project management certification", "AI", "Commercial", "MOFU", "Medium", "Hard",
  "Certiprof, APMG (AIPM), PMI (CPMAI), GSDC, The Digital PM", "Comparison page (roundup incl PCL-AI)", "P2", True),
 ("future of project controls", "AI", "Informational", "TOFU", "Low", "Easy",
  "projectcontrolsonline.com, PC Expo, PCA, Proove", "Spoke (annual thought-leadership report)", "P2", True),
 ("AI for cost estimating in construction", "AI", "Informational", "TOFU", "Low", "Easy",
  "Scattered vendor blogs", "Spoke article", "P2", False),
 ("best AI construction scheduling software", "AI", "Commercial", "MOFU", "Medium", "Medium",
  "ALICE, StruxHub, Archdesk listicles", "Comparison page (neutral roundup)", "P3", False),
 ("project controls courses in Dubai", "Geo", "Transactional", "BOFU", "Low", "Easy",
  "GLOMACS, Edarabia, LPC, Coursetakers, PetroKnowledge — mostly generic PM courses: intent gap",
  "Landing page (Dubai / UAE)", "P1", True),
 ("project controls training UAE", "Geo", "Transactional", "BOFU", "Low", "Easy",
  "Same set", "Same UAE landing page", "P2", False),
 ("planning engineer course in Saudi Arabia", "Geo", "Transactional", "BOFU", "Low", "Easy",
  "Knowledge Academy, Edarabia, GulfTalent — thin mixed-intent SERP", "Landing page (KSA, Vision 2030 angle)", "P2", True),
 ("project controls certification UK", "Geo", "Commercial", "MOFU", "Medium", "Medium",
  "ECITB/The CCM, APMG, University of Cumbria, Knowledge Academy", "Landing page (UK)", "P2", True),
 ("project controls certification USA", "Geo", "Commercial", "MOFU", "Low", "Medium",
  "AACE, Zippia, PCA — few geo-specific pages exist", "Landing page (US)", "P2", False),
 ("project controls course India", "Geo", "Commercial", "MOFU", "Medium", "Medium",
  "Knowledge Academy, NPTEL/IIT Madras (free), Class Central", "Landing page (India, vs free NPTEL)", "P2", True),
 ("primavera p6 course in Dubai", "Geo", "Transactional", "BOFU", "Low", "Easy",
  "Coursetakers, local training shops", "Spoke/landing hybrid", "P2", False),
 ("project controls courses in Qatar", "Geo", "Transactional", "BOFU", "Low", "Easy",
  "GLOMACS-tier local trainers, directories", "Landing page (Qatar)", "P3", False),
 ("planning engineer jobs in UAE", "Geo", "Informational", "TOFU", "High", "Hard",
  "GulfTalent, Bayt, Glassdoor, Indeed — job boards own it",
  "Spoke (career + salary guide, cert CTA) — don't chase the jobs SERP", "P3", True),
 ("planning engineer salary UAE", "Geo", "Informational", "TOFU", "Medium", "Medium",
  "Glassdoor, Bayt, GulfTalent", "Spoke / salary table", "P3", False),
 ("project controls jobs in Saudi Arabia", "Geo", "Informational", "TOFU", "Medium", "Hard",
  "Job boards, AtkinsRealis careers blog", "Spoke (KSA giga-projects career guide)", "P3", False),
 ("best project controls certification", "Comparison", "Commercial", "MOFU", "Medium", "Medium",
  "Zippia thin programmatic listicles x2, PCA, Class Central, EVMi — beatable",
  "Comparison page (AACE, PMI-SP, ECITB, PPC, PCL-AI — honest)", "P1", True),
 ("AACE CCP vs PMP", "Conquest", "Commercial", "MOFU", "Low", "Easy",
  "ccpstudy.com, dumps sites, Bayt forum threads — weak SERP", "Comparison page", "P2", True),
 ("PMI-SP vs AACE PSP", "Conquest", "Commercial", "MOFU", "Low", "Easy",
  "planningengineer.net, forums", "Comparison page", "P2", False),
 ("PMI-SP worth it", "Conquest", "Commercial", "MOFU", "Low", "Easy",
  "projectmanagement.com forum thread ranks #1 — opportunity", "Spoke + FAQ block", "P2", True),
 ("AACE certification cost", "Conquest", "Commercial", "MOFU", "Medium", "Easy",
  "ccpstudy.com (one solo niche site dominates), dumpsgate, IMF Academy",
  "Comparison page (all-certs cost table incl PCI pricing)", "P1", True),
 ("CCP certification worth it", "Conquest", "Commercial", "MOFU", "Low", "Easy",
  "ccpstudy.com, forums", "FAQ block on comparison page", "P3", False),
 ("best certification for planning engineers", "Comparison", "Commercial", "MOFU", "Low", "Easy",
  "Thin — Zippia-tier only", "Comparison page variant", "P2", False),
 ("project controls exam questions", "Exam prep", "Transactional", "BOFU", "Low", "Easy",
  "SERP GAP — results bleed to PMP prep; no dedicated question bank ranks",
  "Free Certuvo practice-question bank landing", "P1", True),
 ("planning engineer interview questions", "Exam prep", "Informational", "TOFU", "High", "Medium",
  "Indeed, Betterteam, ProjectPractical, planningengineer.net", "Spoke + Q&A pack (Certuvo lead magnet)", "P2", True),
 ("project controls interview questions", "Exam prep", "Informational", "TOFU", "Medium", "Easy",
  "climbtheladder.com, perfectinterview.ai — thin", "Spoke article", "P2", False),
 ("primavera p6 practice test", "Exam prep", "Transactional", "BOFU", "Medium", "Easy",
  "Multisoft, KnowledgeHut, Quizlet decks, dumps sites — thin/low-quality",
  "Free interactive P6 quiz on Certuvo", "P2", True),
 ("earned value practice questions", "Exam prep", "Transactional", "BOFU", "Low", "Easy",
  "PMP-prep sites only", "EVM quiz + formula drills", "P2", False),
 ("CCP exam questions", "Exam prep", "Transactional", "BOFU", "Medium", "Easy",
  "ccpstudy.com, Udemy, dumps sites", "Certuvo CCP-style practice bank (legit prep, not dumps)", "P2", False),
 ("PMI-SP exam prep", "Exam prep", "Commercial", "BOFU", "Low", "Medium",
  "Project Management Academy, Elite Minds", "Spoke + Certuvo module", "P3", False),
 ("honorary fellowship engineering", "Honorary", "Informational", "TOFU", "Low", "Medium",
  "RAEng, ICE, IMechE, IET, Imperial — institutional pages, none 'sell' a programme",
  "Landing page (honorary certification, fellowship-searcher angle)", "P3", True),
 ("how to become a fellow of a professional institution", "Honorary", "Informational", "MOFU", "Low", "Easy",
  "IET forum threads, LinkedIn posts — thin", "Spoke guide (fellowship application CTA)", "P2", False),
 ("professional fellowship application", "Honorary", "Informational", "MOFU", "Low", "Easy",
  "Universities, mixed institutional pages", "Landing + application guide", "P3", False),
 ("fellowship for project professionals", "Honorary", "Commercial", "BOFU", "Low", "Easy",
  "Effectively nobody (APM Fellowship closest)", "Fellowship landing page variant", "P3", False),
]

P1_WHY = [
 ("project controls institute", "Brand defense: the .com competitor owns your exact name today — you cannot build a certification brand while another PCI outranks you for it."),
 ("planning engineer certification", "BOFU commercial term where only low-authority cert mills rank; the largest single role in the Gulf-heavy audience."),
 ("cost controller certification", "Thin SERP (resume blogs + obscure issuers), direct product match, winnable in months."),
 ("AI project controls certification", "A true SERP gap: nobody has named this category and it is literally the product (PCL-AI). Define it before someone else does."),
 ("AI in project controls", "The differentiator pillar; only vendor blogs rank, no authority owner; every AI spoke feeds it internal links."),
 ("will AI replace planning engineers", "Easy question SERP (auto-generated career sites); taps the exact anxiety the AI-era curriculum answers; strong email-capture page."),
 ("best project controls certification", "Zippia's thin programmatic listicles are beatable with a genuinely expert, honest comparison; highest-leverage MOFU asset."),
 ("AACE certification cost", "One solo niche site dominates; a full cost-comparison table conquests AACE-intent traffic at its decision moment."),
 ("project controls exam questions", "SERP gap (results bleed to PMP prep); a free Certuvo question bank ranks fast and feeds the funnel."),
 ("project controls courses in Dubai", "Gulf commercial intent served today by generic PM-course directories, not project-controls pages; a dedicated Dubai landing page closes the gap."),
]
