namespace PCI.Backend.Data;

/// <summary>
/// First-run content for the table-backed public sections (FAQ accordion, Body-of-Knowledge
/// domains, governance roles, policy/document lists, header &amp; footer navigation) — extracted
/// verbatim from the shipped pages, so a fresh database renders the site exactly as designed.
/// Each table is seeded ONLY when empty: operator edits and deletions are never overwritten
/// or resurrected by a restart or redeploy. Generated by scratchpad/regen-seeds.py.
/// </summary>
public static class SeedContent
{
    public static void Run(Db db)
    {
        void IfEmpty(string table, Action fill)
        {
            try { if (db.Scalar<long>($"SELECT COUNT(*) FROM `{table}`") == 0) { db.Transaction(fill); Console.WriteLine($"[seed] {table}: initial content loaded"); } }
            catch (Exception e) { Console.Error.WriteLine($"[seed] {table} skipped: {e.Message}"); }
        }
        IfEmpty("faqs", () => { var n = 0; foreach (var r in Faqs) db.Execute("INSERT INTO faqs(question,answer,category,sort_order,published) VALUES(?,?,?,?,1)", r[0], r[1], r[2], ++n); });
        void SeedBok() { var n = 0; foreach (var r in Bok) db.Execute("INSERT INTO bok_domains(code,name,weight,description,bullets,sort_order) VALUES(?,?,?,?,?,?)", r[0], r[2], r[1] is string w ? (object)long.Parse(w) : null, r[3], r[4], ++n); }
        IfEmpty("bok_domains", SeedBok);
        // Upgrade path: databases seeded before the thirteen-domain PCP-AI BoK still carry the original
        // eight-domain set. If (and only if) the table is byte-for-byte that untouched old seed, replace it
        // with the current one; any operator-edited table is left alone.
        try
        {
            var oldSeed = db.Scalar<long>("SELECT COUNT(*) FROM bok_domains") == 8
                       && db.Scalar<long>("SELECT COUNT(*) FROM bok_domains WHERE name IN ('Project Controls Foundations & Governance','Planning & Scheduling','Cost Estimating & Control','Earned Value & Performance Management','Risk & Contingency Management','Change & Configuration Management','Data, Reporting & Analytics','Governed AI in Project Controls')") == 8;
            if (oldSeed) { db.Transaction(() => { db.Execute("DELETE FROM bok_domains"); SeedBok(); }); Console.WriteLine("[seed] bok_domains: upgraded to the thirteen-domain PCL-AI set"); }
        }
        catch (Exception e) { Console.Error.WriteLine($"[seed] bok_domains upgrade skipped: {e.Message}"); }
        IfEmpty("governance_roles", () => { var n = 0; foreach (var r in Roles) db.Execute("INSERT INTO governance_roles(role,holder,status,remit,sort_order) VALUES(?,NULL,'open',?,?)", r[0], r[1], ++n); });
        IfEmpty("resources", () => { var n = 0; foreach (var r in Docs) db.Execute("INSERT INTO resources(title,category,doc_type,url,description,published,sort_order) VALUES(?,?,'Page',?,?,1,?)", r[0], r[1], r[2], r[3], ++n); });
        IfEmpty("nav_items", () => { var n = 0; foreach (var r in Nav) db.Execute("INSERT INTO nav_items(label,url,nav_group,sort_order,visible) VALUES(?,?,?,?,1)", r[0], r[1], r[2], ++n); });
        // The three access routes live under the Membership nav group. Add them idempotently on every boot
        // (AFTER the IfEmpty bulk seed) so databases seeded before the routes existed pick them up too —
        // the bulk seed only runs on an empty table. WHERE NOT EXISTS keeps it a no-op once present.
        try
        {
            foreach (var (lbl, url, so) in new[] { ("Standard route", "route-standard.html", 1), ("Founding route", "route-founding.html", 2), ("Honorary route", "route-honorary.html", 3) })
                db.Execute("INSERT INTO nav_items(label,url,nav_group,sort_order,visible) SELECT ?,?, 'Membership', ?, 1 WHERE NOT EXISTS(SELECT 1 FROM nav_items WHERE url=? AND nav_group='Membership')", lbl, url, so, url);
        }
        catch (Exception e) { Console.Error.WriteLine($"[seed] membership routes skipped: {e.Message}"); }
        // Training Partner pages (Phase 7) — added idempotently under the Organisations footer group.
        try
        {
            foreach (var (lbl, url, so) in new[] { ("Training Partners", "training-partners.html", 8), ("Become a Training Partner", "become-a-training-partner.html", 9) })
                db.Execute("INSERT INTO nav_items(label,url,nav_group,sort_order,visible) SELECT ?,?, 'Organisations', ?, 1 WHERE NOT EXISTS(SELECT 1 FROM nav_items WHERE url=? AND nav_group='Organisations')", lbl, url, so, url);
        }
        catch (Exception e) { Console.Error.WriteLine($"[seed] training partner nav skipped: {e.Message}"); }
        // Multi-certification (Phase 2): point the header "Certifications" menu at the DB-driven catalogue
        // hub, and list every credential in the footer "Certifications" group. Conditional on the old
        // default URL so an operator who re-points a link keeps their choice (no clobbering on reboot).
        try
        {
            db.Execute("UPDATE nav_items SET url='/certifications' WHERE nav_group='Header' AND label='Certifications' AND url='certification.html'");
            // Content Centre: expose the News vertical (/news) in the header nav (idempotent; admin can move it).
            db.Execute("INSERT INTO nav_items(label,url,nav_group,sort_order,visible) SELECT 'News','/news','Header',40,1 WHERE NOT EXISTS(SELECT 1 FROM nav_items WHERE url='/news')");
            // Final Project Leadership Suite credentials in the footer "Certifications" group.
            foreach (var (lbl, url, so) in new[] { ("PCI PCL-AI", "/certifications/pcl-ai", 20), ("PCI PFL-AI", "/certifications/pfl-ai", 21), ("PCI PML-AI", "/certifications/pml-ai", 22), ("All certifications", "/certifications", 23) })
                db.Execute("INSERT INTO nav_items(label,url,nav_group,sort_order,visible) SELECT ?,?, 'Certifications', ?, 1 WHERE NOT EXISTS(SELECT 1 FROM nav_items WHERE url=? AND nav_group='Certifications')", lbl, url, so, url);
            // Migrate any earlier (temporary) credential nav rows to the final slugs + designations.
            foreach (var (oldUrl, newUrl, newLbl) in new[] {
                ("/certifications/pcp-ai", "/certifications/pcl-ai", "PCI PCL-AI"),
                ("/certifications/pfip", "/certifications/pfl-ai", "PCI PFL-AI"),
                ("/certifications/cpmd", "/certifications/pml-ai", "PCI PML-AI"),
                ("/certifications/cpmd-ai", "/certifications/pml-ai", "PCI PML-AI"),
                ("/certifications/pdl-ai", "/certifications/pml-ai", "PCI PML-AI") })
                db.Execute("UPDATE nav_items SET url=?, label=? WHERE nav_group='Certifications' AND url=?", newUrl, newLbl, oldUrl);
            // Replace the retired acronym in any nav label (e.g. "PMP vs AACE vs PCP-AI") across every group.
            db.Execute("UPDATE nav_items SET label=REPLACE(label,'PCP-AI','PCL-AI') WHERE label LIKE '%PCP-AI%'");
            // The comparison article moved with the acronym rename; keep any old nav row pointing at it.
            db.Execute("UPDATE nav_items SET url='pmp-vs-aace-vs-pcl-ai.html' WHERE url='pmp-vs-aace-vs-pcp-ai.html'");
            // Deterministic order for the Certifications menu: the suite first (All → PCL → PFL → PML),
            // then the journey pages. Existing rows kept their pre-suite sort_orders, which interleaved
            // the three credentials oddly mid-menu; this pins the canonical order on every boot (keyed
            // by URL, so renamed labels stay put and admin-added rows sort after by their own order).
            foreach (var (url, so) in new (string, int)[] {
                ("/certifications", 1), ("/certifications/pcl-ai", 2), ("/certifications/pfl-ai", 3), ("/certifications/pml-ai", 4),
                ("certification-roadmap.html", 5), ("eligibility-requirements.html", 6), ("exam-structure.html", 7),
                ("body-of-knowledge.html", 8), ("sample-questions.html", 9), ("cert-policies.html", 10),
                ("recert.html", 11), ("digital-credentials.html", 12), ("ai-cert.html", 13),
                ("book.html", 14), ("enrol.html", 15) })
                db.Execute("UPDATE nav_items SET sort_order=? WHERE nav_group='Certifications' AND url=?", so, url);
            // 301 for the renamed article path so the old URL keeps its SEO value.
            db.Execute("INSERT OR IGNORE INTO seo_redirects(from_path,to_url,status,active,note) VALUES('/pmp-vs-aace-vs-pcp-ai.html','/pmp-vs-aace-vs-pcl-ai.html',301,1,'Master Naming Update')");
            // Preserve every retired third-certification URL as a single-hop permanent redirect.
            foreach (var oldPath in new[] { "/certifications/cpmd", "/certifications/cpmd-ai", "/certifications/pdl-ai" })
                db.Execute("INSERT OR IGNORE INTO seo_redirects(from_path,to_url,status,active,note) VALUES(?, '/certifications/pml-ai', 301, 1, 'PML-AI naming migration')", oldPath);
            // Public Downloads Centre: a top-level header link, placed just after Resources (ties break by id
            // so it sorts immediately after). Idempotent — inserted once, then left for an operator to move.
            db.Execute("INSERT INTO nav_items(label,url,nav_group,sort_order,visible) SELECT 'Downloads','/downloads','Header', COALESCE((SELECT sort_order FROM nav_items WHERE nav_group='Header' AND label='Resources'),90), 1 WHERE NOT EXISTS(SELECT 1 FROM nav_items WHERE nav_group='Header' AND url='/downloads')");
            // …and in the footer "Resources" column, next to the existing Guidelines & Downloads link.
            db.Execute("INSERT INTO nav_items(label,url,nav_group,sort_order,visible) SELECT 'Downloads Centre','/downloads','Resources', COALESCE((SELECT sort_order FROM nav_items WHERE nav_group='Resources' AND url='downloads.html'),1), 1 WHERE NOT EXISTS(SELECT 1 FROM nav_items WHERE nav_group='Resources' AND url='/downloads')");
        }
        catch (Exception e) { Console.Error.WriteLine($"[seed] certification nav skipped: {e.Message}"); }
        // Master Naming Update: databases seeded before the Project Leadership Suite still carry the
        // retired names inside admin-editable content (FAQs, resource descriptions). Rewrite in place —
        // long names first so the bare acronym replace never mangles them; a no-op once clean.
        try
        {
            foreach (var tc in new[] { ("faqs", "question"), ("faqs", "answer"), ("resources", "description"), ("resources", "title") })
            {
                db.Execute($"UPDATE {tc.Item1} SET {tc.Item2}=REPLACE({tc.Item2},'Certified Project Controls Professional — AI (PCP-AI)','PCI AI Project Controls Leader (PCI PCL-AI)') WHERE {tc.Item2} LIKE '%Certified Project Controls Professional%'");
                db.Execute($"UPDATE {tc.Item1} SET {tc.Item2}=REPLACE({tc.Item2},'Certified Project Controls Professional','PCI AI Project Controls Leader') WHERE {tc.Item2} LIKE '%Certified Project Controls Professional%'");
                db.Execute($"UPDATE {tc.Item1} SET {tc.Item2}=REPLACE({tc.Item2},'PCP-AI','PCL-AI') WHERE {tc.Item2} LIKE '%PCP-AI%'");
            }
        }
        catch (Exception e) { Console.Error.WriteLine($"[seed] naming upgrade skipped: {e.Message}"); }
    }

    static readonly object?[][] Faqs =
    {
        new object?[]{ @"What is the PCI PCL-AI credential?", @"<p>The PCI AI Project Controls Leader (PCI PCL-AI) is a rigorous credential covering project controls, cost engineering, forecasting and performance — with the governed use of artificial intelligence treated as part of the discipline. It is part of the PCI AI Project Leadership Certification Suite, awarded by the Project Controls Institute and built with reference to <a href=""accreditation-status.html"">ISO/IEC 17024</a> personnel-certification principles.</p>", @"The credential" },
        new object?[]{ @"Who is the PCI PCL-AI for?", @"<p>It is for the people who hold major projects to plan, cost and cash flow: planners, schedulers, cost engineers, project-controls and PMO professionals, and project-finance specialists across construction, energy, infrastructure and software.</p>", @"The credential" },
        new object?[]{ @"Is the PCI PCL-AI accredited?", @"<p>PCI is an independent independent certifying body. Our examinations are being developed with reference to ISO/IEC 17024. We describe our status honestly at every stage and make no claims beyond what is true today.</p>", @"The credential" },
        new object?[]{ @"How do I qualify to sit the exam?", @"<p>There are two routes: an experience route for practitioners with relevant project-controls experience, and a foundation route for those newer to the field. Full <a href=""eligibility-requirements.html"">eligibility</a> criteria are confirmed during enrolment.</p>", @"Exam & enrolment" },
        new object?[]{ @"What does the examination involve?", @"<p>The exam tests applied judgement rather than recall: scenario-based multiple-choice questions across the ten sections (93 Knowledge Areas), including the governed use of AI. It is proctored, online or at a test centre.</p>", @"Exam & enrolment" },
        new object?[]{ @"How is the credential maintained?", @"<p>PCI credentials run on a three-year continuing-professional-development (CPD) cycle. Membership keeps your credential current and tracks your CPD.</p>", @"Exam & enrolment" },
        new object?[]{ @"How much does it cost?", @"<p>Fees for the inaugural cohort are confirmed at enrolment. Members receive reduced rates on examinations and events.</p>", @"Exam & enrolment" },
        new object?[]{ @"Why is AI part of a project-controls credential?", @"<p>Because AI is already in the toolkit. Each PCI credential assesses the applied, governed use of AI across forecasting, risk and reporting — not generic AI literacy. Every output a certified professional relies on must be explainable, validated and owned by a competent human. In short: AI proposes; the professional disposes.</p>", @"The AI standard" },
        new object?[]{ @"What does membership include?", @"<p>Membership provides <a href=""recert.html"">recertification</a> and CPD tracking, a verifiable digital credential designed for recognition by employers, body-of-knowledge and AI-practice updates, and member rates on examinations and events.</p>", @"Membership & employers" },
        new object?[]{ @"Can my organisation certify a whole team?", @"<p>Yes. Employers can upskill an existing function or build a new project-controls capability to one benchmarked standard. <a href=""employers.html"">Read more for employers</a> or <a href=""contact.html"">contact us</a> about team enrolment.</p>", @"Membership & employers" },
        new object?[]{ @"Does PCI also sell exam preparation?", @"<p>No. PCI develops and owns the standard and the examination. Preparation and training are provided separately by Certuvo, our official partner. This separation supports the <a href=""impartiality-policy.html"">impartiality</a> expected of a body developed with reference to ISO/IEC 17024 personnel-certification principles.</p>", @"Independence & verification" },
        new object?[]{ @"How can I verify someone's credential?", @"<p>Use the credential lookup on the <a href=""verify.html"">Verify page</a> to confirm a professional's PCI credential status.</p>", @"Independence & verification" },
    };

    // The PCP-AI BoK: three weighted groups (40/40/20) over thirteen domains — mirrors docs/bok.
    // Rows are {code, weight, name, description, bullets}; a row with no code is a group header
    // (its weight is the group percentage) and a row with a code (D1..D13) is a domain card.
    static readonly object?[][] Bok =
    {
        new object?[]{ null, @"40", @"Project accounting & finance", @"Domains 1–4 · the financial grammar of project controls.", null },
        new object?[]{ @"D1", null, @"Foundations of Accounting for Project Controls", @"The double-entry model, the financial statements, accruals and project cost coding.", @"Apply the accounting equation and double-entry mechanics
Build and read the four financial statements
Run accruals, provisions and project cost coding" },
        new object?[]{ @"D2", null, @"Financial Reporting & the Standards", @"Revenue from contracts (IFRS 15 at its heart) and the standards that shape project numbers.", @"Apply the five-step revenue model to project contracts
Account for contract assets, liabilities and onerous contracts
Bridge management reporting and statutory reporting" },
        new object?[]{ @"D3", null, @"Budgeting & Forecasting", @"Estimates, baselines, forecasts and project cash flow.", @"Build classed estimates and time-phased budgets
Forecast EAC top-down and bottom-up, with a governed change log
Model project cash flow, funding and indirect taxes" },
        new object?[]{ @"D4", null, @"Performance, Variance & Reporting", @"Turning numbers into decisions — variances, KPIs and reporting.", @"Decompose variances with flexed budgets and bridges
Design KPI systems with data-derived thresholds
Report by exception to the decision each audience must take" },
        new object?[]{ null, @"40", @"Project management principles", @"Domains 5–12 · the delivery disciplines controls serves.", null },
        new object?[]{ @"D5", null, @"Cost Management & Cost Control", @"The cost engine: commitments, accruals, actuals and control accounts.", @"Run the commitment → accrual → actual cycle
Structure control accounts with work authorisation
Track quantities, trends and the true cost exposure" },
        new object?[]{ @"D6", null, @"Earned Value Management & Forecasting", @"The flagship: EV, indices and defensible forecasts.", @"Measure EV with sound earning rules and the productivity factor
Select and defend the EAC method, not just compute it
Apply earned schedule and credibility tests to recovery claims" },
        new object?[]{ @"D7", null, @"Contracts & Commercial Management", @"Contract types, variations, claims, BoQ and the billing cycle.", @"Work the risk-allocation spectrum from lump sum to MDMH rates
Manage variations, claims, LDs, retention and securities
Run BoQ measurement, certificates and the revenue loop" },
        new object?[]{ @"D8", null, @"Project Management Lifecycle", @"Initiating to closing — gates, benefits and governance.", @"Operate stage gates on evidence, pricing decision latency
Manage stakeholders and communication as a controls discipline
Close projects with completions, final accounts and lessons" },
        new object?[]{ @"D9", null, @"Agile & Adaptive Delivery", @"Scrum, Kanban, flow metrics and AgileEVM for controls.", @"Measure velocity, flow and cycle time honestly
Apply AgileEVM and reconcile story points to % complete
Govern hybrid delivery through gates without breaking flow" },
        new object?[]{ @"D10", null, @"Project Scheduling", @"CPM in full — networks, float, compression and delay.", @"Run forward and backward passes, float and the critical path
Compress with crash economics, drag and resource limits
Progress schedules and analyse delay defensibly" },
        new object?[]{ @"D11", null, @"Business Process Cycles", @"O2C, P2P, time-and-expense and the control environment.", @"Operate three-way match, SoD and the audit trail
Read process mining and continuous monitoring output
Manage working capital: DSO, DPO, DIO and the cash cycle" },
        new object?[]{ @"D12", null, @"Risk Management", @"Uncertainty quantified — registers, contingency and appetite.", @"Quantify risk with EMV, decision trees and Monte Carlo
Set and govern contingency against P-levels and appetite
Manage correlation, draw-down and opportunity" },
        new object?[]{ null, @"20", @"AI knowledge & practical approach", @"Domain 13 · governed AI across the controls lifecycle.", null },
        new object?[]{ @"D13", null, @"AI for Project Controls & PM", @"Concepts, data, prompting, tools, applied workflows, governance and capability — the governed use of AI across the whole controls lifecycle.", @"Apply AI to estimating, forecasting, scheduling, commercial and reporting workflows
Evaluate outputs with golden sets, precision/recall and priced review steps
Govern models, data and accountability — AI proposes, the professional disposes" },
    };

    static readonly object?[][] Roles =
    {
        new object?[]{ @"Responsible Officer", @"Accountable for the Institute’s operations, integrity and adherence to its own policies." },
        new object?[]{ @"Chief Examiner / Assessment Lead", @"Owns examination validity, the blueprint and the standard-setting that fixes the pass mark." },
        new object?[]{ @"Certification & Impartiality Committee", @"Independent-majority body that safeguards impartial certification decisions and manages threats to impartiality." },
        new object?[]{ @"Standards Committee", @"Owns the competency standard and the <a href=""body-of-knowledge.html"">Body of Knowledge</a>, and oversees its validation." },
        new object?[]{ @"Appeals Panel", @"Provides independent review of certification and examination decisions under the <a href=""appeals.html"">Appeals Policy</a>." },
        new object?[]{ @"Subject-Matter Experts", @"Practising experts who author and peer-review the standard and the examination items." },
    };

    static readonly object?[][] Docs =
    {
        new object?[]{ @"Terms of Enrolment", @"Enrolment & payment", @"terms-of-enrollment.html", @"What enrolment provides and the conditions that apply" },
        new object?[]{ @"Refund & Cancellation Policy", @"Enrolment & payment", @"refund-policy.html", @"Refund eligibility and how to request one" },
        new object?[]{ @"Privacy Policy", @"Enrolment & payment", @"privacy.html", @"How we handle your personal data" },
        new object?[]{ @"Cookie Policy", @"Enrolment & payment", @"cookie-policy.html", @"Cookies used on this site" },
        new object?[]{ @"Data Protection Policy", @"Enrolment & payment", @"data-protection-policy.html", @"Our data-protection commitments" },
        new object?[]{ @"Exam Structure", @"Examination", @"exam-structure.html", @"Format, domains and weighting of the PCI certification exams" },
        new object?[]{ @"Examination Rules", @"Examination", @"exam-rules.html", @"Conduct and rules on exam day" },
        new object?[]{ @"Certification Policies", @"Examination", @"cert-policies.html", @"How certification decisions are made" },
        new object?[]{ @"Eligibility Requirements", @"Examination", @"eligibility-requirements.html", @"Who can sit the exam" },
        new object?[]{ @"Candidate Handbook", @"Examination", @"handbook.html", @"Your end-to-end guide to certification" },
        new object?[]{ @"Certification Roadmap", @"Examination", @"certification-roadmap.html", @"The path from member to certified professional" },
        new object?[]{ @"Recertification", @"Membership & CPD", @"recert.html", @"Renewing your status every three years" },
        new object?[]{ @"CPD Framework", @"Membership & CPD", @"cpd-framework.html", @"Continuing professional development" },
        new object?[]{ @"Membership Benefits", @"Membership & CPD", @"membership-benefits.html", @"What your membership includes" },
        new object?[]{ @"Accreditation Status", @"Membership & CPD", @"accreditation-status.html", @"Our current accreditation position" },
        new object?[]{ @"Code of Ethics", @"Governance & conduct", @"ethics.html", @"Professional and ethical standards" },
        new object?[]{ @"Conflict of Interest", @"Governance & conduct", @"coi.html", @"How we manage conflicts" },
        new object?[]{ @"Appeals Policy", @"Governance & conduct", @"appeals.html", @"Challenging a decision" },
        new object?[]{ @"Complaints Policy", @"Governance & conduct", @"complaints.html", @"Raising a concern" },
        new object?[]{ @"Impartiality Policy", @"Governance & conduct", @"impartiality-policy.html", @"Safeguarding fair assessment" },
        new object?[]{ @"AI Governance Policy", @"Governance & conduct", @"ai-policy.html", @"How governed AI is used and overseen" },
    };

    static readonly object?[][] Nav =
    {
        new object?[]{ @"Certifications", @"certification.html", @"Header" },
        new object?[]{ @"Membership", @"membership.html", @"Header" },
        new object?[]{ @"Resources", @"resources.html", @"Header" },
        new object?[]{ @"Platform", @"certuvo.html", @"Header" },
        new object?[]{ @"Organisations", @"organizations.html", @"Header" },
        new object?[]{ @"Chapters", @"chapters.html", @"Header" },
        new object?[]{ @"Sectors", @"sectors.html", @"Header" },
        new object?[]{ @"About", @"about.html", @"Header" },
        new object?[]{ @"Log in", @"login.html", @"Header account" },
        new object?[]{ @"Donate", @"donate.html", @"Header account" },
        new object?[]{ @"Why PCI", @"why-pci.html", @"Explore" },
        new object?[]{ @"How PCI Is Different", @"how-pci-is-different.html", @"Explore" },
        new object?[]{ @"Candidate Journey", @"candidate-journey.html", @"Explore" },
        new object?[]{ @"PC Manager Career Path", @"project-controls-manager-career-path.html", @"Explore" },
        new object?[]{ @"PC Director Career Path", @"project-controls-director-career-path.html", @"Explore" },
        new object?[]{ @"PMP vs AACE vs PCL-AI", @"pmp-vs-aace-vs-pcl-ai.html", @"Explore" },
        new object?[]{ @"Saudi Arabia", @"project-controls-certification-saudi-arabia.html", @"Certification by Region" },
        new object?[]{ @"UAE", @"project-controls-certification-uae.html", @"Certification by Region" },
        new object?[]{ @"USA", @"project-controls-certification-usa.html", @"Certification by Region" },
        new object?[]{ @"UK", @"project-controls-certification-uk.html", @"Certification by Region" },
        new object?[]{ @"India", @"project-controls-certification-india.html", @"Certification by Region" },
        new object?[]{ @"Pakistan", @"project-controls-certification-pakistan.html", @"Certification by Region" },
        new object?[]{ @"Donate", @"donate.html", @"About PCI" },
        new object?[]{ @"About PCI", @"about.html", @"About PCI" },
        new object?[]{ @"Founding Status", @"founding-status.html", @"About PCI" },
        new object?[]{ @"Leadership & Governance", @"leadership.html", @"About PCI" },
        new object?[]{ @"Mission & Vision", @"mission-vision.html", @"About PCI" },
        new object?[]{ @"Governance Framework", @"governance.html", @"About PCI" },
        new object?[]{ @"Accreditation Status", @"accreditation-status.html", @"About PCI" },
        new object?[]{ @"Strategic Plan", @"strategic-plan.html", @"About PCI" },
        new object?[]{ @"Annual Reports", @"annual-reports.html", @"About PCI" },
        new object?[]{ @"Certification Integrity", @"certification-integrity.html", @"About PCI" },
        new object?[]{ @"How PCI Fits", @"landscape.html", @"About PCI" },
        new object?[]{ @"FAQ", @"faq.html", @"About PCI" },
        new object?[]{ @"Enrol", @"enrol.html", @"Certifications" },
        new object?[]{ @"PCI PCL-AI", @"/certifications/pcl-ai", @"Certifications" },
        new object?[]{ @"Certification Roadmap", @"certification-roadmap.html", @"Certifications" },
        new object?[]{ @"Eligibility Requirements", @"eligibility-requirements.html", @"Certifications" },
        new object?[]{ @"Exam Structure", @"exam-structure.html", @"Certifications" },
        new object?[]{ @"Body of Knowledge", @"body-of-knowledge.html", @"Certifications" },
        new object?[]{ @"Sample Questions", @"sample-questions.html", @"Certifications" },
        new object?[]{ @"Certification Policies", @"cert-policies.html", @"Certifications" },
        new object?[]{ @"Recertification", @"recert.html", @"Certifications" },
        new object?[]{ @"Digital Credentials", @"digital-credentials.html", @"Certifications" },
        new object?[]{ @"AI Certificate", @"ai-cert.html", @"Certifications" },
        new object?[]{ @"Book an Exam", @"book.html", @"Certifications" },
        new object?[]{ @"Standard route", @"route-standard.html", @"Membership" },
        new object?[]{ @"Founding route", @"route-founding.html", @"Membership" },
        new object?[]{ @"Honorary route", @"route-honorary.html", @"Membership" },
        new object?[]{ @"Student", @"membership-student.html", @"Membership" },
        new object?[]{ @"Associate", @"membership-associate.html", @"Membership" },
        new object?[]{ @"Professional", @"membership-professional.html", @"Membership" },
        new object?[]{ @"Fellow", @"membership-fellow.html", @"Membership" },
        new object?[]{ @"Corporate", @"membership-corporate.html", @"Membership" },
        new object?[]{ @"Membership Benefits", @"membership-benefits.html", @"Membership" },
        new object?[]{ @"CPD Framework", @"cpd-framework.html", @"Membership" },
        new object?[]{ @"Candidate Handbook", @"handbook.html", @"Governance" },
        new object?[]{ @"Examination Rules", @"exam-rules.html", @"Governance" },
        new object?[]{ @"Certification Policy", @"cert-policies.html", @"Governance" },
        new object?[]{ @"Ethics Code", @"ethics.html", @"Governance" },
        new object?[]{ @"Appeals Policy", @"appeals.html", @"Governance" },
        new object?[]{ @"Complaints Policy", @"complaints.html", @"Governance" },
        new object?[]{ @"Conflict of Interest", @"coi.html", @"Governance" },
        new object?[]{ @"AI Governance Policy", @"ai-policy.html", @"Governance" },
        new object?[]{ @"Impartiality Policy", @"impartiality-policy.html", @"Governance" },
        new object?[]{ @"All policies & documents", @"policies.html", @"Governance" },
        new object?[]{ @"Guidelines & Downloads", @"downloads.html", @"Resources" },
        new object?[]{ @"Knowledge Hub", @"knowledge.html", @"Resources" },
        new object?[]{ @"Research", @"research.html", @"Resources" },
        new object?[]{ @"Publications", @"publications.html", @"Resources" },
        new object?[]{ @"White Papers", @"white-papers.html", @"Resources" },
        new object?[]{ @"Industry Reports", @"industry-reports.html", @"Resources" },
        new object?[]{ @"Salary Reports", @"salary-reports.html", @"Resources" },
        new object?[]{ @"Career Guides", @"career-guides.html", @"Resources" },
        new object?[]{ @"Webinars", @"webinars.html", @"Resources" },
        new object?[]{ @"Blog & Insights", @"blog.html", @"Resources" },
        new object?[]{ @"Certuvo platform", @"certuvo.html", @"Resources" },
        new object?[]{ @"United States", @"chapter-us.html", @"Global Chapters" },
        new object?[]{ @"United Kingdom", @"chapter-uk.html", @"Global Chapters" },
        new object?[]{ @"Europe", @"chapter-europe.html", @"Global Chapters" },
        new object?[]{ @"Saudi Arabia", @"chapter-saudi.html", @"Global Chapters" },
        new object?[]{ @"United Arab Emirates", @"chapter-uae.html", @"Global Chapters" },
        new object?[]{ @"India", @"chapter-india.html", @"Global Chapters" },
        new object?[]{ @"Pakistan", @"chapter-pakistan.html", @"Global Chapters" },
        new object?[]{ @"Canada", @"chapter-canada.html", @"Global Chapters" },
        new object?[]{ @"Australia", @"chapter-australia.html", @"Global Chapters" },
        new object?[]{ @"Aerospace & Defence", @"sector-aero.html", @"Industry Sectors" },
        new object?[]{ @"Rail & Transportation", @"sector-rail.html", @"Industry Sectors" },
        new object?[]{ @"Energy & Utilities", @"sector-energy.html", @"Industry Sectors" },
        new object?[]{ @"Oil & Gas", @"sector-oilgas.html", @"Industry Sectors" },
        new object?[]{ @"Construction & Infrastructure", @"sector-construction.html", @"Industry Sectors" },
        new object?[]{ @"Aviation", @"sector-aviation.html", @"Industry Sectors" },
        new object?[]{ @"Manufacturing", @"sector-manufacturing.html", @"Industry Sectors" },
        new object?[]{ @"Data Centres", @"sector-datacenters.html", @"Industry Sectors" },
        new object?[]{ @"Smart Cities", @"sector-smartcities.html", @"Industry Sectors" },
        new object?[]{ @"Government Programmes", @"sector-government.html", @"Industry Sectors" },
        new object?[]{ @"Refund Policy", @"refund-policy.html", @"Legal" },
        new object?[]{ @"Privacy Policy", @"privacy.html", @"Legal" },
        new object?[]{ @"Cookie Policy", @"cookie-policy.html", @"Legal" },
        new object?[]{ @"Terms of Use", @"terms.html", @"Legal" },
        new object?[]{ @"Website Disclaimer", @"website-disclaimer.html", @"Legal" },
        new object?[]{ @"Copyright Policy", @"copyright-policy.html", @"Legal" },
        new object?[]{ @"Accessibility Statement", @"accessibility-statement.html", @"Legal" },
        new object?[]{ @"Data Protection Policy", @"data-protection-policy.html", @"Legal" },
        new object?[]{ @"Log in", @"login.html", @"Verify" },
        new object?[]{ @"Reset password", @"reset-password.html", @"Verify" },
        new object?[]{ @"Verify Credential", @"verify.html", @"Verify" },
        new object?[]{ @"Digital Badge Registry", @"digital-badge-registry.html", @"Verify" },
        new object?[]{ @"Contact PCI", @"contact.html", @"Contact" },
        new object?[]{ @"Request Information", @"request-info.html", @"Contact" },
        new object?[]{ @"Corporate Programmes", @"corporate-programs.html", @"Contact" },
        new object?[]{ @"University Partnerships", @"university-partnerships.html", @"Contact" },
    };

}
