namespace PCI.Backend.Data;

/// <summary>
/// First-run content for the table-backed public sections (FAQ accordion, Body-of-Knowledge
/// domains, governance roles, policy/document lists, header &amp; footer navigation) — extracted
/// verbatim from the shipped pages, so a fresh database renders the site exactly as designed.
/// Each table is seeded ONLY when empty: operator edits and deletions are never overwritten
/// or resurrected by a restart or redeploy. Generated by scratchpad/regen-seeds.py.
/// </summary>
public static class SeedContent
{
    public static void Run(Db db)
    {
        void IfEmpty(string table, Action fill)
        {
            try { if (db.Scalar<long>($"SELECT COUNT(*) FROM `{table}`") == 0) { db.Transaction(fill); Console.WriteLine($"[seed] {table}: initial content loaded"); } }
            catch (Exception e) { Console.Error.WriteLine($"[seed] {table} skipped: {e.Message}"); }
        }
        IfEmpty("faqs", () => { var n = 0; foreach (var r in Faqs) db.Execute("INSERT INTO faqs(question,answer,category,sort_order,published) VALUES(?,?,?,?,1)", r[0], r[1], r[2], ++n); });
        IfEmpty("bok_domains", () => { var n = 0; foreach (var r in Bok) db.Execute("INSERT INTO bok_domains(code,name,weight,description,bullets,sort_order) VALUES(?,?,?,?,?,?)", "D" + (n + 1), r[1], long.Parse((string)r[0]!), r[2], r[3], ++n); });
        IfEmpty("governance_roles", () => { var n = 0; foreach (var r in Roles) db.Execute("INSERT INTO governance_roles(role,holder,status,remit,sort_order) VALUES(?,NULL,'open',?,?)", r[0], r[1], ++n); });
        IfEmpty("resources", () => { var n = 0; foreach (var r in Docs) db.Execute("INSERT INTO resources(title,category,doc_type,url,description,published,sort_order) VALUES(?,?,'Page',?,?,1,?)", r[0], r[1], r[2], r[3], ++n); });
        IfEmpty("nav_items", () => { var n = 0; foreach (var r in Nav) db.Execute("INSERT INTO nav_items(label,url,nav_group,sort_order,visible) VALUES(?,?,?,?,1)", r[0], r[1], r[2], ++n); });
        // The three access routes live under the Membership nav group. Add them idempotently on every boot
        // (AFTER the IfEmpty bulk seed) so databases seeded before the routes existed pick them up too —
        // the bulk seed only runs on an empty table. WHERE NOT EXISTS keeps it a no-op once present.
        try
        {
            foreach (var (lbl, url, so) in new[] { ("Standard route", "route-standard.html", 1), ("Founding route", "route-founding.html", 2), ("Honorary route", "route-honorary.html", 3) })
                db.Execute("INSERT INTO nav_items(label,url,nav_group,sort_order,visible) SELECT ?,?, 'Membership', ?, 1 WHERE NOT EXISTS(SELECT 1 FROM nav_items WHERE url=? AND nav_group='Membership')", lbl, url, so, url);
        }
        catch (Exception e) { Console.Error.WriteLine($"[seed] membership routes skipped: {e.Message}"); }
        // Training Partner pages (Phase 7) — added idempotently under the Organisations footer group.
        try
        {
            foreach (var (lbl, url, so) in new[] { ("Training Partners", "training-partners.html", 8), ("Become a Training Partner", "become-a-training-partner.html", 9) })
                db.Execute("INSERT INTO nav_items(label,url,nav_group,sort_order,visible) SELECT ?,?, 'Organisations', ?, 1 WHERE NOT EXISTS(SELECT 1 FROM nav_items WHERE url=? AND nav_group='Organisations')", lbl, url, so, url);
        }
        catch (Exception e) { Console.Error.WriteLine($"[seed] training partner nav skipped: {e.Message}"); }
    }

    static readonly object?[][] Faqs =
    {
        new object?[]{ @"What is the PCP-AI credential?", @"<p>The Certified Project Controls Professional — AI (PCP-AI) is a single, rigorous credential covering project controls, cost engineering and project finance, with the governed use of artificial intelligence treated as part of the discipline. It is awarded by the Project Controls Institute and built with reference to <a href=""accreditation-status.html"">ISO/IEC 17024</a> personnel-certification principles.</p>", @"The credential" },
        new object?[]{ @"Who is the PCP-AI for?", @"<p>It is for the people who hold major projects to plan, cost and cash flow: planners, schedulers, cost engineers, project-controls and PMO professionals, and project-finance specialists across construction, energy, infrastructure and software.</p>", @"The credential" },
        new object?[]{ @"Is the PCP-AI accredited?", @"<p>PCI is an independent independent certifying body. Our examinations are being developed with reference to ISO/IEC 17024. We describe our status honestly at every stage and make no claims beyond what is true today.</p>", @"The credential" },
        new object?[]{ @"How do I qualify to sit the exam?", @"<p>There are two routes: an experience route for practitioners with relevant project-controls experience, and a foundation route for those newer to the field. Full <a href=""eligibility-requirements.html"">eligibility</a> criteria are confirmed during enrolment.</p>", @"Exam & enrolment" },
        new object?[]{ @"What does the examination involve?", @"<p>The exam tests applied judgement rather than recall: scenario-based multiple-choice questions across the ten sections (93 Knowledge Areas), including the governed use of AI. It is proctored, online or at a test centre.</p>", @"Exam & enrolment" },
        new object?[]{ @"How is the credential maintained?", @"<p>The PCP-AI runs on a three-year continuing-professional-development (CPD) cycle. Membership keeps your credential current and tracks your CPD.</p>", @"Exam & enrolment" },
        new object?[]{ @"How much does it cost?", @"<p>Fees for the inaugural cohort are confirmed at enrolment. Members receive reduced rates on examinations and events.</p>", @"Exam & enrolment" },
        new object?[]{ @"Why is AI part of a project-controls credential?", @"<p>Because AI is already in the toolkit. The PCP-AI assesses the applied, governed use of AI across forecasting, risk and reporting — not generic AI literacy. Every output a certified professional relies on must be explainable, validated and owned by a competent human. In short: AI proposes; the professional disposes.</p>", @"The AI standard" },
        new object?[]{ @"What does membership include?", @"<p>Membership provides <a href=""recert.html"">recertification</a> and CPD tracking, a verifiable digital credential designed for recognition by employers, body-of-knowledge and AI-practice updates, and member rates on examinations and events.</p>", @"Membership & employers" },
        new object?[]{ @"Can my organisation certify a whole team?", @"<p>Yes. Employers can upskill an existing function or build a new project-controls capability to one benchmarked standard. <a href=""employers.html"">Read more for employers</a> or <a href=""contact.html"">contact us</a> about team enrolment.</p>", @"Membership & employers" },
        new object?[]{ @"Does PCI also sell exam preparation?", @"<p>No. PCI develops and owns the standard and the examination. Preparation and training are provided separately by Certuvo, our official partner. This separation supports the <a href=""impartiality-policy.html"">impartiality</a> expected of a body developed with reference to ISO/IEC 17024 personnel-certification principles.</p>", @"Independence & verification" },
        new object?[]{ @"How can I verify someone's credential?", @"<p>Use the credential lookup on the <a href=""verify.html"">Verify page</a> to confirm a professional's PCP-AI status.</p>", @"Independence & verification" },
    };

    static readonly object?[][] Bok =
    {
        new object?[]{ @"10", @"Project Controls Foundations & Governance", @"The role, frameworks and governance of project controls across the asset and project lifecycle.", @"Apply project-controls frameworks and terminology
Establish a controls baseline and governance cadence
Align controls with stakeholder and assurance needs" },
        new object?[]{ @"16", @"Planning & Scheduling", @"Developing, maintaining and analysing schedules that reflect reality.", @"Build logic-driven, resource-loaded schedules
Apply critical-path and schedule-risk analysis
Maintain schedule integrity and progress measurement" },
        new object?[]{ @"16", @"Cost Estimating & Control", @"Estimating, budgeting and controlling cost with integrity.", @"Develop and classify estimates
Establish and manage the cost baseline
Analyse variances and forecast cost at completion" },
        new object?[]{ @"14", @"Earned Value & Performance Management", @"Integrating cost and schedule to measure true performance.", @"Compute and interpret EVM indices
Forecast EAC/ETC from performance trends
Communicate performance to decision-makers" },
        new object?[]{ @"12", @"Risk & Contingency Management", @"Identifying, quantifying and managing uncertainty.", @"Run qualitative and quantitative risk analysis
Derive and manage cost/schedule contingency
Integrate risk into forecasts and decisions" },
        new object?[]{ @"8", @"Change & Configuration Management", @"Controlling change to the baseline with auditability.", @"Operate a disciplined change-control process
Maintain baseline configuration and traceability
Assess change impact across cost and schedule" },
        new object?[]{ @"12", @"Data, Reporting & Analytics", @"Turning controls data into trustworthy insight.", @"Ensure data quality and a single source of truth
Design clear, decision-useful reporting
Apply analytics to surface trends and exceptions" },
        new object?[]{ @"12", @"Governed AI in Project Controls", @"Using AI to augment — never replace — professional judgement.", @"Apply AI to forecasting, scheduling and analytics responsibly
Govern models, data integrity and human-in-the-loop assurance
Uphold ethics, accountability and explainability" },
    };

    static readonly object?[][] Roles =
    {
        new object?[]{ @"Responsible Officer", @"Accountable for the Institute’s operations, integrity and adherence to its own policies." },
        new object?[]{ @"Chief Examiner / Assessment Lead", @"Owns examination validity, the blueprint and the standard-setting that fixes the pass mark." },
        new object?[]{ @"Certification & Impartiality Committee", @"Independent-majority body that safeguards impartial certification decisions and manages threats to impartiality." },
        new object?[]{ @"Standards Committee", @"Owns the competency standard and the <a href=""body-of-knowledge.html"">Body of Knowledge</a>, and oversees its validation." },
        new object?[]{ @"Appeals Panel", @"Provides independent review of certification and examination decisions under the <a href=""appeals.html"">Appeals Policy</a>." },
        new object?[]{ @"Subject-Matter Experts", @"Practising experts who author and peer-review the standard and the examination items." },
    };

    static readonly object?[][] Docs =
    {
        new object?[]{ @"Terms of Enrolment", @"Enrolment & payment", @"terms-of-enrollment.html", @"What enrolment provides and the conditions that apply" },
        new object?[]{ @"Refund & Cancellation Policy", @"Enrolment & payment", @"refund-policy.html", @"Refund eligibility and how to request one" },
        new object?[]{ @"Privacy Policy", @"Enrolment & payment", @"privacy.html", @"How we handle your personal data" },
        new object?[]{ @"Cookie Policy", @"Enrolment & payment", @"cookie-policy.html", @"Cookies used on this site" },
        new object?[]{ @"Data Protection Policy", @"Enrolment & payment", @"data-protection-policy.html", @"Our data-protection commitments" },
        new object?[]{ @"Exam Structure", @"Examination", @"exam-structure.html", @"Format, domains and weighting of the PCP-AI exam" },
        new object?[]{ @"Examination Rules", @"Examination", @"exam-rules.html", @"Conduct and rules on exam day" },
        new object?[]{ @"Certification Policies", @"Examination", @"cert-policies.html", @"How certification decisions are made" },
        new object?[]{ @"Eligibility Requirements", @"Examination", @"eligibility-requirements.html", @"Who can sit the exam" },
        new object?[]{ @"Candidate Handbook", @"Examination", @"handbook.html", @"Your end-to-end guide to certification" },
        new object?[]{ @"Certification Roadmap", @"Examination", @"certification-roadmap.html", @"The path from member to certified professional" },
        new object?[]{ @"Recertification", @"Membership & CPD", @"recert.html", @"Renewing your status every three years" },
        new object?[]{ @"CPD Framework", @"Membership & CPD", @"cpd-framework.html", @"Continuing professional development" },
        new object?[]{ @"Membership Benefits", @"Membership & CPD", @"membership-benefits.html", @"What your membership includes" },
        new object?[]{ @"Accreditation Status", @"Membership & CPD", @"accreditation-status.html", @"Our current accreditation position" },
        new object?[]{ @"Code of Ethics", @"Governance & conduct", @"ethics.html", @"Professional and ethical standards" },
        new object?[]{ @"Conflict of Interest", @"Governance & conduct", @"coi.html", @"How we manage conflicts" },
        new object?[]{ @"Appeals Policy", @"Governance & conduct", @"appeals.html", @"Challenging a decision" },
        new object?[]{ @"Complaints Policy", @"Governance & conduct", @"complaints.html", @"Raising a concern" },
        new object?[]{ @"Impartiality Policy", @"Governance & conduct", @"impartiality-policy.html", @"Safeguarding fair assessment" },
        new object?[]{ @"AI Governance Policy", @"Governance & conduct", @"ai-policy.html", @"How governed AI is used and overseen" },
    };

    static readonly object?[][] Nav =
    {
        new object?[]{ @"Certifications", @"certification.html", @"Header" },
        new object?[]{ @"Membership", @"membership.html", @"Header" },
        new object?[]{ @"Resources", @"resources.html", @"Header" },
        new object?[]{ @"Platform", @"certuvo.html", @"Header" },
        new object?[]{ @"Organisations", @"organizations.html", @"Header" },
        new object?[]{ @"Chapters", @"chapters.html", @"Header" },
        new object?[]{ @"Sectors", @"sectors.html", @"Header" },
        new object?[]{ @"About", @"about.html", @"Header" },
        new object?[]{ @"Log in", @"login.html", @"Header account" },
        new object?[]{ @"Donate", @"donate.html", @"Header account" },
        new object?[]{ @"Why PCI", @"why-pci.html", @"Explore" },
        new object?[]{ @"How PCI Is Different", @"how-pci-is-different.html", @"Explore" },
        new object?[]{ @"Candidate Journey", @"candidate-journey.html", @"Explore" },
        new object?[]{ @"PC Manager Career Path", @"project-controls-manager-career-path.html", @"Explore" },
        new object?[]{ @"PC Director Career Path", @"project-controls-director-career-path.html", @"Explore" },
        new object?[]{ @"PMP vs AACE vs PCP-AI", @"pmp-vs-aace-vs-pcp-ai.html", @"Explore" },
        new object?[]{ @"Saudi Arabia", @"project-controls-certification-saudi-arabia.html", @"Certification by Region" },
        new object?[]{ @"UAE", @"project-controls-certification-uae.html", @"Certification by Region" },
        new object?[]{ @"USA", @"project-controls-certification-usa.html", @"Certification by Region" },
        new object?[]{ @"UK", @"project-controls-certification-uk.html", @"Certification by Region" },
        new object?[]{ @"India", @"project-controls-certification-india.html", @"Certification by Region" },
        new object?[]{ @"Pakistan", @"project-controls-certification-pakistan.html", @"Certification by Region" },
        new object?[]{ @"Donate", @"donate.html", @"About PCI" },
        new object?[]{ @"About PCI", @"about.html", @"About PCI" },
        new object?[]{ @"Founding Status", @"founding-status.html", @"About PCI" },
        new object?[]{ @"Leadership & Governance", @"leadership.html", @"About PCI" },
        new object?[]{ @"Mission & Vision", @"mission-vision.html", @"About PCI" },
        new object?[]{ @"Governance Framework", @"governance.html", @"About PCI" },
        new object?[]{ @"Accreditation Status", @"accreditation-status.html", @"About PCI" },
        new object?[]{ @"Strategic Plan", @"strategic-plan.html", @"About PCI" },
        new object?[]{ @"Annual Reports", @"annual-reports.html", @"About PCI" },
        new object?[]{ @"Certification Integrity", @"certification-integrity.html", @"About PCI" },
        new object?[]{ @"How PCI Fits", @"landscape.html", @"About PCI" },
        new object?[]{ @"FAQ", @"faq.html", @"About PCI" },
        new object?[]{ @"Enrol", @"enrol.html", @"Certifications" },
        new object?[]{ @"PCP-AI", @"certification.html", @"Certifications" },
        new object?[]{ @"Certification Roadmap", @"certification-roadmap.html", @"Certifications" },
        new object?[]{ @"Eligibility Requirements", @"eligibility-requirements.html", @"Certifications" },
        new object?[]{ @"Exam Structure", @"exam-structure.html", @"Certifications" },
        new object?[]{ @"Body of Knowledge", @"body-of-knowledge.html", @"Certifications" },
        new object?[]{ @"Sample Questions", @"sample-questions.html", @"Certifications" },
        new object?[]{ @"Certification Policies", @"cert-policies.html", @"Certifications" },
        new object?[]{ @"Recertification", @"recert.html", @"Certifications" },
        new object?[]{ @"Digital Credentials", @"digital-credentials.html", @"Certifications" },
        new object?[]{ @"AI Certificate", @"ai-cert.html", @"Certifications" },
        new object?[]{ @"Book an Exam", @"book.html", @"Certifications" },
        new object?[]{ @"Standard route", @"route-standard.html", @"Membership" },
        new object?[]{ @"Founding route", @"route-founding.html", @"Membership" },
        new object?[]{ @"Honorary route", @"route-honorary.html", @"Membership" },
        new object?[]{ @"Student", @"membership-student.html", @"Membership" },
        new object?[]{ @"Associate", @"membership-associate.html", @"Membership" },
        new object?[]{ @"Professional", @"membership-professional.html", @"Membership" },
        new object?[]{ @"Fellow", @"membership-fellow.html", @"Membership" },
        new object?[]{ @"Corporate", @"membership-corporate.html", @"Membership" },
        new object?[]{ @"Membership Benefits", @"membership-benefits.html", @"Membership" },
        new object?[]{ @"CPD Framework", @"cpd-framework.html", @"Membership" },
        new object?[]{ @"Candidate Handbook", @"handbook.html", @"Governance" },
        new object?[]{ @"Examination Rules", @"exam-rules.html", @"Governance" },
        new object?[]{ @"Certification Policy", @"cert-policies.html", @"Governance" },
        new object?[]{ @"Ethics Code", @"ethics.html", @"Governance" },
        new object?[]{ @"Appeals Policy", @"appeals.html", @"Governance" },
        new object?[]{ @"Complaints Policy", @"complaints.html", @"Governance" },
        new object?[]{ @"Conflict of Interest", @"coi.html", @"Governance" },
        new object?[]{ @"AI Governance Policy", @"ai-policy.html", @"Governance" },
        new object?[]{ @"Impartiality Policy", @"impartiality-policy.html", @"Governance" },
        new object?[]{ @"All policies & documents", @"policies.html", @"Governance" },
        new object?[]{ @"Guidelines & Downloads", @"downloads.html", @"Resources" },
        new object?[]{ @"Knowledge Hub", @"knowledge.html", @"Resources" },
        new object?[]{ @"Research", @"research.html", @"Resources" },
        new object?[]{ @"Publications", @"publications.html", @"Resources" },
        new object?[]{ @"White Papers", @"white-papers.html", @"Resources" },
        new object?[]{ @"Industry Reports", @"industry-reports.html", @"Resources" },
        new object?[]{ @"Salary Reports", @"salary-reports.html", @"Resources" },
        new object?[]{ @"Career Guides", @"career-guides.html", @"Resources" },
        new object?[]{ @"Webinars", @"webinars.html", @"Resources" },
        new object?[]{ @"Blog & Insights", @"blog.html", @"Resources" },
        new object?[]{ @"Certuvo platform", @"certuvo.html", @"Resources" },
        new object?[]{ @"United States", @"chapter-us.html", @"Global Chapters" },
        new object?[]{ @"United Kingdom", @"chapter-uk.html", @"Global Chapters" },
        new object?[]{ @"Europe", @"chapter-europe.html", @"Global Chapters" },
        new object?[]{ @"Saudi Arabia", @"chapter-saudi.html", @"Global Chapters" },
        new object?[]{ @"United Arab Emirates", @"chapter-uae.html", @"Global Chapters" },
        new object?[]{ @"India", @"chapter-india.html", @"Global Chapters" },
        new object?[]{ @"Pakistan", @"chapter-pakistan.html", @"Global Chapters" },
        new object?[]{ @"Canada", @"chapter-canada.html", @"Global Chapters" },
        new object?[]{ @"Australia", @"chapter-australia.html", @"Global Chapters" },
        new object?[]{ @"Aerospace & Defence", @"sector-aero.html", @"Industry Sectors" },
        new object?[]{ @"Rail & Transportation", @"sector-rail.html", @"Industry Sectors" },
        new object?[]{ @"Energy & Utilities", @"sector-energy.html", @"Industry Sectors" },
        new object?[]{ @"Oil & Gas", @"sector-oilgas.html", @"Industry Sectors" },
        new object?[]{ @"Construction & Infrastructure", @"sector-construction.html", @"Industry Sectors" },
        new object?[]{ @"Aviation", @"sector-aviation.html", @"Industry Sectors" },
        new object?[]{ @"Manufacturing", @"sector-manufacturing.html", @"Industry Sectors" },
        new object?[]{ @"Data Centres", @"sector-datacenters.html", @"Industry Sectors" },
        new object?[]{ @"Smart Cities", @"sector-smartcities.html", @"Industry Sectors" },
        new object?[]{ @"Government Programmes", @"sector-government.html", @"Industry Sectors" },
        new object?[]{ @"Refund Policy", @"refund-policy.html", @"Legal" },
        new object?[]{ @"Privacy Policy", @"privacy.html", @"Legal" },
        new object?[]{ @"Cookie Policy", @"cookie-policy.html", @"Legal" },
        new object?[]{ @"Terms of Use", @"terms.html", @"Legal" },
        new object?[]{ @"Website Disclaimer", @"website-disclaimer.html", @"Legal" },
        new object?[]{ @"Copyright Policy", @"copyright-policy.html", @"Legal" },
        new object?[]{ @"Accessibility Statement", @"accessibility-statement.html", @"Legal" },
        new object?[]{ @"Data Protection Policy", @"data-protection-policy.html", @"Legal" },
        new object?[]{ @"Log in", @"login.html", @"Verify" },
        new object?[]{ @"Reset password", @"reset-password.html", @"Verify" },
        new object?[]{ @"Verify Credential", @"verify.html", @"Verify" },
        new object?[]{ @"Digital Badge Registry", @"digital-badge-registry.html", @"Verify" },
        new object?[]{ @"Contact PCI", @"contact.html", @"Contact" },
        new object?[]{ @"Request Information", @"request-info.html", @"Contact" },
        new object?[]{ @"Corporate Programmes", @"corporate-programs.html", @"Contact" },
        new object?[]{ @"University Partnerships", @"university-partnerships.html", @"Contact" },
    };

}
