import type { CSSProperties } from 'react'

// Self-contained styles for the gate-staff scanner. The tree is deliberately NOT wired into any
// app shell yet (see README.md), so it cannot rely on the portal's global CSS classes — everything
// it needs is here. Sized for a phone/tablet held at a gate: large targets, high contrast.

export const S: Record<string, CSSProperties> = {
  root: {
    fontFamily:
      "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    color: '#0f172a',
    maxWidth: 560,
    margin: '0 auto',
    padding: '1rem',
  },
  stack: { display: 'flex', flexDirection: 'column', gap: '.9rem' },
  row: { display: 'flex', gap: '.5rem', alignItems: 'center', flexWrap: 'wrap' },
  panel: {
    border: '1px solid #e3e8ef',
    borderRadius: 12,
    padding: '1rem',
    background: '#fff',
  },
  h1: { fontSize: '1.3rem', fontWeight: 800, margin: 0 },
  h2: { fontSize: '1.05rem', fontWeight: 700, margin: '0 0 .35rem' },
  muted: { color: '#64748b', fontSize: '.92rem', margin: '.15rem 0' },
  input: {
    flex: '1 1 200px',
    fontSize: '1.1rem',
    padding: '.6rem .7rem',
    border: '1px solid #cbd5e1',
    borderRadius: 9,
  },
  btn: {
    fontSize: '1rem',
    fontWeight: 700,
    padding: '.6rem 1rem',
    background: '#1d4ed8',
    color: '#fff',
    border: 0,
    borderRadius: 9,
    cursor: 'pointer',
  },
  btnSecondary: {
    fontSize: '.95rem',
    fontWeight: 600,
    padding: '.5rem .9rem',
    background: '#fff',
    color: '#1d4ed8',
    border: '1px solid #cbd5e1',
    borderRadius: 9,
    cursor: 'pointer',
  },
  btnBig: {
    fontSize: '1.35rem',
    fontWeight: 800,
    padding: '1rem 1.5rem',
    background: '#1d4ed8',
    color: '#fff',
    border: 0,
    borderRadius: 12,
    cursor: 'pointer',
    flex: '1 1 auto',
  },
  btnBigSecondary: {
    fontSize: '1.35rem',
    fontWeight: 800,
    padding: '1rem 1.5rem',
    background: '#fff',
    color: '#0f172a',
    border: '2px solid #cbd5e1',
    borderRadius: 12,
    cursor: 'pointer',
    flex: '1 1 auto',
  },
  errNote: {
    background: '#fee2e2',
    color: '#7f1d1d',
    border: '1px solid #fecaca',
    borderRadius: 9,
    padding: '.6rem .75rem',
    marginTop: '.6rem',
  },
  warnNote: {
    background: '#fef9c3',
    color: '#713f12',
    border: '1px solid #fde68a',
    borderRadius: 9,
    padding: '.6rem .75rem',
  },
  okNote: {
    background: '#dcfce7',
    color: '#14532d',
    border: '1px solid #bbf7d0',
    borderRadius: 9,
    padding: '.8rem 1rem',
    fontWeight: 700,
    fontSize: '1.1rem',
  },
  offlineBanner: {
    background: '#7f1d1d',
    color: '#fff',
    fontWeight: 700,
    padding: '.6rem .9rem',
    borderRadius: 9,
    marginBottom: '.75rem',
    textAlign: 'center',
  },
}
